evergreen.yml

Refresh pacman cache when installing mongodb

---

evergreen.yml
scripts/run-resmoke.sh

Hopefully there is nothing too crazy here.

Move integration tests to amazon2, use Evergreen binary archive

---

src/cast_core/CMakeLists.txt
src/cast_core/include/cast_core/actors/CrudActor.hpp
src/cast_core/src/actors/CrudActor.cpp
src/driver/test/CrudActor.yml
src/driver/test/CrudActorTransaction.yml
src/gennylib/CMakeLists.txt
src/gennylib/include/gennylib/PoolFactory.hpp
src/gennylib/include/gennylib/context.hpp
src/gennylib/src/PoolFactory.cpp
src/gennylib/src/context.cpp
src/gennylib/test/ActorHelper.cpp
src/gennylib/test/ActorHelper.hpp
src/gennylib/test/CrudActor_test.cpp
src/gennylib/test/PoolFactory_test.cpp

Extremely WIP, putting it up to get another set of eyes on it because there definitely will be room for improvements. The skeleton is there for the 'aggregation' and 'bulk_write' commands which seem to be the trickiest part of the actor. 
Still TBD:
How to bind YAML syntax for operation Options.
The current syntax is reflected in the YAML configuration defined in the first test case of CrudActor_test.cpp.

TIG-1187 Crud Actor

---

THIRD-PARTY-NOTICES.txt
src/cast_core/include/cast_core/actors/HelloWorld.hpp
src/cast_core/src/actors/HelloWorld.cpp
src/cast_core/src/actors/Loader.cpp
src/cast_core/src/actors/MultiCollectionQuery.cpp
src/cast_core/src/actors/MultiCollectionUpdate.cpp
src/driver/test/BigUpdate.yml
src/gennylib/benchmark/PhaseLoop_benchmark.cpp
src/gennylib/include/gennylib/PhaseLoop.hpp
src/gennylib/include/gennylib/context.hpp
src/gennylib/include/gennylib/conventions.hpp
src/gennylib/include/gennylib/v1/ConfigNode.hpp
src/gennylib/include/gennylib/v1/GlobalRateLimiter.hpp
src/gennylib/src/GlobalRateLimiter.cpp
src/gennylib/src/context.cpp
src/gennylib/test/GlobalRateLimiter_test.cpp
src/gennylib/test/PhaseLoop_test.cpp
src/gennylib/test/conventions_test.cpp
src/gennylib/test/orchestrator_test.cpp
src/metrics/include/metrics/MetricsReporter.hpp
src/metrics/include/metrics/metrics.hpp
src/value_generators/include/value_generators/DefaultRandom.hpp
src/value_generators/src/DefaultRandom.cpp

Did a drive-by to rename _hwCounter to _helloCounter and UIntSpec to IntegerSpec.

TIG-1155 add global rate limiter

---

README.md

Add Patch-Testing Section to README

---

cmake/CheckCompiler.cmake
cmake/ConfigureInstall.cmake
cmake/FindMongoCxx.cmake
cmake/GetGRpc.cmake
cmake/GetSsl.cmake
cmake/Options.cmake
scripts/create-new-actor.sh
scripts/dry-run-workloads.sh
scripts/find-openssl.rc
scripts/generate-uuid-tag.sh
scripts/get-mongo-source.sh
scripts/run-resmoke.sh
src/cast_core/include/cast_core/actors/CrudActor.hpp
src/gennylib/include/gennylib/ActorProducer.hpp
src/gennylib/include/gennylib/Cast.hpp
src/gennylib/include/gennylib/MongoException.hpp
src/gennylib/include/gennylib/PhaseLoop.hpp
src/gennylib/include/gennylib/PoolManager.hpp
src/gennylib/include/gennylib/context.hpp
src/gennylib/include/gennylib/conventions.hpp
src/gennylib/src/Cast.cpp
src/gennylib/src/PoolManager.cpp
src/gennylib/src/context.cpp
src/gennylib/test/NopActor.hpp
src/value_generators/include/value_generators/value_generators.hpp

Had an itch to scratch. Removed a few `WorkloadContext` methods that aren't used and move some impls to `.cpp` files to be consistent.

Remove cruft

---

README.md

TIG-1408 update README with simplified genny patch build steps

---

src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActor_test.cpp
src/cast_core/test/RunCommandActor_test.cpp
src/cast_core/test/actors_test.cpp

TIG-1434 use count_documents instead of count

---

README.md
scripts/lamp

CLion got me down so added the option to build with make 😸

Allow user to build with make rather than ninja

---

src/python/genny/cedar.py
src/python/genny/cedar_report.py
src/python/genny/csv2.py
src/python/setup.py
src/python/tests/cedar_report_test.py
src/python/tests/cedar_test.py

Class design follows 10gen/dsi#315

TIG-1481 TIG-1483 create cedar report and send to poplar

---

src/python/genny/cedar_report.py
src/python/tests/cedar_report_test.py

Depends on https://github.com/10gen/dsi/pull/346

TIG-1577 update to latest poplar report schema

---

Doxyfile
scripts/create-new-actor.sh
src/cast_core/include/cast_core/actors/CrudActor.hpp
src/cast_core/include/cast_core/actors/HelloWorld.hpp
src/cast_core/include/cast_core/actors/Insert.hpp
src/cast_core/include/cast_core/actors/RunCommand.hpp
src/testlib/include/testlib/clocks.hpp

Genny's doxygen site still leaves a lot to be desired but at least remove some cruft.
Here's the site after these changes: http://genny-docs.s3-website-us-east-1.amazonaws.com/html/

Remove v1 and inner PhaseConfig cruft

---

scripts/lamp

This isn't the full scope of the fix for TIG-1518 but it is a step there.

TIG-1518: Quote lamp args

---

src/lamplib/context.py

Use updated toolchain with cross-platform SSL support

TIG-1432 update toolchain

---

src/metrics/include/metrics/metrics.hpp
src/metrics/include/metrics/operation.hpp
src/metrics/test/metrics_test.cpp

Ready for preliminary review. This approach was easier for me to implement than templating all the things. But I'm open to other suggestions if the code looks ugly.
The error message from exceeding the threshold still needs to be fleshed out.

TIG-1271 Allow Specifying Threshold to metrics operations

---

src/cast_core/src/CrudActor.cpp

Few light housekeeping things before I add more functionality:
1. switch to `BOOST_THROW_EXCEPTION`
2. `std::move` in operation ctor params
3. Record documents and bytes metrics where appropriate
Sys-perf patch: https://evergreen.mongodb.com/version/5cb0d1c50ae606414132d48b

TIG-1397: Crud Actor 💅

---

scripts/create-new-actor.sh

I'm going to add some more documentation to the generated example Actor. Heredoc syntax is much nicer to work with so converting to that before adding/changing anything else.

Convert create-new-actor.sh echo blocks to cat/heredoc syntax

---

src/python/genny/legacy_report.py

Please review the other half of this ticket first: https://github.com/10gen/dsi/pull/355
`perf.json` results currently look like this: `InsertRemove.InsertRemoveTest.Insert`. This ticket will change them them to look like this: `InsertRemove.InsertRemoveTest-Insert`.

TIG-1617 Use - to concatenate actor and op name in perf.json

---

src/python/genny/cedar_report.py
src/python/tests/cedar_report_test.py

[patch build](https://evergreen.mongodb.com/version/5ce408cb0ae6065ef952660a)

TIG-1659: fix name of order field

---

src/driver/src/DefaultDriver.cpp

Example metrics file header:
```
OperationThreadCounts
actor,operation,workers
HelloWorld,ActorFinished,1
HelloWorld,ActorStarted,1
HelloWorld,DefaultMetricsName.0,2
HelloWorld,DefaultMetricsName.1,2
HelloWorld,DefaultMetricsName.2,2
HelloWorld,Setup,1
```

TIG-1677 rename Genny.Setup metric to [workload name].Setup

---

src/gennylib/include/gennylib/PhaseLoop.hpp
src/gennylib/include/gennylib/v1/GlobalRateLimiter.hpp

I tacked on my rate limiter jitter change to this PR as well. It doesn't fix anything but is a usability improvement for local development.
DSI patch: https://evergreen.mongodb.com/version/5d12257361837d34ce78cee7

TIG-1780 reset the rate limiter before the start of each phase

---

src/canaries/benchmark/canaries_benchmark.cpp
src/gennylib/include/gennylib/PhaseLoop.hpp
src/gennylib/include/gennylib/v1/GlobalRateLimiter.hpp
src/gennylib/test/GlobalRateLimiter_test.cpp

I think the overall approach is correct but I need to fix up the perf tests at least and maybe some edge cases.
(FYI I'm putting up this PR after Ryan showed me Luke's WT caching actor and we determined that he needed this functionality)

TIG-1847 global rate limiter should burst across all available threads

---

src/cast_core/include/cast_core/actors/CollectionScanner.hpp
src/cast_core/src/CollectionScanner.cpp
src/workloads/docs/CollectionScanner.yml

Third attempt at this PR sorry for the mess.
This PR improves the CollectionScanner to meet the criteria of the LSWA. I've added a few configurations, the index specification is met using the Filter configuration. I think the read at a snapshot configuration is met by specifying a begin transaction with read concern majority but I'm not 100% certain on that.

TIG-1894 Extending collection scanner to match large scale workload requirements

---

src/workloads/scale/UpdateMillionDocsInTxn.yml

https://evergreen.mongodb.com/version/5d5efc8fa4cf471f304cdc9f (Patch name is under the SERVER ticket, not the PERF ticket I later created)

PERF-1911 Test million documents transaction

---

src/metrics/include/metrics/Period.hpp
src/metrics/include/metrics/metrics.hpp
src/metrics/include/metrics/operation.hpp
src/metrics/test/metrics_test.cpp
src/testlib/include/testlib/clocks.hpp

Still WIP - need to add some testing and re-jigger some types/aliases to be consistent - but wanted to get this out there for feedback on the API.
cc @luke-pearson

Ability to directly record computed/synthetic metrics

---

src/workloads/execution/BackgroundValidateCmd.yml

TIG-2023 Create a new workload to perform CRUD operations during background validation to visualize impact on throughput and latency

---

src/cast_core/src/HelloWorld.cpp
src/metrics/include/metrics/MetricsReporter.hpp
src/metrics/include/metrics/metrics.hpp
src/metrics/include/metrics/operation.hpp
src/metrics/include/metrics/v1/TimeSeries.hpp
src/metrics/include/metrics/v1/passkey.hpp
src/metrics/test/metrics_test.cpp

TIG-1984 Update Synthetic Metrics Events API and Add Testing

---

scripts/genny_auto_tasks.sh
src/python/genny/genny_auto_tasks.py
src/python/setup.py
src/python/tests/auto_tasks_test.py

Main components of this PR:
- `genny_auto_tasks.sh` sets up the virtualenv and installs dependencies
- `genny_auto_tasks.py` actually generates and outputs the json
- `auto_tasks_test.py` contains the unit test for the above

TIG-2076 Add bash and python scripts for generating task json for modified workloads

---

src/python/genny/genny_auto_tasks.py

Autorun: Allow --forced-workloads without --modified

---

src/gennylib/include/gennylib/context.hpp

Just makes actor ids indexed from 1.

TIG-2479 Don't send 0 ActorIDs to Poplar

---

src/workloads/execution/UnionWith.yml

JIRA: https://jira.mongodb.org/browse/PERF-1959
CR url: https://mongodbcr.appspot.com/572650018/

PERF-1959 Add sys-perf tests for $unionWith aggregation stage

---

src/workloads/execution/UnionWith.yml

Add 3 Node ReplSet variant to UnionWith workload.

PERF-1959 Add replica variant to unionWith perf tests

---

src/workloads/docs/RunCommand-Simple.yml

Should fix https://jira.mongodb.org/browse/BF-16960
```
[2020/04/18 08:41:15.057] Traceback (most recent call last):
[2020/04/18 08:41:15.057]   File "/data/mci/fdb2c462de7960da7cf777d14ad53581/src/genny/genny/src/python/venv/bin/genny-auto-tasks", line 11, in <module>
[2020/04/18 08:41:15.057]     load_entry_point('genny', 'console_scripts', 'genny-auto-tasks')()
[2020/04/18 08:41:15.057]   File "/data/mci/fdb2c462de7960da7cf777d14ad53581/src/genny/genny/src/python/gennylib/auto_tasks.py", line 441, in main
[2020/04/18 08:41:15.057]     tasks = repo.tasks(op, build)
[2020/04/18 08:41:15.057]   File "/data/mci/fdb2c462de7960da7cf777d14ad53581/src/genny/genny/src/python/gennylib/auto_tasks.py", line 332, in tasks
[2020/04/18 08:41:15.057]     tasks = self.variant_tasks(build)
[2020/04/18 …
```

TIG-2503 Fix autorun on sys-perf waterfall

---

src/workloads/scale/LargeScaleModel.yml

Patch: https://evergreen.mongodb.com/version/5e99e29d850e6158128d1594

TIG-2509 Run the large scale model workload with FTDC outputs

---

src/gennylib/include/gennylib/MongoException.hpp

No luck in recreating the underlying BF due to purples in my patch. :(

TIG-2555 Capture what strings in MongoExceptions when present

---

src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActorYamlTests.yml

Added findOne support to the crud actor while working on porting over mixed workloads. I'll put that up for a separate review.

TIG-2564 Add findOne support to CrudActor

---

src/workloads/execution/CreateBigIndex.yml
src/workloads/execution/CreateIndex.yml

I found I wish I had results on 3 node replica set for this. This PR is to add it. @louiswilliams any reason not to do it? I know we didn't originally include it.

PERF-2020 Run CreateIndex and CreateBigIndex on more variants

---

src/cast_core/src/CrudActor.cpp
src/gennylib/include/gennylib/context.hpp
src/workloads/docs/CrudActor.yml

TIG-2618 Allow CrudActor to specify which connection pool (Client) to use

---

src/lamplib/tasks/download.py
src/lamplib/tasks/run_tests.py
src/python/README.md
src/python/gennylib/auto_tasks.py
src/python/gennylib/canaries_runner.py
src/python/gennylib/genny_runner.py
src/python/gennylib/legacy_report.py
src/python/requirements.txt
src/python/setup.py
src/python/tests/auto_tasks_test.py
src/python/tests/cedar_report_test.py

Will depend on a couple other changes in DSI and the server

SERVER-50133 Kill "Legacy" Auto-Tasks Logic

---

src/gennylib/src/PoolFactory.cpp
src/gennylib/test/PoolFactory_test.cpp

Sys-perf patch build: https://spruce.mongodb.com/version/5f89ab98c9ec446bcf0ec04b/tasks

TIG-2608 Add appName=Genny to Genny URI

---

evergreen.yml
scripts/get-mongo-source.sh
src/cast_core/test/CrudActorYamlTestRunner.cpp
src/cast_core/test/RunCommandActor_test.cpp
src/gennylib/benchmark/PhaseLoop_benchmark.cpp
src/gennylib/src/PoolFactory.cpp
src/gennylib/test/PoolFactory_test.cpp
src/lamplib/tasks/download.py
src/lamplib/tasks/run_tests.py
src/python/requirements.txt
src/python/setup.py
src/testlib/src/MongoTestFixture.cpp

Most of the work was in the toolchain, which was already pushed. Green build here: https://evergreen.mongodb.com/version/genny_toolchain_0db5d1544746c1570371f51109a0a312a7215b65

TIG-2643 update c++ driver version to 3.6.0

---

src/lamplib/tasks/download.py

My personal laptop came back from the shop with Catalina. I tried `lamp` and hastily read the text and skipped the reboot. It didn't work. I cursed and googled. And read the SO article. And googled more. Then I finally read the text again. Rebooted and re-ran stuff and it worked. Let's help users avoid that.

Expand on lamp message for Catalina users

---

src/workloads/contrib/historystore/README
src/workloads/contrib/historystore/eMRCfBench.yml
src/workloads/contrib/historystore/eMRCfGrow.yml
src/workloads/contrib/historystore/eMRCfPopulate.yml
src/workloads/contrib/historystore/eMRCf_runner.sh

Adding a set of tests and scripts written to evaluate the impact
of growing the WiredTiger history store in a PSA replica set with
a failed secondary node.  The README file provides details.

WT-6790 Package and document eMRCf tests

---

src/metrics/include/metrics/MetricsReporter.hpp
src/metrics/include/metrics/operation.hpp
src/metrics/test/metrics_test.cpp

Patch build: https://evergreen.mongodb.com/version/5fd0fe351e2d17517b6258d4

TIG-2804 Swap ops and number in genny

---

src/value_generators/include/value_generators/DocumentGenerator.hpp
src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocGenYamlTestCaseRunner.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml

This involved plumbing ActorID through a lot of stuff. I've added a ^ThreadID and a ^ThreadIDString generators. First one returns an int, the second a string.

PERF-2071 Add ^ActorId value generators to Genny

---

src/phases/scale/LargeScalePhases.yml
src/workloads/scale/ScanWithLongLived.yml

This PR is configuring the new LSWA workload to take advantage of the functionality added in #396.

WT-6968 Configure new workload to use fixed-rate scanning

---

src/metrics/include/metrics/metrics.hpp
src/metrics/test/metrics_test.cpp

Basically stops extra streams from being created, details in ticket.

TIG-2826 Metrics are not being reported for CrudActor in ReshardCollection.yml workload

---

README.md
src/gennylib/src/context.cpp
src/lamplib/src/genny/curator.py

Related: https://github.com/10gen/dsi/pull/840

TIG-2896 Don't store CedarMetrics in WorkloadOutput

---

src/workloads/issues/ConnectionsBuildup.yml

One of three changes for https://jira.mongodb.org/browse/PERF-2096. This one is a new workload to reproduce the connections buildup issue.
As this workload is to reproduce a specific issue (and ensure that we won't have a regression there), I created a separate folder 'issues' in 'workloads'

PERF-2096 ConnectsBuildup workload

---

src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml

I renamed arrayGenerator to literalArrayGenerator (mean it is a literal array of one or more generators) so that I could then implement an array generator.
I think that makes sense but I'm happy to take feedback to clarify.

TIG-2918 generate arrays

---

README.md

TIG-2882 added a workaround

---

src/workloads/docs/LongLivedReader.yml
src/workloads/scale/LargeScaleLongLived.yml
src/workloads/scale/LargeScaleModel.yml

TIG-2744 move Globalrate of LargeScaleModel, LargeScaleLongLived, and LongLivedReader to each phases

TIG-2744 Fix GlobalRate in Large-Scale workloads

---

src/cast_core/src/CollectionScanner.cpp

Without this try / catch the new LLT workloads can eixt with something like:
```
[2021-03-25 20:37:53.612019] [0x00007f04e59d3700] [error]   Operation exception Transaction 76771 has been aborted.: generic server error
[2021-03-25 20:37:53.612088] [0x00007f04e59d3700] [debug]   
Dynamic exception type: mongocxx::v_noabi::operation_exception
std::exception::what: Transaction 76771 has been aborted.: generic server error
```
These sort of exceptions are transient and recoverable and shouldn't cause the workload to exit

PERF-2232 catch and count transaction operation exceptions

---

src/lamplib/src/genny/tasks/auto_tasks.py

PB: https://evergreen.mongodb.com/version/605a5792e3c33125a45cda2a

TIG-2878 Add logging to task-gen

---

src/cast_core/include/cast_core/actors/OptionsConversion.hpp
src/cast_core/src/CrudActor.cpp
src/workloads/scale/LLTRemove.yml

Continuing to add more workloads.

 PERF-2181 LLT remove workloads

---

src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActorYamlTests.yml
src/workloads/docs/CrudActorTransaction.yml
src/workloads/scale/ReplaceMillionDocsInSeparateTxns.yml
src/workloads/scale/UpdateMillionDocsInTxn.yml

I'll probably do some DRY cleanup in crud actor but this should be functional (at least the yaml test works). Running the workloads in a patch now.

TIG-2695 add withTransaction to CrudActor and replace startTxn/commitTxn in workloads

---

src/workloads/scale/LLTMixed.yml

Added LoggingActor to the mixed workload - otherwise it fails.

PERF-2240: 'Create LLT Benchmark Mixed Workload' added LoggingActor

---

src/workloads/scale/LLTInsert.yml
src/workloads/scale/LLTMixed.yml
src/workloads/scale/LLTQuery.yml
src/workloads/scale/LLTRemove.yml
src/workloads/scale/LLTUpdate.yml

fix clients, durations and transactionLfetimeLimitSeconds.

PERF-2182 Cleanup workloads

---

.github/CODEOWNERS

Noticed I wasn't being notified of PRs.

TIG-3042 Update Genny CODEOWNERS to TIPS

---

src/cast_core/src/CollectionScanner.cpp
src/workloads/docs/CollectionScanner.yml

This commit makes PERF-2317 easier (and any new workloads could be committed to the waterfalls).

TIG-3041 Add aggregation support to collection scanner.

---

src/workloads/execution/ExpressiveQueries.yml

[First Evergreen run](https://evergreen.mongodb.com/version/609d25fc2fbabe6ccd812b53)
[Evergreen for commit f613ed8](https://evergreen.mongodb.com/version/60a4d01fa4cf47685f54cf12)

PERF-2300: Add expressive queries to sys-perf workload

---

src/workloads/transactions/LLTInsertLowLtc.yml
src/workloads/transactions/LLTMixedLowLtc.yml
src/workloads/transactions/LLTQueryLowLtc.yml
src/workloads/transactions/LLTRemoveLowLtc.yml
src/workloads/transactions/LLTUpdateLowLtc.yml

Look at mixed last. This PR cuts down on the repetition (and will hopefully make life easier in future).
[Patch](https://spruce.mongodb.com/version/60a4ed630ae6063e3d0f1d20/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=%5Elinux-1-node-replSet%24) is currently progressing.
There will be one more PR after this one, but while it will be a large diif it will be mostly boiler plate cut and paste.

PERF-2260 use actor templates

---

src/workloads/transactions/LLTInsertHighGtc.yml
src/workloads/transactions/LLTInsertHighLtc.yml
src/workloads/transactions/LLTMixedHighGtc.yml
src/workloads/transactions/LLTMixedHighLtc.yml
src/workloads/transactions/LLTQueryHighGtc.yml
src/workloads/transactions/LLTQueryHighLtc.yml
src/workloads/transactions/LLTRemoveHighGtc.yml
src/workloads/transactions/LLTRemoveHighLtc.yml
src/workloads/transactions/LLTUpdateHighGtc.yml
src/workloads/transactions/LLTUpdateHighLtc.yml
src/workloads/transactions/README.md

PERF-2260 fix high rate

---

src/workloads/execution/CumulativeWindows.yml

https://jira.mongodb.org/browse/PERF-2277
Test | 1 | 8 | Max
-- | -- | -- | --
CumulativeWindows.Avg | 49,321,199 | &nbsp; | 49,321,199
CumulativeWindows.CovPop | 62,363,598 | &nbsp; | 62,363,598
CumulativeWindows.CovSamp | 62,340,876 | &nbsp; | 62,340,876
CumulativeWindows.StdDevPop | 49,672,157 | &nbsp; | 49,672,157
CumulativeWindows.StdDevSamp | 49,887,726 | &nbsp; | 49,887,726
CumulativeWindows.Sum | 53,042,569 | &nbsp; | 53,042,569

PERF-2277 Benchmarks for cumulative aggregation window functions

---

src/lamplib/src/genny/curator.py

See ticket for comment rationale.

TIG-3063 Update pinned curator

---

src/workloads/sharding/ReshardCollection.yml

Also removes the {ThrowOnFailure: false} handling from updateOne operations now that it is no longer needed.

PERF-2349: Fix "Threads" spec in ReshardCollection.yml

---

src/workloads/transactions/LLTAnalytics.yml

Not sure if it makes sense to merge as is - but I'd like to get some feedback earlier as we are pressed to finish the project. I plan to play with data size and try mixed workload (copied from LLT). So at least these two things probably would be changed. 
The main part I want your feedback is data structure and aggregation pipeline. And, of course, everything else to improve it.

PERF-2317 Extend LLT measurements for Analytics workloads

---

src/cast_core/include/cast_core/actors/Loader.hpp
src/cast_core/src/Loader.cpp
src/workloads/docs/Loader.yml

[patch](https://spruce.mongodb.com/version/60e82a780ae6060b4eaef626/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

TIG-3201 Update genny loader to support multiple threads per collections

---

src/lamplib/src/genny/cli.py
src/lamplib/src/genny/curator.py

Make sure to review https://github.com/mongodb/genny/blob/master/docs/developing.md

STAR-2112 Fix lint issues associated with PRs #514 and #521 

---

src/gennylib/include/gennylib/Node.hpp
src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml

PERF-2525 Add ^FormatString generator to genny

PERF-2526 Add ObjectId Generator

---

src/lamplib/src/genny/tasks/dry_run.py
src/workloads/docs/CrudActorFSM.yml
src/workloads/docs/CrudActorFSMAdvanced.yml
src/workloads/docs/StateMachineCrudActor.yml

This is just the example document. When we are happy with it I will start on implementing the beast. Please pay particular attention to the syntax and ergonomics. If there are small things we can do to make it more similar to other FSM we use, let me know.

PERF-2078 Example workload for proposed State Machine Functionality for Crud Actor.

---

src/value_generators/src/DocumentGenerator.cpp

Adds ^Inc to the int generator list (it was missing)
Adds a int to string wrapper generator.

Generator Updates

---

docs/setup.md

I broke this with the last update

Add -d to install doc

---

CMakeLists.txt
cmake/FindMongoCxx.cmake
src/gennylib/include/gennylib/parallel.hpp
src/gennylib/test/Node_test.cpp
src/lamplib/src/genny/download.py
src/lamplib/src/genny/tasks/compile.py
src/lamplib/src/genny/toolchain.py

This reverts commit 4b1d379dea870ef0c39bd92f665eb496f5e0f7f8.

Revert "TIG-3599 Update genny to use new vcpkg/toolchain (#581)"

---

src/workloads/execution/DensifyFillCombo.yml

patch nearing done: https://spruce.mongodb.com/version/61ba216e7742ae0dfb469b10/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-2729: Add perf test for densify/fill  combo

---

CMakeLists.txt
cmake/FindMongoCxx.cmake
src/gennylib/include/gennylib/parallel.hpp
src/gennylib/test/Node_test.cpp
src/lamplib/src/genny/download.py
src/lamplib/src/genny/tasks/compile.py
src/lamplib/src/genny/toolchain.py

This reverts commit 31b844471ddad42c21a108e5398f7f2e121858bc.

Revert "TIG-3599 Update genny to use new vcpkg/toolchain (#598)"

---

src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActorYamlTestRunner.cpp
src/cast_core/test/CrudActorYamlTests.yml
src/workloads/docs/CrudActorTransaction.yml

Testing remains a sore point for this.
- There are no unit tests for actors at this point, so I'd be starting from scratch there. This would be incredibly painful
- The changes I've made to the integration test are at the very least an assertion that OnSession won't crash.
- There does not appear to be a reasonable way to assert

TIG-3651 Respect OnSession for operations inside CrudActor's WithTransaction op

---

src/phases/execution/TimeSeriesLastpoint.yml
src/workloads/execution/TimeSeriesLastpoint.yml

Evergreen patch: https://spruce.mongodb.com/version/621cf72b3627e06fd97624fa/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-2814 Add remaining cases for lastpoint type queries

---

src/phases/execution/MultiDeletes.yml
src/workloads/execution/MultiDeletesBatched.yml
src/workloads/execution/MultiDeletesDocByDoc.yml

Evergreen: https://spruce.mongodb.com/version/622a04e6c9ec440d0c012012/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-2824 Add BATCHED_DELETE perf workload

---

src/phases/execution/TimeSeriesLastpoint.yml

🌲 [patch](https://spruce.mongodb.com/version/624d5b5f3627e0623ae919cd/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=lastpoint)

PERF-2919 Update lastpoint workload to also test smaller selectivity

---

src/workloads/scale/MajorityReads10KThreads.yml
src/workloads/scale/MajorityWrites10KThreads.yml
src/workloads/scale/Mixed10KThreads.yml

[Evergreen patch](https://spruce.mongodb.com/version/62470de05623434c1de7fce2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-2914 Add workload with 10k simultaneous threads

---

src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/execution/MetricSecondaryIndexTimeseriesCollection.yml
src/workloads/execution/TimeSeries2dsphere.yml

I started a patch build here: https://spruce.mongodb.com/version/624f530661837d6b5e6c9067/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-2534 and PERF-2756 Time-series metric indexes (ascending/descending, 2dsphere)

---

src/phases/scale/DesignDocWorkloadPhases.yml
src/workloads/scale/LargeScaleParallel.yml
src/workloads/scale/LargeScaleSerial.yml

Just some docs, hopefully nothing too controversial.

TIG-3722 Document WiredTiger genny workloads

---

src/cast_core/src/Loader.cpp
src/workloads/docs/Loader.yml

Patch build: https://evergreen.mongodb.com/patch/626c3d8a1e2d1750d3d66217?redirect_spruce_users=true

PERF-2969: Add assert if Loader phase threads > Loader Actor threads

---

src/phases/tpch/denormalized/Q15.yml
src/phases/tpch/normalized/Q15.yml

[patch](https://spruce.mongodb.com/version/627151291e2d170bc6a17622/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-2984  remove create view metrics

---

.github/CODEOWNERS

TIG-4170 More precise codeowners

---

.github/CODEOWNERS

Docs here: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

TIG-4170 Codeowner fix globbing

---

src/workloads/docs/HelloWorld-MultiplePhases.yml

Fix iteration count example for multiple threads

---

src/workloads/networking/CommitLatency.yml
src/workloads/networking/CommitLatencySingleUpdate.yml

Fixed MacOS compilation errors from previous PR

PERF-2926 Fix CommitLatency workloads and add to autorun

---

src/workloads/scale/BigUpdate.yml
src/workloads/scale/BigUpdate10k.yml
src/workloads/scale/InsertRemove.yml
src/workloads/transactions/LLTMixed.yml

consolidate the keywords format to use camel case

consolidate the keywords format

---

src/cast_core/include/cast_core/actors/CollectionScanner.hpp
src/cast_core/src/CollectionScanner.cpp
src/cast_core/test/CollectionScanner_test.cpp
src/workloads/docs/CollectionScanner.yml
src/workloads/transactions/LLTMixed.yml

Patch running [here](https://spruce.mongodb.com/version/62c58bb3c9ec44082d388f84/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-3138 GenerateCollectionNames error checking, added test and updated docs example

---

src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml
src/workloads/docs/RunCommand-Simple.yml
src/workloads/scale/LargeIndexedIns.yml

Leverage the existing code for the simplest possible implementation.

PERF-3132 simple ^Date generator

---

docs/setup.md

A user ran into this issue recently, and I also ran into it some time ago. I'd like to clarify the docs here to help set expectations.

Mention ./run-genny clean in install instructions

---

src/workloads/scale/LargeIndexedIns.yml

Updated the workload to remove the update operations and unused fields from the index.

PERF-3196: Large index insert test does not perform any update operation after the index is created.

---

src/value_generators/src/DocumentGenerator.cpp

Updated the randomDouble generator comments to reflect that we are returning double, not int

PERF-3181: Incorrect comment in DocumentGenerator.cpp

---

src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml

Evergreen: https://spruce.mongodb.com/version/62f520f13e8e86413d301936/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Add a zipfian distribution generator. The class implements the inverse transform sampling algorithm. A couple of tests were added.

PERF-3197 Add Zipfian distribution to int generator

---

src/workloads/execution/BackgroundValidateCmd.yml

Patch: 
https://spruce.mongodb.com/version/62ffd82f32f41720f42e12ef/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

TIG-4274 Remove throttling for BackgroundValidateCmd workload

---

src/workloads/execution/ColumnStoreIndex.yml

See the ticket and linked BF for a writeup.

PERF-3252 Avoid overlapping dependencies in BrowserUsageByDistinctUser

---

src/workloads/execution/BackgroundTTLDeletions.yml
src/workloads/scale/ContentionTTLDeletions.yml

Adding @dalyd to see if this workload makes sense to test the impact of TTL deletions

PERF-3049 Add workload for Background TTL deletions

---

src/workloads/execution/MatchFilters.yml

Evergreen: https://spruce.mongodb.com/version/63445cde30661531116919cd/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-3396 Implement missing performance tests for match filters

---

src/workloads/execution/ArrayTraversal.yml
src/workloads/execution/FilterWithComplexLogicalExpression.yml
src/workloads/execution/RepeatedPathTraversal.yml

evergreen: https://spruce.mongodb.com/version/635066900ae60652abec61a7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-3397 Extend filter dotted paths performance tests

---

src/phases/execution/AggregateExpressions.yml
src/workloads/execution/AggregateExpressions.yml

[Evergreen](https://spruce.mongodb.com/version/635c16ed1e2d17773e7678dc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-3402: Add end to end agg expression tests

---

build/.gitignore
evergreen.yml
src/lamplib/src/genny/cli.py
src/lamplib/src/genny/curator.py
src/lamplib/src/genny/tasks/compile.py
src/lamplib/src/genny/tasks/run_tests.py
src/lamplib/src/genny/toolchain.py

There are some special cases in this code that we will need to take care of. I would like to defer any heavy lifting right now, but am happy to do easy things. This goes with a hand crafted genny toolchain for arm. I'll share notes on that also. 
This works in my test environment. I haven't tested the download portions of it, but I will try that tomorrow. Please take a look.

PERF-3431 First Graviton support for Genny

---

src/workloads/contrib/analysis/test_result_summary.py

PERF-3576 Update test_result_summary.py

---

src/workloads/query/SSBColumnStoreIndex.yml

evergreen: https://spruce.mongodb.com/version/639796491e2d175eb411f6b9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-3653: Add common prefix pairs to ssb_column_store_comparison test names

---

src/workloads/query/CsiHeavyDiskUsage.yml

Companion PRs:
https://github.com/10gen/dsi/pull/1137
https://github.com/10gen/mongo/pull/8810
Evergreen patches:
https://spruce.mongodb.com/version/63b870a02fbabe308124399b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC (1 run)
https://spruce.mongodb.com/version/63bdbfbb0305b968659ffb61/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC (3 reruns)
https://spruce.mongodb.com/version/63bf3fbd3627e06c3018361a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC (1 run)

PERF-3461 New workload for inserting into a large dataset in presence of CSI index

---

src/workloads/docs/LongLivedWriter.yml
src/workloads/scale/LargeScaleLongLived.yml

Patch Build: https://evergreen.mongodb.com/version/63d96180d6d80a7d9d22594f

PERF-3771 Fix rate limit typo in Long Lived workloads

---

src/value_generators/src/DocumentGenerator.cpp

I observed segfaults in Genny while running tests in evergreen which used `TakeRandomStringFromFrequencyMapSingleton`. After running Genny locally with tsan, I observed that data races were occurring between FrequencyMapGenerator's use of RNG, and other generators' RNG use.
Digging into `FrequencyMapSingletonGenerator`, I noticed that in multithreaded environments, the first thread to make their `FrequencyMapSingletonGenerator` would construct the underlying `FrequencyMapGenerator` in the global table. All uses of this `FrequencyMapGenerator` across all actors would be protected by a mutex. Unfortunately, the `FrequencyMapGenerator` was constructed using the first thread's `GeneratorArgs`, and so would capture a reference to its `DefaultRandom`. `DefaultRandom` is intended to belong to a …

EVG-19030 Propagate FrequencyMapSingletonGenerator's DefaultRandom

---

src/workloads/execution/TimeSeriesRangeDelete.yml

patch:
https://spruce.mongodb.com/version/6413d3e80ae6060dd9baea71/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=delete

PERF-3752 Add new time-series multi delete workload

---

.github/pull_request_template.md

Jira Ticket: [PERF-3531](https://jira.mongodb.org/browse/PERF-3531)
Whats changed:
We've update the PR template the help guide users to provide better documentation when submitting code changes

PERF-3531 - Add PR template form

---

src/workloads/contrib/analysis/test_result_summary.py

**Jira Ticket:** PERF-4074
Fix the display format of milliseconds in my perf results summary script.
N/A
N/A
N/A

PERF-4074 Increase precision in metrics summary script

---

src/workloads/scale/BigUpdate.yml
src/workloads/scale/MixedWorkloadsGennyStress.yml

**Jira Ticket:** < Ticket Number >
High level explanation of changes
PLEASE READ AND REMOVE THE SECTION BELOW BEFORE SUBMITTING YOUR PR FOR REVIEW
1.  Once (1) you get approval from the STM or the Product Perf team for your change and (2) all your CI tests pass, you can initiate a merge …

run genny tasks with execution control off

---

src/workloads/query/TimeSeriesSort.yml

[patch](https://spruce.mongodb.com/version/645d24891e2d172177bb2ed9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-3395 Clean up TimeSeriesSort.yml

---

src/phases/query/RunLargeArithmeticOp.yml
src/workloads/query/ConstantFoldArithmetic.yml
src/workloads/query/CumulativeWindows.yml
src/workloads/query/DensifyFillCombo.yml
src/workloads/query/DensifyHours.yml
src/workloads/query/DensifyMilliseconds.yml
src/workloads/query/DensifyMonths.yml
src/workloads/query/DensifyNumeric.yml
src/workloads/query/DensifyTimeseriesCollection.yml
src/workloads/query/FillTimeseriesCollection.yml
src/workloads/query/LookupWithOnlyUnshardedColls.yml
src/workloads/query/MetricSecondaryIndexTimeseriesCollection.yml
src/workloads/query/SlidingWindows.yml
src/workloads/query/TimeSeries2dsphere.yml
src/workloads/query/TimeSeriesSortCompound.yml
src/workloads/query/linearFill.yml
src/workloads/query/locf.yml

Reverts mongodb/genny#877
This was causing:
* https://jira.mongodb.org/browse/BF-28753
* https://jira.mongodb.org/browse/BF-28754

Revert "PERF-3784: Replace RunCommand by CrudActor in query workloads"

---

src/lamplib/src/genny/toolchain.py
src/workloads/encrypted/ExponentialCompact.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1Cf16.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1Cf16Sharded.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1Cf32.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1Cf32Sharded.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1Cfdefault.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1CfdefaultSharded.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5Cf16.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5Cf16Sharded.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5Cf32.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5Cf32Sharded.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5Cfdefault.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5CfdefaultSharded.yml
src/workloads/encrypted/medical_workload-diagnosis-100-0-unencrypted.yml
src/workloads/encrypted/medical_workload-diagnosis-100-0.yml
src/workloads/encrypted/medical_workload-diagnosis-50-50-unencrypted.yml
src/workloads/encrypted/medical_workload-diagnosis-50-50.yml
src/workloads/encrypted/medical_workload-guid-50-50-unencrypted.yml
src/workloads/encrypted/medical_workload-guid-50-50.yml
src/workloads/encrypted/medical_workload-load-unencrypted.yml
src/workloads/encrypted/medical_workload-load.yml

test patch (using genny-toolchain with updated libmongocrypt): https://spruce.mongodb.com/version/64629292850e6173bd8bc3ca/tasks

PERF-3954 Re-enable QE performance tests

---

src/workloads/sharding/MultiShardTransactions.yml

**Jira Ticket:** PERF-4116
Add genny workloads to test latency and throughput of multi shard transactions
https://spruce.mongodb.com/version/645e4f2b850e6121c27d1d3e/tasks
https://spruce.mongodb.com/version/6461fbff9ccd4e2c6f1639e8/tasks

PERF-4116 Add genny workloads to test latency and throughput of multi shard transactions

---

docs/using.md

Rename this page from "Table of Content" to "Using Genny". Also add the go link for this page on top.

Rename using.md and add go link

---

src/workloads/query/QueryStats.yml

**Jira Ticket:** (https://jira.mongodb.org/browse/BF-28988)
fixing query stats parameters
https://spruce.mongodb.com/version/647f63f832f4176d68c25485/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

BF-28988: Fixing queryStats Parameters

---

src/workloads/query/CumulativeWindows.yml
src/workloads/query/SlidingWindows.yml
src/workloads/query/WindowWithComplexPartitionExpression.yml

**Jira Ticket:** PERF-4256
Add workloads for the remaining window expressions: $addToSet, $integral, $push, $first, $last, $shift, $documentNumber, $rank, $denseRank
[If applicable, link a patch test showing code changes running successfully](https://performance-monitoring-and-analysis.server-tig.prod.corp.mongodb.com/task/sys_perf_linux_standalone.2022_11_sliding_windows_patch_0b03b1ae353e85365589c8d4ad0c2d9433289d12_64877e35a4cf476a01f940bc_23_06_12_20_25_42/performanceData?time_series_filters=%5B%7B%22active%22%3Atrue%2C%22name%22%3A%22test%22%2C%22operator%22%3A%22contains%22%2C%22type%22%3A%22string%22%2C%22value …

PERF-4256: Add missing window expresssions

---

src/workloads/query/CumulativeWindows.yml

**Jira Ticket:** < Ticket Number >
High level explanation of changes
PLEASE READ AND REMOVE THE SECTION BELOW BEFORE SUBMITTING YOUR PR FOR REVIEW
1.  Once (1) you get approval from the STM or the Product Perf team for your change and (2) all your CI tests pass, you can initiate a merge …

PERF-4309: Separate recently added window function tests to new phase

---

docs/using.md
src/driver/src/DefaultDriver.cpp
src/gennylib/include/gennylib/context.hpp
src/gennylib/src/context.cpp

**Jira Ticket:** EVG-19853
Log which Actors run in each Phase, at debug log level, in Genny workload's dry-run mode.
For example, here's part of the log output for [TimeSeriesSort.yml](https://github.com/mongodb/genny/blob/f014c99eb7681e7b337b12e586469137e3a2343f/src/workloads/query/TimeSeriesSort.yml) (the full output can be found [here](https://privatebin.corp.mongodb.com/?0e99cb425102bff1#BDMZmq79DpUxhad8ZBZUezGCYjPkDAiMcLDWkDyKvT6J)):
```shell
> ./run-genny workload --dry-run -v debug src/workloads/query/TimeSeriesSort.yml 
...
[2023-07-04 15:50:37.341091] [0x00000001e8a9de00] [info]    Workload context constructed without errors.
[2023-07-04 15:50:37.342075] [0x00000001e8a9de00] [debug]   Phase 0 Actors:
[2023-07-04 15:50:37.342095] [0x00000001e8a9de00] [debug] …
```

EVG-19853: Log which Actors run in each Phase, at debug log level, in dry-run mode

---

docs/using.md

This fixes a typo in the using.md

Updated file name to print perf summary

---

src/workloads/query/ProjectParse.yml

Added a workload for $project parsing performance.
https://spruce.mongodb.com/version/64c2dcce3627e000ccaa3665/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
I've submitted this form.
https://github.com/10gen/mongo/pull/14542

SERVER-78580 projection parsing workload

---

src/phases/execution/TimeSeriesUpdatesAndDeletes.yml
src/workloads/execution/TimeSeriesArbitraryUpdate.yml
src/workloads/execution/TimeSeriesRangeDelete.yml

patch:
https://spruce.mongodb.com/version/64c8052d1e2d17e5f0aae318/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=time_series_arbitrary

PERF-3749 Add time-series arbitrary updates workload

---

src/workloads/sharding/MultiShardTransactions.yml
src/workloads/sharding/MultiShardTransactionsWithManyNamespaces.yml

**Jira Ticket:** PERF-4498
Add more thread levels to MultiShardTransactions workloads
https://spruce.mongodb.com/version/64ca81142fbabe83162d5b91/tasks

PERF-4498 Add more thread levels to MultiShardTransactions workloads

---

src/workloads/query/ProjectParse.yml

[patch](https://spruce.mongodb.com/version/64cd19c67742ae1aaa5cd6fa/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-4505 Exclude ProjectParse from Bonsai variants

---

src/canaries/src/main.cpp

**Jira Ticket:** PERF-4215
Genny Canary pings on serverless are slow, we need to periodically log to the console to ensure that evergreen doesn't kill the task.
[Patch](https://spruce.mongodb.com/version/64ccc87e9ccd4eb838ff358c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[DSI PR](https://github.com/10gen/dsi/pull/1373)

PERF-4215 fix genny canaries on sys-perf-atlas

---

docs/using.md

SERVER-79305 - add link to skip compile

---

src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml

**Jira Ticket:** EVG-17808
Added {^UUID} generator support.

EVG-17808 add {^UUID} generator

---

src/cast_core/src/DbCheckActor.cpp
src/phases/replication/startup/StartupPhasesTemplate.yml
src/workloads/replication/dbcheck/dbcheck_40GB.yml

**Jira Ticket:** < [SERVER-79695](https://jira.mongodb.org/browse/SERVER-79695), [PERF-4691](https://jira.mongodb.org/browse/PERF-4691) >
Add index consistency checks to perf canary workloads
[Link](https://spruce.mongodb.com/version/64ff42ebd1fe07cd9a85e2b2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
**Related PRs:**

PERF-4691 Add index consistency checks to perf canary workloads

---

src/workloads/query/ShardFilter.yml

**Jira Ticket:** SERVER-79756
Added new workload to target plans with a shard filter stage.
🌲 [patch](https://spruce.mongodb.com/version/651c6fe32a60eda358ef736e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
Done
n/a

SERVER-79756 Create workload targetted at plans which require a shard filter

---

src/workloads/replication/dbcheck/dbcheck_40GB.yml

Related to https://github.com/10gen/mongo/pull/17283
[EV](https://spruce.mongodb.com/version/65679bce850e61c2b9f93c73/tasks)

PERF-4941 Increase maxDbCheckMBperSec for dbcheck workload

---

src/workloads/query/TimeseriesBlockProcessing.yml

**Jira Ticket:** https://jira.mongodb.org/browse/PERF-4906?filter=-1
Adding new test for time series bucket level filters.
https://spruce.mongodb.com/version/656f6d8d9ccd4e411f60db14
N/A, this is just adding a new test to existing workload.
N/A

PERF-4906 Add TS test for conjunction of selective predicates

---

src/workloads/query/TimeseriesTsbsExpressionQuery.yml

**Jira Ticket:** [PERF-4970](https://jira.mongodb.org/browse/PERF-4970)
Adds workload that tests mathematical expression using the tsbs dataset
https://spruce.mongodb.com/version/65801971c9ec444ed7459df4/changes?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Form has been submitted.
[Mongo PR](https://github.com/10gen/mongo/pull/17602)

PERF-4970 Add TS test for math operations

---

src/workloads/execution/CreateBigIndex.yml
src/workloads/query/TimeseriesBlockProcessing.yml

This is a quick fix for [BF-31192](https://jira.mongodb.org/browse/BF-31192)

SERVER-84272 Prevent CreateBigIndex.yml from running in shard-lite environment

---

src/phases/query/CollScanSimplifiablePredicate.yml

[sys-perf patch](https://spruce.mongodb.com/version/65833dd8d1fe077855558f06/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

SERVER-83900 Add type bracketing query benchmarks

---

src/workloads/streams/AddFields.yml
src/workloads/streams/LargeHoppingWindow.yml
src/workloads/streams/LargeTumblingWindow.yml
src/workloads/streams/LargeWindowMixed.yml
src/workloads/streams/LargeWindowUniqueAndExistingKeys.yml
src/workloads/streams/StreamsLookup.yml
src/workloads/streams/TopKPerWindow.yml

**Jira Ticket:**SERVER-82989
We changed allowedLateness field for streams.  Before it used to be specified for $source operator.  Now it is only applicable at $window.
https://spruce.mongodb.com/version/65948e7461837d7b7e59b029/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
n/a
PLEASE READ AND REMOVE THE SECTION BELOW BEFORE SUBMITTING YOUR PR FOR REVIEW
1. …

SERVER-82989 genny test fixes for allowed lateness changes.

---

src/workloads/query/TimeseriesEnum.yml

**Jira Ticket:** [PERF-5024](https://jira.mongodb.org/browse/PERF-5024)
Added more values in $nIn queries to make filter more selective.
[7.0](https://spruce.mongodb.com/version/659fd906c9ec44ed083048f1/tasks)
[7.1](https://spruce.mongodb.com/version/65a0281e850e614a52bd9ed6/tasks)
[7.2](https://spruce.mongodb.com/version/65a02c2f32f4174972d4f492/tasks)
[master](https://spruce.mongodb.com/version/65a028773066159a235d7da8/tasks)

PERF-5024 : Increase selectivity

---

src/phases/query/CollScanOnMixedDataTypes.yml
src/workloads/query/CollScanOnMixedDataTypesLarge.yml
src/workloads/query/CollScanOnMixedDataTypesMedium.yml
src/workloads/query/CollScanOnMixedDataTypesSmall.yml

**Jira Ticket:** SERVER-84675
A new genny workload that runs CollScan queries
**Patch Results:**
https://spruce.mongodb.com/version/65af7fd7c9ec441cbae823b3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

SERVER-84675 Add workloads running CollScan queries on various types

---

src/phases/query/CollScanLargeNumberOfFields.yml
src/workloads/query/CollScanLargeNumberOfFieldsLarge.yml
src/workloads/query/CollScanLargeNumberOfFieldsMedium.yml
src/workloads/query/CollScanLargeNumberOfFieldsSmall.yml

**Jira Ticket:** SERVER-84676
Add queries over collections with a large number of fields
[Patch](https://spruce.mongodb.com/version/65a97a9b9ccd4e79469f8a98/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

SERVER-84676 Add queries over collections with a large number of fields

---

src/workloads/scale/LoadTest.yml

**Jira Ticket:** PERF-4416
Set MaxPhases correctly.

PERF-4416 set MaxPhases correctly

---

src/phases/query/FilterWithComplexLogicalExpression.yml

🌲 [patch](https://spruce.mongodb.com/version/65b814a80ae6066bbf8da957/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-5080 Fix whitespace in predicate in FilterWithComplexLogicalExpression

---

src/workloads/query/multiplanner/NoSuchField.yml

Only change here compared to `Simple.yml` is on L222, adding `{no_such_field: "none"}` to `query`.

PERF-5115 Create multi-planner performance workload where we hit 'getTrialPeriodMaxWorks'

---

src/workloads/query/ArrayTraversal.yml
src/workloads/query/ExpressiveQueries.yml
src/workloads/scale/LargeIndexedIns.yml
src/workloads/scale/LoadTest.yml

**Jira Ticket:** PERF-5289
Self-explanatory
None
None
None

PERF-5289 Ensure all high-value workloads run on all-feature-flags variants

---

src/workloads/query/multiplanner/BlockingSort.yml
src/workloads/query/multiplanner/ClusteredCollection.yml
src/workloads/query/multiplanner/NoGoodPlan.yml
src/workloads/query/multiplanner/NonBlockingVsBlocking.yml

**Jira Ticket:** PERF-5305
Fix duplicate _id
https://spruce.mongodb.com/version/66030d35a9f52900071631cc/tasks

PERF-5305 Remove needless _id and fix repeat count

---

src/workloads/query/multiplanner/Subplanning.yml

**Jira Ticket:** PERF-5293
Add subplanning workload
https://spruce.mongodb.com/version/660452f15813710007edf328/tasks

PERF-5293 Add subplanning workload

---

.github/CODEOWNERS
.github/pull_request_template.md

**Jira Ticket:** [DEVPROD-2192](https://jira.mongodb.org/browse/DEVPROD-2192)
- Added a newer version of the CODEOWNERS file that hopefully maps to teams that exist.
- Updated the PR template
Figured terraform was the best way of displaying this, ignore the "will be imported"/"updated" stuff, I am not proposing any settings changes in this PR.
```
resource "github_branch" "main" {
branch        = "master"
etag          = "W/\"aab1abea53fedd5213d8473da2809741ad30ef8a07bc97378b8ac44e489693dc\""
id            = "genny:master"
ref           = "refs/heads/master"
repository    = "genny"
sha           = "b6360b717ee7da1c2d8f76d032011ba2b8a7f33d"
source_branch = "main"
}
resource "github_branch_default" "this" {
branch     = "master"
etag       = …
```

DEVPROD-2192 Add initial CODEOWNERS file, update PR template

---

.github/CODEOWNERS

**Jira Ticket:** [DEVPROD-2192](https://jira.mongodb.org/browse/DEVPROD-2192)

DEVPROD-2192 Add dry-run to @mongodb/performance in CODEOWNERS

---

docs/TPCH.md
docs/streams.md

A follow up PR to https://github.com/mongodb/genny/pull/1197
Here we add an additional subsection for the column store tests.

DEVPROD-6718 - Add Column Store documentation 

---

docs/generated/workloads.md
src/workloads/query/ArrayTraversal.yml

**Jira Ticket:** [SERVER-89309](https://jira.mongodb.org/browse/SERVER-89309)
Remove 5 phases that contain queries determined to be uncommon in practice.

SERVER-89309 Remove AggregationExpression* phases from ArrayTraversal.yml

---

src/cast_core/include/cast_core/actors/StreamStatsReporter.hpp
src/cast_core/src/StreamStatsReporter.cpp
src/cast_core/test/StreamStatsReporter_test.cpp
src/workloads/docs/StreamStatsReporter.yml
src/workloads/streams/AddFields.yml
src/workloads/streams/LargeHoppingWindow.yml
src/workloads/streams/LargeTumblingWindow.yml
src/workloads/streams/LargeWindowMixed.yml
src/workloads/streams/LargeWindowUniqueAndExistingKeys.yml
src/workloads/streams/Passthrough.yml
src/workloads/streams/Passthrough_ChangeStreamSource.yml
src/workloads/streams/Passthrough_MongoSink.yml
src/workloads/streams/Search.yml
src/workloads/streams/StreamsLookup.yml
src/workloads/streams/TopKPerWindow.yml

**Jira Ticket:** [BF-32909](https://jira.mongodb.org/browse/BF-32909)
Provide tenantId, processorId and options.featureFlags to SP commands.

BF-32909: Provide tenantId and processorId to SP commands.

---

src/workloads/query/PercentilesAgg.yml

**Jira Ticket:** PERF-5427
I'm removing unused stuff from this workload. It currently has 30 phases but only need 7. The rest are empty. It also has templates for things it doesn't use. Also the test only lasts 5 seconds currently so I'm increasing the runtime to reduce noise.
[updated patch](https://spruce.mongodb.com/version/6633ca6c4ac0e2000709244f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-5427 cleanup

---

src/workloads/tpch/denormalized/10/Q15.yml
src/workloads/tpch/normalized/10/Q15.yml

**Jira Ticket:** [PERF-5566](https://jira.mongodb.org/browse/PERF-5566)
Before this change, the views that the queries are supposed to run against weren't being created so the queries returned immediately without doing any actual work.
[sys-perf patch](https://spruce.mongodb.com/version/66678bd32e682f0007eefe09/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-5566 Fix TPCH Q15 scale 10 phases

---

src/workloads/query/ArrayTraversal.yml
src/workloads/query/FilterWithComplexLogicalExpression.yml
src/workloads/query/FilterWithComplexLogicalExpressionMedium.yml
src/workloads/query/FilterWithComplexLogicalExpressionSmall.yml

Remove standalone variants for filter_with_complex_logical_expression and array_traversal tests.

PERF-4866: remove standalone variants for filter_with_complex_logical_expression and array_traversal

---

src/workloads/query/ProjectParse.yml

**Jira Ticket:** [PERF-5712](https://jira.mongodb.org/browse/PERF-5712)
Add a new test case to the `ProjectParse` test suite for `$project`s with `$filters` containing large predicates.
[Patch](https://spruce.mongodb.com/version/66a29eda1b15c70007fe8965).

PERF-5712: Implement a performance test for long constant array in $filter of $project

---

docs/generated/workloads.md
src/workloads/query/NonSearchHybridScoring.yml

Extending the workload to add a score fusion based pipeline.
https://spruce.mongodb.com/version/66ce3b4b6d5bcd0007f61029/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-5545 Add scoreFusion workload

---

evergreen/system_perf/master/genny_tasks.yml
src/lamplib/src/genny/tasks/auto_tasks_all.py
src/lamplib/src/genny/tasks/auto_tasks_local.py

**Jira Ticket:** [DEVPROD-10486](https://jira.mongodb.org/browse/DEVPROD-10486)
This PR removes the requirement for the schedule_variant_auto_tasks when running local taskgen.

 DEVPROD-10486 Remove requirement for auto-tasks

---

evergreen/system_perf/README.md

These will be used when creating a new branch on the mongo repo.

DEVPROD-11772: Add branching instructions to sys-perf README.

---

.github/dependabot.yml

**Jira Ticket:** [DEVPROD-15706](https://jira.mongodb.org/browse/DEVPROD-15706)
Disabling Dependabot YML

DEVPROD-15706 Include a dependabot.yml file that should disable all updates

---

README.md

Repoint deprecation notice link.

DEVPROD-17216: Fix Genny readme.
