src/gennylib/include/gennylib/ConfigNode.hpp
src/gennylib/include/gennylib/context.hpp
src/gennylib/src/context.cpp
src/gennylib/test/context_test.cpp

Moves the logic in `PhaseContext` to inherit the configuration from `ActorContext` to a generic `ConfigNode` class.
----
I had taken a stab at [TIG-1187](https://jira.mongodb.org/browse/TIG-1187) and found myself defining an `OperationContext` class that mimicked the behavior of `PhaseContext::get()` to allow the user to save on some repetitive typing. My suspicion is that @jasonjhchan may want a similar construct as part of [TIG-1186](https://jira.mongodb.org/browse/TIG-1186) (e.g. for applying a write concern to all commands being executed).
**Note**: There isn't any urgency around doing a formal code review for these changes because I'll be out until December 18th. Although, if it seems like it'd be a useful point for Jason's changes to work off of, then someone can feel free to take …

TIG-1203: Make {Workload,Actor,Phase}Context types hierarchical

---

evergreen.yml

It seems that s3Copy wasn't setting permissions correctly for what it uploaded. I've switched to fetch/put and it seems much easier to reason about.

TIG-1366 Make genny tarballs publicly readable

---

src/cast_core/src/actors/MultiCollectionQuery.cpp
src/driver/test/AuthNInsert.yml
src/driver/test/BigUpdate.yml
src/driver/test/CollScan.yml
src/driver/test/InsertWithNop.yml
src/driver/test/RunCommand.yml
src/driver/test/Workload.yml
src/gennylib/src/value_generators/generators-private.cpp
src/gennylib/src/value_generators/generators-private.hh
src/gennylib/src/value_generators/parser.cpp
src/gennylib/src/value_generators/parser.hh
src/gennylib/test/RunCommandActor_test.cpp
src/gennylib/test/document_test.cpp

Also changes to use a `std::unordered_set<std::string_view>` instead of a `std::set<std::string>` to eliminate some (but far from all) string copies happening when parsing the templates.
----
@rtimmons, the design document calls for using the `'@'` character as the prefix for the typename of all value generators; however, [the `'@'` character is reserved in the YAML 1.2 specification](https://yaml.org/spec/1.2/spec.html#c-reserved) and therefore cannot be used unquoted. I think it'd be an inconvenience for genny users to need to remember to quote the typenames for the value generators that I'd rather pick a different character. I recall the motivation to use a different character than `'$'` as being due to how `'$'`-prefixed keys are special from a MongoDB perspective and wanting to avoid …

TIG-1363: Use '^' and Pascal case for names of value generator types

---

src/cast_core/src/actors/RunCommand.cpp
src/gennylib/include/gennylib/v1/ConfigNode.hpp
src/gennylib/test/context_test.cpp

We have a few occasions where we want to support both a singular and a plural syntax. Notably `Operation` and `Operations` but probably others too. This adds `context.getPlural` to simplify the calling code.

Add context.getPlural

---

src/driver/test/SecondaryAllowed.yml
src/driver/test/service-architecture/SecondaryAllowed.yml

Currently the workload only runs a stepdown command to trigger an election.

SERVER-36673: Add Secondary Allowed workload

---

src/gennylib/src/Cast.cpp
src/gennylib/src/context.cpp
src/gennylib/test/context_test.cpp

Added a test to check that producing an actor with a mistyped 'Type' will result in an InvalidConfigurationException.

TIG-1205 Error if No Actors Produced for an Actor YAML Block

---

src/cast_core/test/CrudActor_test.cpp
src/cast_core/test/RunCommandActor_test.cpp
src/testlib/include/testlib/MongoTestFixture.hpp
src/testlib/src/MongoTestFixture.cpp

Besides the title I also added the ApmEvent class to MongoTestFixture and updated other tests that used it.

TIG-1384 'InsertActor respects writeConcern' fails if not run on a replset

---

README.md
src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActor_test.cpp
src/gennylib/include/gennylib/PhaseLoop.hpp

Decided in pointing to defer TIG-1223 and instead just warn for now.
This is our first real use for `NDEBUG`. I don't know if the server does something fancier that we may want to adopt?
Also changed to use vanilla `unique_ptr<T>` rather than `optional<unique_ptr<T>>`.

TIG-1223: Warn if accessing phaseConfig-> on nop phases

---

src/cast_core/include/cast_core/actors/Loader.hpp
src/cast_core/include/cast_core/actors/MultiCollectionQuery.hpp
src/cast_core/include/cast_core/actors/MultiCollectionUpdate.hpp
src/cast_core/src/HelloWorld.cpp
src/cast_core/src/Insert.cpp
src/cast_core/src/InsertRemove.cpp
src/cast_core/src/Loader.cpp
src/cast_core/src/MultiCollectionQuery.cpp
src/cast_core/src/MultiCollectionUpdate.cpp
src/cast_core/src/RunCommand.cpp
src/driver/src/DefaultDriver.cpp
src/gennylib/benchmark/orchestrator_benchmark.cpp
src/gennylib/include/gennylib/Orchestrator.hpp
src/gennylib/src/Orchestrator.cpp
src/gennylib/test/Cast_test.cpp
src/gennylib/test/PhaseLoop_test.cpp
src/gennylib/test/context_test.cpp
src/gennylib/test/orchestrator_test.cpp
src/metrics/include/metrics/metrics.hpp
src/testlib/src/ActorHelper.cpp

Please check that I correctly deprecated the previous metrics types. 
Some existing genny classes are still using metrics::registry and metrics::guage (such as orchestrator.hpp). Not sure if we'll want to do that at some point or not. But all of the actors in cast_core are now using metrics::operation.

TIG-1328 Migrate all Actors from previous metrics types to metrics::Operation

---

cmake/ParseAndAddCatchTests.cmake

I had noticed for my patch build that [the "Test Results" pane only showed the sentinel report on Amazon Linux 2](https://evergreen.mongodb.com/task/genny_amazon2_t_cmake_test_patch_504a7e0528d2c2422b5485462f7354b10f73fd8c_5c6c3c1f3627e0236e5c0911_19_02_19_17_25_52) despite the `metrics_test:example metrics usage` test having failed. [The "Test Results" pane is empty when all of the tests are passing](https://evergreen.mongodb.com/task/genny_amazon2_t_cmake_test_504a7e0528d2c2422b5485462f7354b10f73fd8c_19_02_19_17_17_01). The task logs mentioned
```
[2019/02/19 17:25:56.882] Running command 'attach.xunit_results' in "f_report_test_results" (step 1.1 of 2)
[2019/02/19 17:25:56.882] Command failed: error parsing xunit file: EOF
```
which suggested to me that something was malformed about …

TIG-1404: Force --reporter=junit in ParseAndAddCatchTests()

---

README.md

I forgot how to run a specific testcase, and somehow missed it when reading the readme (my mind only registered the cmake way of running the test), so I wanted to emphasize that you can run the binary itself with the catch2 parameters. I think it would be more clear if both testing options were in the same section.

Moved around some of the descriptions for testing

---

src/gennylib/include/gennylib/conventions.hpp
src/gennylib/src/context.cpp
src/gennylib/test/context_test.cpp
src/gennylib/test/conventions_test.cpp

Added `PhaseRangeSpec` to handle the `..` syntax. `PhaseRangeSpec` handles both `IntegerSpec..IntegerSpec` and `IntegerSpec` formats. The `..` syntax is inclusive and resembles Ruby's `..`. 
Note that the `decode` method for `PhaseRangeSpec` was  implemented to throw if a user inputted invalid syntax, but the correct behavior should be to return false instead and let the caller decide whether to throw or have other behavior. I've kept the current behavior to be consistent with how the other specs have been implemented, and opened up [TIG-1507](https://jira.mongodb.org/browse/TIG-1507) to fix them all at once.

TIG-1202 Support Phase Range Syntax

---

src/testlib/include/testlib/yamlToBson.hpp
src/testlib/src/yamlToBson.cpp
src/testlib/test/yamlToBson_test.cpp

Tests want to write bson but it's painful with the builders. This cribs Max's work on `Value` to build a simple utility to convert yaml to bson.
There's already `bsoncxx::from_json` so tests could write bson in the form of json and some should probably do just that, but I've got an idea to put a whole suite of tests for overhauled value-generators into a yaml file and I want to be able to write the `expected` case as yaml not a stringified json or something....

TIG-1209: Add Simple YAML to BSON Conversion in testlib

---

.genny-root
CMakeLists.txt
src/testlib/CMakeLists.txt
src/testlib/include/testlib/findRepoRoot.hpp
src/testlib/src/findRepoRoot.cpp

I'm writing a test that wants to load up a yaml file but the cwd of the test binary isn't really well-defined. This lets us look for a special ".genny-root" file by checking `.` then `./..` and then `./../..` etc.
I considered looking for `.git` but that seems a bit cheeky and I think could break if we ever add submodules or something.

TIG-1209: Add findRepoRoot to assist with loading test fixtures

---

src/cast_core/src/InsertRemove.cpp
src/workloads/scale/InsertRemove.yml

Need to open a ticket, but here's the change. I changed the log message to debug while here. 
Sys-perf patch here: https://evergreen.mongodb.com/version/5c9241775623433487e7d6bd
I assume it will break history. That's fine.

PERF-1816: Increase run time for Insert remove test

---

src/python/genny/cedar_report.py
src/python/tests/cedar_report_test.py

It isn't defined in mainline builds and therefore won't be serialized out by the expansions.write command.
Also addresses an unrelated warning from PyYAML about using `load()` and unsafe code execution.

TIG-1548: Fix handling of ${is_patch} expansion

---

src/python/genny/cedar.py
src/python/genny/cedar_report.py
src/python/genny/csv2.py
src/python/tests/fixtures/cedar/barebones.csv
src/python/tests/fixtures/cedar/error_outcome.csv
src/python/tests/fixtures/cedar/two_op.csv
src/python/third_party/csvsort.py

I threw in some changes to improve the perf. We should see roughly double the throughput of the first half of csv parsing. (double `tottime` of `method 'writerow' of '_csv.writer' objects`).
I haven't benchmarked csvsort yet but I'm less confident about making large improvements there. If this PR doesn't visibly improve the overall performance of metrics parsing, we may have to do something else entirely for the longer term.
```
// python -m cProfile -s tottime -m genny.cedar_report
// BEFORE
17957893 function calls (17954266 primitive calls) in 11.364 seconds
Ordered by: internal time
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
637040    5.467    0.000    7.051    0.000 csv2.py:85(_parse_into_intermediate_csv)
637040    2.391    0.000    2.391    0.000 {method …
```

TIG-1563 Improve metrics parsing performance and log csv parsing progress

---

src/workloads/networking/CommitLatency.yml
src/workloads/networking/CommitLatencySingleUpdate.yml

Genny reports metrics per Actor (multiple phases aggregate together), so each configuration needs to be its own actor instance.

PERF-1748 Separate CommitLatency configurations into individual actors

---

src/testlib/include/testlib/helpers.hpp
src/testlib/include/testlib/yamlTest.hpp
src/testlib/include/testlib/yamltest.hpp
src/value_generators/test/DocGenYamlTestCaseRunner.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml

I want to re-use some of the yaml-based-testing code for CrudActor testing. Refactoring to testlib makes the most sense. I'm holding off on adding too much documentation or self-testing to this for now since I anticipate needing to make a few tweaks once the code is used in more than just one place. I'll add that once CrudActor testing is using it as well.
There's almost no new code here just adding `template<...>` in a few places.

TIG-1397: Move some YAML-Based Testing Infrastructure to testlib

---

src/CMakeLists.txt
src/canaries/CMakeLists.txt
src/canaries/include/canaries/Loops.hpp
src/canaries/src/Loops.cpp
src/canaries/src/main.cpp

Most of what's described in TIG-1098 is covered. `db.ping()` is missing, but I'm planning to do it as part of TIG-1337 now that the ticket has been reopened. I'll probably also file a ticket to integrate the canaries with DSI. 
Right now the output is in a human readable format:
```bash
➜  genny git:(tig1098) ./dist/bin/genny-canaries "simple-loop" "phase-loop" "metrics-loop" "real-loop" -p false
simple-loop:	2143012ns
phase-loop:	50859249ns
metrics-loop:	192317833ns
real-loop:	219668218ns
➜  genny git:(tig1098) ./dist/bin/genny-canaries "simple-loop" "phase-loop" "metrics-loop" "real-loop" -p false
simple-loop:	2108709ns
phase-loop:	51095903ns
metrics-loop:	194208899ns
real-loop:	220928299ns
➜  genny git:(tig1098) ./dist/bin/genny-canaries "simple-loop" "phase-loop" "metrics-loop" …
```

TIG-1098 Add standalone benchmark binary to measure genny perf impact

---

src/canaries/src/main.cpp
src/python/third_party/csvsort.py

I [left a comment on the ticket](https://jira.mongodb.org/browse/TIG-1566) with a patch build showing a roughly 40% perf improvement from sorting 10GB of csv in memory at once. Is that sufficient or do we want to pursue more aggressive optimizations?

TIG-1566 improve metrics parsing perf

---

src/lamplib/__main__.py

I tested this manually by changing 14 to 15 and verifying that `./scripts/lamp` fails locally with the expected error message.

TIG-1683 enforce min macOS version of 10.14

---

src/python/genny/cedar_report.py
src/python/tests/cedar_report_test.py

This lets you skip cedar reporting when running DSI locally.

TIG-1720 Option to Skip Cedar Reporting

---

.gitignore
src/lamplib/tasks/toolchain.py

This was a head-scratcher. It seems Python's `TarFile.extractall` wasn't working and was only extracting a portion of the toolchain!

TIG-1744 fix genny compile on macOS

---

src/python/setup.py
src/workloads/scale/InsertBigDocs.yml

This adds a new workload that inserts big documents.

Insert big docs

---

scripts/create-new-actor.sh

It's currently passed in as const mongocxx::database& but at the call-site it's a value. Treating it as a const allows the PhaseConfig to implicitly copy it as a ref and it prohibits the PhaseConfig from calling non-const methods.

TIG-1779 Let mongocxx::database be a value in the generated PhaseConfig

---

src/HitchhikersGuide.md
src/cast_core/test/RunCommandActor_test.cpp
src/gennylib/include/gennylib/PhaseLoop.hpp
src/gennylib/include/gennylib/context.hpp
src/gennylib/include/gennylib/v1/GlobalRateLimiter.hpp
src/gennylib/test/GlobalRateLimiter_test.cpp
src/gennylib/test/PhaseLoop_test.cpp
src/workloads/docs/HelloWorld-MultiplePhases.yml
src/workloads/docs/InsertWithNop.yml
src/workloads/docs/RunCommand.yml
src/workloads/networking/PrimaryRequiredReads.yml
src/workloads/networking/SecondaryAllowed.yml

It's too easy for workload YAML to not specify a `Repeat` or `Duration` value for a Phase and unintentionally make that Phase a "background" phase. This can create hard-to-debug scenarios if no Actor specifies a Repeat/Duration for a given Phase (which is always a mis-configuration).
Require an extra configuration for Phases without Repeat or Duration that makes it obvious the yaml author intended for the Actor to operate in the background for the given Phase.
Fortunately (or unfortunately depending on how much victim you wanna play) this caught a few workloads already in production....
cc @dalyd this woulda saved both of us a couple hours the other day 😸

TIG-1834 Don't allow accidental empty phases

---

src/lamplib/context.py

No actual changes in the toolchain just built against latest AMIs.
I suspect this will fail cuz we also need to update the DSI base images but we'll see.
Patch-build: https://evergreen.mongodb.com/version/5d4880db1e2d17127ed13587

Use latest genny toolchain

---

src/cast_core/include/cast_core/actors/CollectionScanner.hpp
src/cast_core/include/cast_core/actors/RandomSampler.hpp
src/cast_core/src/CollectionScanner.cpp
src/cast_core/src/RandomSampler.cpp
src/gennylib/include/gennylib/PhaseLoop.hpp
src/gennylib/include/gennylib/v1/GlobalRateLimiter.hpp
src/gennylib/test/GlobalRateLimiter_test.cpp
src/workloads/scale/OutOfCacheScanner.yml

The shared-state counter was being incremented for each PhaseConfig constructor call not for each Actor ctor call. I think this fix also resolves the weird `.2` suffix thing.

Fix use of shared state in CollectionScanner and RandomSampler

---

src/value_generators/include/value_generators/DocumentGenerator.hpp
src/value_generators/src/DocumentGenerator.cpp

Quick syntax thing that will let the user write
```c++
std::optional<DocumentGenerator> maybeDoc = ...;
maybeDoc->evaluate();
```
instead of the rather ugly form:
```c++
std::optional<DocumentGenerator> maybeDoc = ...;
(*maybeDoc)();
```

Add DocumentGenerator::evaluate()

---

src/cast_core/src/CollectionScanner.cpp
src/gennylib/include/gennylib/PhaseLoop.hpp

Fast follow from #273 - the `&*` syntax is a bit icky but it's "correct" 😄

Don't reference PhaseConfig through v1::ActorPhase

---

src/cast_core/src/CollectionScanner.cpp
src/workloads/scale/OutOfCacheScanner.yml

I've had a look at the perf.jsons in the relevant patch builds and they're looking good. As such I think this PR is good to merge pretty much straight away. 
The original workload was not performing as expected in prod causing it to have extremely varied throughputs.
This also fixes a bug where a sleep was in an incorrect location causing the out of cache scanner threads to act out of order.

TIG-1940 tune workload

---

src/python/genny/parsers/cedar.py
src/python/tests/cedar_test.py

The metrics parsing code assumes each thread runs one op at a time. This is not always the case as we collect "nested" metrics. E.g. metrics for a single op in a bulk op, as well as the total for the entire bulk op.
There's a side effect of this change: since we don't know which metrics are nested, every time genny encounters a new metric, it needs to assume the duration equals the total, instead of using the latest timestamp on that thread from some previous operation
Will run a sys-perf patch once PR is approved.

TIG-1964 support collecting overlapping metrics

---

src/workloads/execution/ValidateCmd.yml

Tested this locally with Genny on a 4.0 binary as Evergreen is in a bit of a weird situation with Genny for 4.0.

Modify ValidateCmd workload to work on MongoDB 4.0

---

src/workloads/docs/ParallelInsert.yml

This write workload pattern is taken from [SERVER-40250](https://jira.mongodb.org/browse/SERVER-40250). The thread levels are chosen based on the point of saturation seen in this [experiment](https://docs.google.com/document/d/1Rvsi0nnH2Mn4UkV_rYAn1R5X6Rz3H9LrttKi6vo4wWw/edit#heading=h.5iu1y848bbb).

PERF-1918 Add ParallelInsert workload

---

src/driver/include/driver/v1/DefaultDriver.hpp
src/driver/src/DefaultDriver.cpp
src/driver/src/main.cpp
src/gennylib/src/Orchestrator.cpp
src/metrics/include/metrics/MetricsReporter.hpp
src/metrics/test/metrics_test.cpp
src/testlib/src/ActorHelper.cpp

Spent a fair amount of time debugging a thing with @luke-pearson that could have been avoided if genny were more verbose with its logging at key lifecycle points.
- add begin/end logging around MetricsReporter::report
- do the same periodic output-logging when reporting `--metrics-format=csv` as in `--metrics-format=cedar-csv`
- add begin/end logging for each Phase
- make log level configurable by passing in the `-v $level` flag

Add logging and make log-level configurable by command-line opts

---

src/gennylib/src/Orchestrator.cpp

Was logging
```
T0: Starting phase 0.
T1: Ending phase 1.
T2: Starting phase 1.
```
Now logs
```
T0: Starting phase 0.
T1: Ending phase 0.
T2: Starting phase 1.
```

TIG-2084 Fix 'Ended phase' log message off-by-one

---

src/python/README.md
src/python/genny/genny_auto_tasks.py
src/python/tests/auto_tasks_test.py

- Add --workloads as an option in the ArgumentParser
- Branch logic in main to use --workloads specified if present, else use the result of `modified_workload_files`
- Add function `validate_user_workloads` to validate the user input
- Add a test for the above
- Update the README with info on `genny_auto_tasks`

TIG 2096: Add --workloads option to genny_auto_tasks

---

build/.gitignore
src/cast_core/include/cast_core/actors/CollectionScanner.hpp
src/cast_core/src/CollectionScanner.cpp
src/cast_core/src/RollingCollections.cpp
src/cast_core/test/CollectionScanner_test.cpp
src/workloads/docs/CollectionScanner.yml

New options: CollectionSkip (skip a number of collections when scanning), CollectionSortOrder (sort the collection names forward or backward before scanning), ScanDuration (hold a snapshot scan transaction open until a duration has elapsed).
Modified option: Allow Database to be a single database name or a comma separated list of databases to scan.
Rolling Collections now are named in a manner that gives a time based ordering when sorted by name. This is needed by the large scale workload so collections can be traversed "ahead" of when they are expiring.

TIG-2064: Add capabilities for collection scanner and rolling collections.

---

build/.gitignore
src/cast_core/src/RollingCollections.cpp
src/workloads/docs/RollingCollections.yml

Details:
Have the tailer's run function use an "await" cursor, so that the cursor
waits for the next entry, rather than poll. This generally gives tighter
results for lag time.  Needed to change how we "catch up" at the start
of the run.
Track lag times per each minute and report best/worst/average over the minute.
Catch any exceptions and report them.
Some refactoring into functions and a helper struct.
Modified test case to run a bit longer to show the minute reporting.

TIG-2106 Oplog tailer actor improvements for large scale workload automation

---

src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActorYamlTestRunner.cpp
src/cast_core/test/CrudActorYamlTests.yml

1. We were previously recording all data on one `metrics::Operation` per `Operation` name, so e.g. all `bulkWrite` operations would be recorded together even if they were on different phases or had very different semantics.
After this Actor was written we introduced the `MetricsName:` concept in a `Phase` block, but we never brought it in.
2. Fixed a bug where we could not specify insert-options and added a test
3. Also did some drive-by 💅.

Make CrudActor respect MetricsName in Phase: YAML Blocks

---

src/python/genny/genny_auto_tasks.py
src/python/tests/auto_tasks_test.py

As requested by @rtimmons, workloads can now pass parameters to `system_perf.yml`'s `prepare environment` function as follows:
```
AutoRun:
Requires:
bootstrap: { infrastructure_provisioning: [replica] }
PrepareEnvironmentWith:
setup: replica-delay
```
This also necessitated a little refactoring of the AutoRun yaml validation code.
(Since the commit queue hasn't merged my last PR yet there are also a few lines of code from that PR, but I re-included them to avoid a merge conflict later on).

TIG 2077 Allow workload yaml to pass parameters to "prepare environment" function

---

src/python/genny/genny_auto_tasks.py

As I discussed with @guoyr offline, this change would make it **not** an error if there are no tasks that should be autorun. 
There are some buildvariants on Evergreen that do not have any associated genny workloads. We could get rid of `genny_auto_tasks` for these variants, but then, if someone added a new genny workload that should run on one of these variants, they would have to edit `system_perf.yml` which defeats the purpose of this ticket.
This PR also fixes an unexpected issue that would occur if `bootstrap.yml` or `runtime.yml` is empty.

TIG-2077 Don't throw exception if no autorun tasks are generated, fix small bug

---

src/python/genny/genny_auto_tasks.py

Small fix to increase the usability of genny_patch_tasks: currently we always raise an exception if there are no locally modified tasks. This PR would stop throwing an exception if the user also supplies workloads to run via the `--forced-workloads` flag. This way, genny_patch_tasks can be used to just run a one-off task via `--forced-workloads`, even if there are no locally modified tasks.

Don't raise exception for no modified workloads if there are --forced-workloads

---

src/python/genny/genny_auto_tasks.py
src/python/genny/parsers/cedar.py
src/python/tests/auto_tasks_test.py

(and don't capture WT diagnostic.data/FTDC as a result)
1. Allow Genny Workloads to run for 18 hours
2. Another minor bug-fix in genny metrics-parsing.
Patch-build [here](https://evergreen.mongodb.com/version/5de81e7e850e612617719bf5).
The task is still red because we ran out of disk-space when processing metrics, but importantly the WT diagnostic data is in the artifact tarball

TIG-2094 Fix: Genny Workloads Timeout After 6 Hours

---

src/workloads/docs/ParallelInsert.yml

This is for the project "Use Exhaust Cusor for Oplog Fetching".

PERF-1933: Run parallel_insert workload with slow network

---

src/phases/execution/CreateIndexPhase.yml
src/workloads/execution/CreateIndex.yml
src/workloads/execution/CreateIndexSharded.yml

Added a workload similar to CreateIndex.yml for running against a sharded collection. The only difference is that I got rid of `mongodb_setup: single-replica` and used `Duration` instead of `Repeat` to make it run more operations.

PERF-1948 Add performance workload for creating an index on a sharded collection

---

src/workloads/execution/ExternalSort.yml

This workload has three benchmark phases, which each run a sort operation. For initial testing, I chose to run 20 trials of each operation.
Looking at one execution of the test, I only need to look at the elapsed time of the first 7 trials for the half width of the 95% confidence interval to be less than 1% of the sample mean. I think that would make 7 a reasonable choice for the number of trials for each operation. We could also round up to 10. Each trial takes about 2.2s, so we don't have to worry about setting this too high.

PERF-1897 Sys-perf tests for external sort

---

src/workloads/docs/ParallelInsert.yml

The current autorun section of this workload generates a task that tries to have the following in bootstrap.yml:
```yaml
infrastructure_provisioning: single
mongodb_setup: replica
```
This [fails](https://evergreen.mongodb.com/task/sys_perf_linux_1_node_replSet_parallel_insert_replica_8ea803b42abc5b9b653fe7931e90f00f0e8c8043_19_12_18_21_48_52/1) because `mongodb_setup.replica.yml` assumes an `infrastructure_provisioning` of at least 3 nodes.
I suspect this was introduced by TIG-2077 and we accidentally added this line.
This is theoretically possible to catch prior to committing, so I added to GI-075 the [Genny Ideas Doc](https://docs.google.com/document/d/1K0SlHoKkIACIXhkNP_KPHvb3IV6r53ReqsHqEYTnXDA/edit#) to consider adding code to prevent something like this from happening in the …

BF-15755 Remove single-replica from ParallelInsert.yml

---

src/gennylib/include/gennylib/context.hpp
src/metrics/include/metrics/metrics.hpp
src/metrics/include/metrics/operation.hpp
src/metrics/test/metrics_test.cpp

Right now the actor counts and phase numbers aren't used for anything, but they'll be passed to poplar to used. I'm thinking the OperationImpl makes sense as the location where the two forms of metrics co-reside, because I think we can mostly create a new version of EventSeries to hold it.
Lotsa feedback welcome 😄

TIG-2260 Make metrics::Registry Aware of Actor-counts and Phase-Numbers

---

src/workloads/docs/RunCommand-Simple.yml

Adding simplified RunCommand workload to run it as integration test in DSI CI.
This is the copy of [RunCommand](https://github.com/mongodb/genny/blob/5813b65a7caef9101f3502012e78c97ee817ba3f/src/workloads/docs/RunCommand.yml) workload leaving just _ServerStatusInsertFind_ actor with 100 repeats instead of 5 min duration.

TIG-2434 Add simplified RunCommand workload

---

src/metrics/include/metrics/v2/event.hpp
src/metrics/test/metrics_test.cpp

This just make sure that, if the _last_finished var is after the finish (i.e. if the EventStream was constructed and _last_finish was initialized to now after the finish time was recorded), we just use the duration as the total this time around, next recorded operation will work as normal since _last_finish will be updated.
If we expect a lot of edge cases like this, it might make sense to expose a synthetic_report equivalent for the gRPC stream.

TIG-2478 FTDC outputs for setup operation have negative totals

---

src/workloads/networking/TransportLayerConnectTiming.yml

This diff creates a simple workload to invoke runCommand({replSetTestEgress: 1}) against replset-auth-delay configuration.
See DSI PR 592 for a detailed description of the goals of this project.  TL;DR - Track connection establishment time.

TIG-2386 Add connection establishment latency test

---

src/metrics/include/metrics/operation.hpp
src/metrics/include/metrics/v2/event.hpp

gRPC can only have one call "in-flight" per stream, so what this does is for every operation that writes to the stream, check if there's already an in-flight operation. If so, block until it completes then do the write.
Hopefully this corrects the performance problem. If not we might have to do something more complicated like adding buffers or more streams per thread.
[Patch-build](https://evergreen.mongodb.com/version/5e90c155a4cf47259c6d318b) where I modified InsertRemove to use FTDC outputs.

TIG-2497 Use non-blocking gRPC calls in Genny metrics

---

src/lamplib/tasks/download.py

Not running locally since the MacOS version of the curator waterfall hasn't run yet, but if it passes the evergreen tests we should be good.
Will run a patch to see if this actually fixes MAKE-1256 but either way we should still merge to fix MAKE-1257.

TIG-2505 Update poplar version in genny

---

src/workloads/scale/MixedWrites.yml

Only downside of this is it converts mixed_writes_replica_delay_mixed to FTDC-based output as well. That task is currently green so that's unnecessary and we'd lose change point triaging on it, but we can currently only specify metrics format for the workload not for workload-mongodbsetup pairs.
PB showing it works / fixes the problem: https://evergreen.mongodb.com/version/5eb2e7e62fbabe2124677a54
(Ignore the purple in that PB that's from TIG-2522)

TIG-2521 Convert mixed_writes_replica to use FTDC-based metrics reporting

---

src/cast_core/include/cast_core/actors/MultiCollectionUpdate.hpp
src/cast_core/src/CollectionScanner.cpp
src/cast_core/src/MultiCollectionUpdate.cpp
src/workloads/docs/LongLivedWriter.yml
src/workloads/scale/BigUpdate.yml
src/workloads/scale/InCacheSnapshotReads.yml
src/workloads/scale/InsertRemove.yml
src/workloads/scale/LargeScaleLongLived.yml
src/workloads/scale/LargeScaleModel.yml
src/workloads/scale/LargeScaleParallel.yml
src/workloads/scale/LargeScaleSerial.yml
src/workloads/scale/OutOfCacheSnapshotReads.yml

One of the phase (PointInTimeScanner-Scan-History) in the OutOfCacheSnapshotReads workload is pretty noisy at the moment (see the workload doc in the ticket). But I would like to open a PR first to have some feedbacks while I continue tuning some parameters for the workloads.
This PR extends the existing CollectionScanner actor to read at a point in time using {level: "snapshot", atClusterTime: <TS>}. Since the driver doesn't support reading at a point in time at the moment, I had to write my own find and getMore commands to do the scan.

PERF-2001: InCacheSnapshotReads & OutOfCacheSnapshotReads

---

src/workloads/execution/UserAcquisition.yml

This workload measures the amount of time required to acquire a User object from the local privilege database on a UserCache miss.
It is preliminary to work to remove the internal RoleGraph structure in favor of transactional aggregation based user document resolution.

PERF-2016 Create UserAcquisition workload

---

src/python/gennylib/auto_tasks.py
src/python/tests/auto_tasks_test.py

https://spruce.mongodb.com/version/5f43e30a32f4171537ac59ee/tasks

TIG-2650 Use longer timeouts for generated tasks

---

src/workloads/execution/PipelineUpdate.yml

Added a new workload that uses delta-style update oplog entries. There is also a 'phase' to run only classic updates that are equivalent to another phase which runs only pipeline-based updates. 
Sys-perf evergreen: https://spruce.mongodb.com/version/5f4516fce3c33163f25b4a75/tasks

PERF-1997 Introduce pipeline-based updates sys-perf workload

---

src/canaries/benchmark/canaries_benchmark.cpp
src/canaries/src/Loops.cpp
src/gennylib/include/gennylib/PhaseLoop.hpp
src/gennylib/include/gennylib/context.hpp
src/gennylib/include/gennylib/conventions.hpp
src/gennylib/include/gennylib/v1/GlobalRateLimiter.hpp
src/gennylib/src/context.cpp
src/gennylib/test/GlobalRateLimiter_test.cpp
src/gennylib/test/conventions_test.cpp
src/workloads/docs/HelloWorld.yml

Had a bit of difficulty managing the complexity of a rate being either a percent or the existing format, any thoughts on a way to improve that are welcome. I'd considered having the `RateSpec` be complicated enough to enclose both forms, but wasn't sure if we wanted those convention primitives to be that smart.
Patch running Insert-Remove for twice as long with a 50% rate limit: https://evergreen.mongodb.com/version/5f87a5152a60ed65c96234f6

TIG-2585 Add rate limit based on metrics feedback

---

src/workloads/execution/UnionWith.yml

Hey Katherine - do you mind taking a look at this PR? The idea is to move away from using explain but make sure that all returned documents can fit into a single batch, such that we can still "exhaust" the union pipelines but with the downside that we're incurring overhead for returning documents over the network. 
EVG run: https://evergreen.mongodb.com/version/5f92f1782a60ed74cffbb0ab

TIG-2745 Update $unionWith workloads to not rely on explain

---

src/phases/scale/MixPhases.yml
src/workloads/scale/MixedWorkloadsGenny.yml

Patch running mixed workloads: https://evergreen.mongodb.com/version/5fa9e74b56234315552d1027
I made [this spreadsheet](https://docs.google.com/spreadsheets/d/1bkpnDuCdkaEqZx7tRyITID1ZWm1D-XnplukqgNsQ7GM/edit#gid=0) to compare the CSV and FTDC throughput with the threading changes, and the differences seemed small enough and in both directions enough to be noise (as far as I can tell).

TIG-2628 Increase mixed_workloads_genny duration back to 7min and use FTDC format metrics

---

src/metrics/include/metrics/metrics.hpp

Older compilers don't see that the `case` statements are exhaustive.

TIG-2773 Add throw to prevent false-positive warning

---

src/phases/execution/CreateIndexPhase.yml
src/workloads/execution/CreateIndex.yml
src/workloads/execution/CreateIndexSharded.yml

Evergreen: https://spruce.mongodb.com/version/5fb2daa50ae6060498b51321/tasks (the failures are not relevant; create_index_sharded failing on a standalone/repl set is expected).
This is my proposed fix for https://jira.mongodb.org/browse/PERF-2061. Another way to handle this would be to allow for geoHaystack indexes to only be created when running against version 4.4 or below, but a recent thread on slack seems to suggest that this isn't possible at the moment.

PERF-2061 Remove references of geoHaystackIndex from workloads testcases

---

scripts/dry-run-workloads.sh
src/cast_core/test/LoggingActor_test.cpp
src/gennylib/src/context.cpp
src/gennylib/test/GlobalRateLimiter_test.cpp
src/metrics/test/metrics_test.cpp
src/workloads/scale/MixedWorkloadsGenny.yml

It looks like the changes from [genny#375](https://github.com/mongodb/genny/pull/375) that actually set FTDC as the default were lost in the merges/fixes.
Patch, when it's done I'll skim for regressions: https://evergreen.mongodb.com/version/5fb82f15c9ec447cdd7d9b86

Set FTDC as the default metrics reporting

---

src/lamplib/tasks/download.py
src/metrics/include/metrics/v2/event.hpp
src/metrics/test/metrics_test.cpp

Previously the buffer would only start draining when it reached 25% capacity, requiring the buffer to be 4x larger than we need just to be safe. This PR greatly increases the grpc thread sleep and adds an actor-thread-side check of when the buffer is almost full, to then wake the grpc thread.
In most workloads the buffer drain is probably going to be determined by the actor thread check, but the grpc-side wakeup and check may still be used by workloads like `large_scale_model`.
[Patch](https://evergreen.mongodb.com/version/5fb5ae13a4cf4723df226a62) running `large_scale_model` and `mixed_workloads_genny` along with the poplar changes, showing similar `mixed_workloads_genny` throughput to a [patch](https://evergreen.mongodb.com/version/5fb54dd1a4cf4723df1e6330) with the current master …

TIG-2781 Reduce metrics buffer size

---

src/phases/scale/LargeScalePhases.yml
src/workloads/scale/LargeScaleModel.yml

Since we'll be reusing configuration from the `LargeScaleModel` workload, we should take this opportunity to abstract each phase into a "phases" YAML so that it can be shared across workloads.
I've inspected the output with `genny evaluate` before and after this change. It's a bit hard to compare because the variables are assigned different numbers but it looks reasonable and follows the same structure.

WT-6697 Refactor existing LSWA workload into separate YAML files

---

src/cast_core/src/CrudActor.cpp
src/phases/scale/MixPhases.yml

Temporary workaround until the underlying drivers issue gets fixed.
Raiden and I had been staring at this for a while and we're pretty confident the driver just isn't retrying where it should. We're going to file a HELP ticket to have some domain experts look at it and revert this commit.
In progress maintenance build variant patch: https://evergreen.mongodb.com/version/5fd21592d1fe071a9dcae722

TIG-2805 Ignore failed writes and don't error out.

---

src/cast_core/src/CrudActor.cpp
src/workloads/docs/CrudActor.yml

Followup to #393 
This works around the C++ driver issue.
green patch: https://evergreen.mongodb.com/build/sys_perf_linux_3_node_replSet_maintenance_events_patch_e36da1b27ef763f4d7367ddf0f2f97259c0deac3_5fd21592d1fe071a9dcae722_20_12_10_12_50_50

TIG-2805 allow specifying ignoreError at the phase level

---

src/cast_core/include/cast_core/actors/MonotonicLoader.hpp
src/cast_core/src/MonotonicLoader.cpp
src/workloads/scale/ScanWithLongLived.yml

@guoyr 
As discussed with @sulabhM, we need some way of generating monotonically increasing _ids.
I've voted for this feature on the ideas doc, but in the interim to unblock ourselves, I'm proposing to add a `MonotonicLoader` which basically does the same thing but with monotonically increasing _ids (the guts of this change is in e229083). When this feature gets implemented, we can remove this actor.

WT-7041 Add MonotonicLoader actor

---

src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocGenYamlTestCaseRunner.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml

The general ethos is to support  ISO-8601 and  "%Y-%m-%d". Other formats could be added but are not for the moment.
Parsers support is to the milliseconds (for easy cut and paste) in the input string but the actual precision is to seconds.
Timezone specifiers as the end of the input strings are not supported(they don't throw an error but they also are not applied unless they happend to be 'Z' or '+00:00').

Add Now and RandomDate Generators

---

src/python/README.md

This scripts were removed, but this documentation was not updated.

TIG-2720 remove references to relocated python scripts from documentation

---

src/workloads/scale/ScanWithLongLived.yml

Not sure if this is the culprit behind why this task sometimes doesn't get generated in patch builds. But I figure we may as well eliminate that possibility and fix the indentation.

WT-7057 Fix AutoRun indentation in LSWA workload

---

src/cast_core/src/RunCommand.cpp
src/workloads/sharding/ReshardCollection.yml

Also adds support for "ClientName" in RunCommand actor for running operations through a connection pool other than the "Default" one.
Sys-perf patch build: https://evergreen.mongodb.com/task/sys_perf_linux_shard_lite_reshard_collection_patch_4b6a89a429c39a4f0848e7723f7bda9d22576cf9_5fff91fbd6d80a156b0ca5fe_21_01_14_00_37_52/1
Sys-perf patch build <span>#</span>2: https://evergreen.mongodb.com/task/sys_perf_linux_shard_lite_reshard_collection_patch_cc8671bcf846a6aeda28a5cf81aea750c2fca4bd_60073a961e2d17558c27f16a_21_01_19_20_04_06/0

PERF-2087: Add workload for reshardCollection with reads and writes

---

src/cast_core/src/CollectionScanner.cpp
src/phases/scale/LargeScalePhases.yml
src/workloads/scale/ScanWithLongLived.yml

@sulabhM 
I'm just putting this here to make it visible to you.
We're not seeing much lookaside usage yet but the transaction length looks good and the yielding has been solved. Reducing the document count and increasing the size hasn't helped as we'd anticipated.

WT-7075 Prevent MongoDB yielding in the LSWA workload

---

src/metrics/include/metrics/metrics.hpp
src/value_generators/include/value_generators/DocumentGenerator.hpp
src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocGenYamlTestCaseRunner.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml

Here is the first draft of the incrementing counter https://jira.mongodb.org/browse/PERF-2077 for discussion. I don't like it at all - not what it does, not code itself... Don't think that it is ready for a merge in any way. But after wasting a lot of time trying to figure out architecture / new C++ features / yaml / etc, it looks like I can utilize some help and I decided that bringing it out as a PR may be a good way to solicit some help. Here is the list of questions I have for now (and I probably didn't get to all questions yet].
1. It looks like the current DocumentGenerator architecture doesn't allow to have a shared counter between Actors - as its instances are per Actor.  [It appears that a shared counter may be in the workload context - but it appears that it will require much …

PERF-2077 incrementing counter

---

src/phases/scale/LargeScalePhases.yml
src/workloads/scale/LargeScaleModel.yml
src/workloads/scale/ScanWithLongLived.yml

- Fix ScanWithLongLived to run for a shorter duration and use replica sets.
- Stop running LargeScaleModel since it generates BFs and doesn't do anything useful.

WT-7193 Cleanup Evergreen tasks for LSWA

---

src/value_generators/include/value_generators/DocumentGenerator.hpp
src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocGenYamlTestCaseRunner.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml

**dateStringParserGenerator** calls **stringGenerator**. As a result, it supports all the generators (even if they don't make sense like ^IP).

PERF-2089 Update ^RandomDate Generator to accept other generators as input

---

src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActorYamlTests.yml

CrudActor ignores options for most operations including find. It does process some options only for four operations: BulkWrite, CountDocuments, EstimateDocumentCount, and StartTransaction. All options must be spell out in the code to be processed. It just ignores it otherwise without any error and warning.
So this PR adds support of a few options for find and findOne and adding a test that supposed to check it.
Ideally it would be good to get a warning when something in the yml file is ignored.
As I need it for PERF-2096 while it is not directly related to it - submitting this small PR separately.

PERF-2159 Adding options support for find and findOne in CrudActor

---

src/cast_core/src/RollingCollections.cpp
src/driver/src/DefaultDriver.cpp

[Patch showing (for example) ](https://evergreen.mongodb.com/task/sys_perf_linux_3_node_replSet_insert_remove_patch_f4054ff40c1c8309eefdbc87e84e8e8403e51281_603c10a67742ae2eaf0c43fb_21_02_28_21_56_21##hidden=Genny-Setup%252CHelloWorld-DefaultMetricsName.0%252CHelloWorld-DefaultMetricsName.1%252CHelloWorld-DefaultMetricsName.2%252CInsertRemoveTest.Insert%252CInsertRemoveTest.Remove%252CInsertRemove.Setup%252CInsertRemove.ActorStarted%252CInsertRemove.ActorFinished%252Cfio%252Ccpu_noise%252Ciperf%252Ccanary_InsertRemove.ActorFinished%252Ccanary_InsertRemove.Setup%252CNetworkBandwidth%252Cfio_latency_test_write_clat_mean%252Cfio_latency_test_read_clat_mean%252Cfio_iops_test_write_iops%252Cfio_iops_test_read_iops%252Cfio_streaming_bandwidth_test_write_iops%252Cfio_streaming_bandwidth_test_read …

TIG-2836 hide genny internal metrics by default

---

src/phases/scale/LLTPhases.yml
src/workloads/scale/InsertLLT.yml

This [patch](https://evergreen.mongodb.com/task/sys_perf_linux_1_node_replSet_insert_llt_patch_fccad833c9081bf0cd61364afdb4ec01ceeb42fa_604152b13e8e8645bfb2ba56_21_03_04_21_36_21)  is for the first commit but there is not a huge change in functionality.
I want to create 2 workloads with difference values for InitialDocumentCount and SecondaryDocumentCount (an in-memory and not in-memory configuration).
I could do an in-memory test phase (the current workload) , drop the database and then run the test again with different values for the not in-memory but I think keeping them separate is simpler.
At the moment, it looks like I will need to make a copy og src/workloads/scale/InsertLLT.yml and update the values. This seems a very verbose approach. Is there a better way to do this or is there …

PERF-2175 load phase

---

src/workloads/scale/LLTInsert.yml

Small change to guard against no output timeout. Waiting on the [patch](https://spruce.mongodb.com/version/6064475f9ccd4e677aaba416/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) to complete.

PERF-2241 guard against timeout

---

src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml

One symbol change to set multiplier default value to 0 in ^Inc value generator.
It appears that current multiplier default value 1 in ^Inc value generator is not helpful - if we generate data with a single thread, 0 makes sense. If we generate data with multiple threads, it should be a large value. So after a team discussion it was decided to change the default for multiplier to 0.

Perf 2239 Set multiplier default value to 0 in ^Inc value generator

---

src/workloads/scale/LLTMixed.yml
src/workloads/scale/LLTRemove.yml

[4.9 patch](https://spruce.mongodb.com/version/607ecf0f5623436443aa20d1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[4.2 patch](https://spruce.mongodb.com/version/607ecf7bd1fe07323e55bcdc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-2240 4.2 doesn't support hints on remove operations

---

src/workloads/docs/Generators.yml

This is to add information about ^Inc to src/workloads/docs/generators.yml
Would be that enough?
Actually everything below actorString (now, year2015, greaterThan2105, etc) is not in the document sample at the top. Does it still look consistent enough?

PERF-2264 Add examples of ^Inc to src/workloads/docs/generators.yml

---

src/workloads/scale/LLTInsert.yml
src/workloads/scale/LLTMixed.yml
src/workloads/scale/LLTQuery.yml
src/workloads/scale/LLTRemove.yml
src/workloads/scale/LLTUpdate.yml

Patches:
* [V4.2 Correct Mixed and set ScanDuration once](https://spruce.mongodb.com/version/6081ad610305b96b7aece298/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
* [Master Correct Mixed and set ScanDuration once](https://spruce.mongodb.com/version/6081acaa61837d07d0709c66/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-2182 set transactionLifetimeLimitSeconds and ScanDuration

---

src/cast_core/src/CollectionScanner.cpp
src/workloads/docs/CollectionScanner.yml
src/workloads/scale/LLTInsert.yml
src/workloads/scale/LLTMixed.yml
src/workloads/scale/LLTQuery.yml
src/workloads/scale/LLTRemove.yml
src/workloads/scale/LLTUpdate.yml
src/workloads/scale/ScanWithLongLived.yml

The current implementation sleeps for to make up the time to ScanDuration. This means that the transaction is open but inactive for a portion of the lifetime.
This new flag allows a transaction to be kept open and active for the the full ScanDuration.
This is required for the longer (60 Minutes+ ScanDuration) LLT tests.

PERF-2305 Add ScanContinuous mode for snapshots CollectionScans

---

README.md

As requested in slack, a hopefully super-temporary workaround message until TIG-2819 goes it.

Update README with workaround for toolchain leaks

---

src/workloads/transactions/LLTInsertHighGtc.yml
src/workloads/transactions/LLTInsertHighLtc.yml
src/workloads/transactions/LLTInsertLowGtc.yml
src/workloads/transactions/LLTInsertLowLtc.yml
src/workloads/transactions/LLTMixedHighGtc.yml
src/workloads/transactions/LLTMixedHighLtc.yml
src/workloads/transactions/LLTMixedLowGtc.yml
src/workloads/transactions/LLTMixedLowLtc.yml
src/workloads/transactions/LLTQueryHighGtc.yml
src/workloads/transactions/LLTQueryHighLtc.yml
src/workloads/transactions/LLTQueryLowGtc.yml
src/workloads/transactions/LLTQueryLowLtc.yml
src/workloads/transactions/LLTRemoveHighGtc.yml
src/workloads/transactions/LLTRemoveHighLtc.yml
src/workloads/transactions/LLTRemoveLowGtc.yml
src/workloads/transactions/LLTUpdateHighGtc.yml
src/workloads/transactions/LLTUpdateHighLtc.yml
src/workloads/transactions/LLTUpdateLowGtc.yml
src/workloads/transactions/LLTUpdateLowLtc.yml
src/workloads/transactions/README.md

Only the LLT*LowLtc.yml files changed. The parameters **InitialDocumentCount**, **SecondaryDocumentCount**, **GlobalRateValue** and **ThreadsValue** were moved to the start of the global block.
The remainder of the files were generated from the sed script in the new README.md.

PERF-2260 add other configurations

---

README.md
run-genny
src/lamplib/requirements.txt

I was trying to install genny on my phone using [iSH](https://ish.app/) which uses a pretty stripped-down version of Arch. I needed `pip` and `wheel` installed. Also the README saying it's ready to go was..a bit too optimistic.
(FWIW the install still bails due to no version of curator and the toolchain, but this at least uncovered a few new assumptions.)

Use ensurepip and wheel for more robust installs

---

README.md
src/workloads/execution/SetWindowFieldsUnbounded.yml

From the [patch build results](https://evergreen.mongodb.com/task/sys_perf_linux_1_node_replSet_set_window_fields_unbounded_patch_441bef2c968ab24fe52d910c26dc3ecac366d0eb_60ad6c221e2d175d3bf3b122_21_05_25_21_30_55#):
Test | 1 | 8 | Max
-- | -- | -- | --
SetWindowFields.BothSpill | 1,377,322,332 | &nbsp; | 1,377,322,332
SetWindowFields.NothingSpills | 100,871,471 | &nbsp; | 100,871,471
SetWindowFields.PartitionSpills | 226,255,058 | &nbsp; | 226,255,058
SetWindowFields.SortSpills | 1,436,059,760 | &nbsp; | 1,436,059,760
I'm surprised that "BothSpill" would be slightly faster than "SortSpills".  Maybe that's just noise?  It is under 5% difference.

PERF-2299 Test unbounded window functions, with spilling

---

src/lamplib/src/genny/curator.py

Downloading curator currently fails on Ubuntu 18.04 because the changes from mongodb/curator@0a6a6d1c254c9238a0bd944d6060466b0db50024 moved the compile task from Ubuntu 16.04 to Ubuntu 18.04.
https://evergreen.mongodb.com/task/curator_ubuntu_push_2230334f0369ea999b8fd2ada0de61e4b4a6e2b0_21_06_01_22_47_01 shows "ubuntu" as the new build variant name.
```
$ ./run-genny -v install --linux-distro=ubuntu1804 
[debug] [genny.download      ] Downloading          name=curator timestamp=2021-06-05T16:54:38Z url=https://s3.amazonaws.com/boxes.10gen.com/build/curator/curator-dist-ubuntu1604-2230334f0369ea999b8fd2ada0de61e4b4a6e2b0.tar.gz
...
urllib.error.HTTPError: HTTP Error 404: Not Found
```

TIG-3063: Fix curator download on Ubuntu 18.04

---

evergreen.yml
src/lamplib/src/genny/toolchain.py

Somehow the very first waterfall commit worked https://evergreen.mongodb.com/waterfall/genny-toolchain lol. I'll take it. Might be an evergreen discrepancy between patch and waterfall builds 🤷

TIG-2819 Update toolchain build id

---

src/gennylib/src/context.cpp
src/lamplib/src/genny/curator.py

Changes the CedarMetrics location to match the DSI-side changes.

TIG-3059 Use perf.send for all sys-perf and performance projects.

---

src/cast_core/include/cast_core/actors/PhaseTimingRecorder.hpp
src/cast_core/src/CollectionScanner.cpp
src/cast_core/src/CrudActor.cpp
src/gennylib/include/gennylib/Orchestrator.hpp
src/gennylib/include/gennylib/PhaseLoop.hpp
src/gennylib/include/gennylib/context.hpp
src/gennylib/include/gennylib/conventions.hpp
src/gennylib/include/gennylib/v1/Sleeper.hpp
src/gennylib/src/Orchestrator.cpp
src/gennylib/src/context.cpp
src/gennylib/test/GlobalRateLimiter_test.cpp
src/metrics/include/metrics/metrics.hpp
src/metrics/include/metrics/v2/event.hpp
src/value_generators/test/DocGenYamlTestCaseRunner.cpp

The main actual change is to wake up all threads when the phase ends, so that the GlobalRate sleeps don't carry over to the next phase. Ended up being smaller than I expected since we could piggyback on the Orchestrator's CV.

TIG-3028 Allow GlobalRate to be specified for background actors

---

src/workloads/execution/ShardedLookup.yml

This new workload currently contains a phase which runs untargeted $lookups (not eligible for shard targeting) on a sharded collection into another sharded collection. We anticipate adding new phases to this workload to test other kinds of sharded $lookups, e.g. targeted $lookups and $lookups on unsharded collections into sharded collections. We will either add new phases to this workload or create a new, corresponding workload for sharded $graphLookup.
Here is the [workload proposal document](https://docs.google.com/document/d/1JLTTS7jJDiMxrhT2yMNSW7YA07KtVgoUbB9jXEKpujU/). It includes the following table showing some example output and robustness results:
<meta charset="utf-8"><p dir="ltr" style="line-height:1.38;margin-top:0pt;margin-bottom:10pt;"><span …

PERF-2360: Add new workload for untargeted sharded $lookup

---

src/workloads/execution/UnshardedLookup.yml

Ran a $lookup against two unsharded collections. One was run in a sharded environment with the sharded lookup feature flag turned on, the other was run with the feature flag turned off. The query was ~33% faster with the feature flag disabled.
Metric | shard-lite | shard-lite-all-feature-flags
-- | -- | --
AverageLatency | 981,263,356 | 1,467,256,868
[Evergreen patch](https://spruce.mongodb.com/version/60f21666d6d80a245ce1599a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-2448 Benchmark an unsharded lookup in a sharded environment

---

src/workloads/execution/ShardedLookup.yml

PERF-2359 Targeted lookup from a sharded collection to a sharded collection
PERF-2362 Untargeted lookup from an unsharded collection to a sharded one
Benchmark | AverageLatency
-- | --
UntargetedLookupUnshardedIntoSharded | 6,460,528,788
UntargetedLookupShardedIntoSharded | 3,505,457,432
TargetedLookupUnshardedIntoSharded | 2,106,877,279
TargetedLookupShardedIntoSharded | 1,087,654,546
A few things to note are that targeted tests are faster than untargeted since certain shards can be left unread. Also an untargeted lookup where the left side is sharded is ~2X faster than when the left side is unsharded. This because the former lookup can be parallelized across shards.

PERF-2358 Targeted lookup from an unsharded collection to a sharded one

---

src/workloads/execution/UnshardedLookup.yml

With the feature flag turned on:
Benchmark | AverageLatency
-- | --
MatchSingleShardLookupUnsharded | 14,243,024
MatchAllShardsLookupUnsharded | 14,884,660
With the feature flag turned off:
Benchmark | AverageLatency
-- | --
MatchSingleShardLookupUnsharded | 9,508,384
MatchAllShardsLookupUnsharded | 12,764,823
When the feature flag is enabled, there is a bit of a regression in the performance of $lookup from a small sharded collection to an unsharded collection. Also surprisingly there doesn't seem to be much of a difference between the two benchmarks when the feature flag is enabled, even though one must scan all shards before performing the lookup whereas the other only needs to read from a single shard.

PERF-2390 Lookup from sharded collection to unsharded collection

---

src/workloads/execution/LookupInUnshardedEnvironment.yml
src/workloads/execution/UnshardedLookupCachedPrefix.yml

From [this patch build](https://spruce.mongodb.com/version/610d3c9d1e2d173508a875db/tasks), we get the following results.
With feature flag disabled, in an unsharded environment:
| Benchmark | Avg latency (sec)  |
|---|---|
| LookupWithCachedPrefixUnshardedToUnsharded | .1554993457 |
This is by far the fastest result. 
With feature flag disabled:
| Benchmark | Avg latency (sec)  |
|---|---|
| LookupWithCachedPrefixUnshardedToUnsharded | 7.6843960346 |
| LookupWithCachedPrefixShardedToUnsharded | 7.6966880165|
With feature flag enabled:
| Benchmark | Avg latency (sec)  |
|---|---|
| LookupWithCachedPrefixUnshardedToUnsharded | 9.1613125435 |
| LookupWithCachedPrefixShardedToUnsharded | 5.5058569847 |
When the feature flag is turned on, we see a slow down in the unsharded local case because …

PERF-2426: Add tests for caching behavior of unsharded $lookup

---

src/workloads/execution/ShardedLookup.yml

From [this patch build](https://spruce.mongodb.com/version/610d3c9d1e2d173508a875db/tasks), we get the following results.
| Benchmark | Avg latency (sec)  |
|---|---|
| LookupWithCachedPrefixUnshardedToSharded | 17.1584018563 |
| LookupWithCachedPrefixShardedToSharded | 9.4955312718 |
The queries with sharded local collections are faster because the $lookup can be parallelized.
It's interesting to see how these results relate to #512. Compared to the UnshardedToUnsharded (~9.2 sec) and ShardedToUnsharded (~5.5 sec) feature-flag-enabled benchmarks, we see a slow down when the foreign collection becomes sharded. A slow down is expected, since when the foreign collection is sharded we have to scatter-gather results instead of targeting just the primary. However, it's much slower than I …

PERF-2378: Add tests for caching behavior of sharded $lookup

---

src/cast_core/src/Loader.cpp
src/cast_core/src/LoggingActor.cpp
src/lamplib/src/genny/tasks/dry_run.py
src/phases/scale/MixPhases.yml
src/workloads/scale/BigUpdate10k.yml
src/workloads/scale/LoadTest.yml
src/workloads/scale/MixedWorkloadsGenny.yml
src/workloads/scale/MixedWorkloadsGennyStress.yml

Patch build: https://evergreen.mongodb.com/build/sys_perf_linux_3_node_replSet_patch_01fb3fac6dbf5a6566e0ce6cf5218d4274df19f1_611d2d8b1e2d17098199f36a_21_08_18_15_56_52
The patch build was successful for MixedWorkloadsGennyStress and LoadTest, so I've included those two here. I need to figure out how to get BigUpdate10k to not timeout during validate. I'll split that problem off of this work. 
Note, this PR effectively re-enables PERF-2330 & PERF-2255 miscellaneous changes (#500) (#523) change that was previously reverted. It should also have a working auto run for it.

PERF-2429 Add Stress Tests to Production (mixed stress and Load Test)

---

src/workloads/execution/UnshardedGraphLookup.yml

From [this](https://spruce.mongodb.com/version/6148dfd20305b97273016779/tasks) evergreen patch, we see the following results.
Feature flag off:
| Benchmark | Avg latency (sec)  |
|---|---|
| GraphLookupShardedToUnshardedMaxDepthZeroOneToOne  | 5.0487785019 |
| GraphLookupShardedToUnshardedMaxDepthZeroOneToFive | 1.5662687845 |
| GraphLookupShardedToUnshardedMaxDepthZeroOneToOneHundred | 1.3148955413 |
| GraphLookupShardedToUnshardedMaxDepthZeroMatchOneToTenTargeted | .8854111305 |
Feature flag on:
| Benchmark | Avg latency (sec)  |
|---|---|
| GraphLookupShardedToUnshardedMaxDepthZeroOneToOne | 3.660342830 |
| GraphLookupShardedToUnshardedMaxDepthZeroOneToFive | 1.6935450762 |
| GraphLookupShardedToUnshardedMaxDepthZeroOneToOneHundred | 1.178930092 |
| …

PERF-2571: Add genny tests for $graphLookup with maxDepth 0

---

docs/setup.md

I was installing genny on my workstation, and I got an error that the install dir didn't exist. /data/mci isn't a standard directory available on the workstation, so I got confused. I've added a note to our setup docs to clarify.

Clarify install dir for genny

---

src/gennylib/test/GlobalRateLimiter_test.cpp

Templatizing phaseloop on a ClockSource would be a bit too invasive of a change to be worth it in the near-term, when this is red for basically every PR (affecting workload authors too). And even that wouldn't remove the thread-based nondeterminism. Arguably the thread jumble like this is expected and mocking it out would be a worse test of behavior anyway. (Plus we have separate unit tests for rate limiters anyway; the benchmark test I believe is happier with a more "real-world" situation.)
We could consider doing some stats about this, but the exact distribution would probably vary from machine to machine, and this is in line with how the other benchmark tests measure behavior.
Tested by removing the "benchmark" tag and running with `--repeat=500`, seemed good.

TIG-3236 t_benchmark_test is flaky

---

docs/using.md

I’m following steps here. Is this guide up to date?
I noticed that following steps fail:
```
brew install mongodb
$ brew install mongodb
Warning: No available formula with the name "mongodb". Did you mean mongosh or monetdb?
==> Searching for similarly named formulae...
These similarly named formulae were found:
mongosh                                                                       monetdb
To install one of them, run (for example):
brew install mongosh
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```
I’m not sure why this step is necessary. I guess one can use locally-built mongod.
```
$ ./run-genny workload -- run --workload-file …
```

Updated a few failing steps

---

CMakeLists.txt
cmake/FindMongoCxx.cmake
evergreen.yml
src/gennylib/include/gennylib/parallel.hpp
src/gennylib/test/Node_test.cpp
src/lamplib/src/genny/tasks/compile.py
src/lamplib/src/genny/toolchain.py

I think we can expect RHEL 7 build to fail due to to the errors on the toolchain, but that's unrelated to our recent work and shouldn't affect production anyway because of [TIG-2860](https://jira.mongodb.org/browse/TIG-2860). I think we should go ahead with the upgrade because [TIG-3753](https://jira.mongodb.org/browse/TIG-3753) is affecting production anyway and that fix would be lumped into this upgrade. 
If this is agreed to merge, I can cut a followup ticket to either deal with the RHEL7 issue or just stop building the toolchain on it. Based on a conversation with @richardsamuels  it seems to be a rhel licensing issue which we'll either have to file a dependent build ticket for, or else find a hacky workaround.

TIG-3391 Upgrade C++ Driver for Genny

---

src/phases/tpch/denormalized/Q17.yml
src/phases/tpch/denormalized/Q2.yml
src/phases/tpch/denormalized/Q9.yml
src/phases/tpch/normalized/Q17.yml
src/phases/tpch/normalized/Q9.yml
src/workloads/tpch/denormalized/1/Q17.yml
src/workloads/tpch/denormalized/1/Q9.yml
src/workloads/tpch/normalized/1/Q17.yml
src/workloads/tpch/normalized/1/Q9.yml

Evergreen patch: https://spruce.mongodb.com/version/61fa8f6930661521f06d4635/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
This patch includes a fly-by fix to update query 2 on the denormalized schema to us a faster join order (similar to what the normalized schema does).

PERF-2771 Add workloads for TPC-H queries 9 and 17

---

src/lamplib/src/genny/tasks/auto_tasks.py

Genny previously assuemed all repo workloads have a master branch. PrivateWorkloads's default branch is named production

TIG-3678 Genny auto patch test task generation doesn't work with PrivateWorkloads

---

src/phases/execution/LookupCommands.yml
src/workloads/execution/LookupSBEPushdown.yml
src/workloads/execution/LookupSBEPushdownINLJMisc.yml
src/workloads/execution/LookupSBEPushdownMisc.yml

This is a draft PR to add workloads for $lookup pushdown feature.
Given that $lookup pushdown feature is a reimplementation of $lookup pipeline stage using the SBE, the proposed workloads have metrics for the SBE $lookup implementation and the classic $lookup implementation so that the team can compare the SBE results to the classic engine's results.
A related PR to add a build variant: 10gen/mongo#3201
See the document for details: 
https://docs.google.com/document/d/1KijhnCvbfhfWtZJXUSrreNK-vcke7xofdkuUrVrnjDo/edit#

PERF-2789 Add $lookup pushdown workloads

---

src/workloads/execution/TimeSeriesLastpoint.yml

From local testing, going from `featureFlagLastPointQuery=false` to `true` results in a 622x speedup. Will update with preliminary Evergreen results when they are available.

PERF-2754 Add perf tests for lastpoint optimization use case 1

---

src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActorYamlTests.yml

In a similar vein to [this PR](https://github.com/mongodb/genny/pull/620), we need to respect OnSession when it's on bulkWrite. [Example affected workload](https://github.com/mongodb/genny/blob/master/src/workloads/scale/UpdateMillionDocsInTxn.yml#L78).

TIG-3937 bulkWrite should not ignore OnSession

---

src/canaries/src/tasks.cpp

Worked locally with the fix but here's a [patch as well](https://spruce.mongodb.com/version/62263fd41e2d1747bf097442/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

TIG-3935 Wrong path to uri option in genny_canaries

---

src/phases/issues/ConnectionsBuildup.yml
src/workloads/issues/ConnectionsBuildup.yml
src/workloads/issues/ConnectionsBuildupNoSharding.yml

Moving common parts into phases and adding a separate ConnectionsBuildupNoSharding to run the workload on non-sharded  environments.
Here is [the patch](https://spruce.mongodb.com/version/622bc7d19ccd4e4a1a9b5d45/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-2818 Productionalize the ConnectionBuildup workload for non-sharded configurations

---

src/workloads/execution/LookupSBEPushdown.yml
src/workloads/execution/LookupSBEPushdownINLJMisc.yml

Given that the SBE lookup algorithms have not been yet fully implemented and we're enabling the feature on all-feature-flags build variant for correctness testing coverage, I'm temporarily disabling the SBE lookup perf testing.
As soon as we have enough confidence in feature's correctness, will re-enable the perf testing. Until then, we can run manually the SBE lookup perf testing by re-enabling the following part.
```
```

PERF-2883 Temporarily disable the SBE lookup testing

---

src/workloads/serverless/IndexStress.yml

JIRA ticket: [CLOUDP-116026](https://jira.mongodb.org/browse/CLOUDP-116026)
Yesterday during manual testing, this workload successfully triggered serverless scaling events! I'll add a successful patch here shortly, but this code should be fine to merge.

CLOUDP-116026: Create a new Genny workload to trigger serverless scaling events

---

src/workloads/execution/LookupSBEPushdownINLJMisc.yml

This is simple typo fix. The `TestRepeatCount` was meant to be 10, not 1.

Update the repeat count of LookupSBEPushdownINLJMisc.yml

---

src/workloads/execution/LookupSBEPushdown.yml
src/workloads/execution/LookupSBEPushdownINLJMisc.yml

Given that all lookup algorithms are working end-to-end and produce correct results, this PR enables the SBE lookup-related workloads on Evergreen sys-perf project.

PERF-2927 Enable the SBE lookup-related Genny workloads

---

src/workloads/scale/MixedWrites.yml

MixedWrites was being used by `AutoRun` on those variants where `infrastructure_provisioning` was `replica`. The issue is that `ThenRun` overwrites the `mongod_setup` of the variant, duplicating the work and running the variants with a different `mongodb_setup` from the ones configured in `system_perf`. This caused situations like `Linux 3-Node ReplSet Initial Sync` running with `replica` instead of the configured `replica-2node` and `linux-3-node-replSet-ssl` without SSL.
With this change the workload will only run on `linux-3-node-replSet` with `replica-delay-mixed` and `replica` MongoDB setups.

TIG-3849: Change AutoRun to mongodb_setup = replica

---

src/workloads/execution/LookupSBEPushdown.yml
src/workloads/execution/LookupSBEPushdownINLJMisc.yml

Given that we onboarded LookupSBEPushdown.yml and LookupSBEPushdownINLMisc.yml to compare the SBE lookup perf to the classic lookup perf, It's not necessary to run two workloads on v4 branches.
It looks like that the Quiesce actor won't work on v4.0 branch, looking at this patch build. The patch in the run disabled Quiesce actor in lookup_sbe_pushdown workloads which is successful but lookup_sbe_pushdown_inlj_misc workload failed.
https://spruce.mongodb.com/version/625487fa1e2d1770ebbec3f9/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Scheduled another patch build with this patch:
https://spruce.mongodb.com/version/6254975657e85a4a74752e74/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-2939 Exclude the lookup pushdown workloads from running on v4 branches

---

src/phases/execution/TimeSeriesSortCommands.yml
src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml
src/workloads/execution/TimeSeriesSortOverlappingBuckets.yml

Duplicate of [#646 ](https://github.com/mongodb/genny/pull/646)

PERF-2892 Extend initial performance tests to include overlapping bucket scenarios

---

src/lamplib/requirements.txt
src/lamplib/src/genny/tasks/preprocess.py
src/lamplib/src/tests/test_preprocess.py
src/workloads/docs/HelloWorld.yml

Many times it would be nice to have arithmetic with parameters in YAML files.
This is a proposal to add this functionality. Not sure if the syntax is the most appropriate, since it might be confusing with doc generators. Given that ^Parameter also follows this ^xxxx style, I used the same.

Add ^NumExpr preprocessing directive to perform arithmetic operations on YAML configuration files

---

src/workloads/scale/MixedWorkloadsGennyStress.yml

Patch build: https://spruce.mongodb.com/version/626adf410ae6067e047fdcb2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
It looks like this workload is still inserting documents, but I don't know how with that setting of threads. This should make it sane.

PERF-2696: Adjust actor and phase threads to match in mixed_workloads_stress

---

src/workloads/scale/ManyUpdate.yml

This is a workload that just does a simple multi-update on a large number of documents.  This ends up measuring the impact of secondary replication on the primary.
@dalyd 
@mridul-augustine

PERF-3040 Create a genny workload for measuring replication overhead

---

src/workloads/execution/ColumnstoreIndexes.yml

This PR is to add a query workload for columnar indexes and a companion PR with other PRs which have been submitted separately.
- system_perf.yml changes: https://github.com/10gen/mongo/pull/5229
- DSI test_control: https://github.com/10gen/dsi/pull/1053
@jimoleary,
Decided to not measure either cold cache or warm cache scenarios but just measure hot cache scenarios after discussion with the team.
As of now, all queries in the workload can leverage columnar indexes except `TopErrorsQuery` which uses a regular scan even though there is a columnar index.
Evergreen patch build:
https://spruce.mongodb.com/version/627d69980ae6067da38f8de6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-2985 Add query workloads for columnar indexes

---

src/workloads/issues/ConnectionPoolStress.yml

Patch: [single shard](https://spruce.mongodb.com/version/628c9f8a2fbabe7a3e6cb567/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-3053 Deploy Sharded stress testing conn pool workload

---

src/workloads/execution/DensifyTimeseriesCollection.yml

This change will create a pretty diverse set of buckets. We'll have buckets that close, buckets with a small amount of documents due to the previous bucket containing the meta/time range being full. Then we'll have buckets that have close to 1000 documents and are still open.
[patch](https://spruce.mongodb.com/version/62964f852a60ed2b207ddc7a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-3062: Change test data in DensifyTimeSeriesCollection to have more than one document per bucket

---

src/workloads/execution/ColumnStoreIndex.yml

This is to fix the perf BF: https://jira.mongodb.org/browse/BF-25436
The symptom is `{dropIndexes: "charts_metrics.events", indexes: ["$**_columstore"]}` command was failing due to non-existent namespace. Actually test_control.columnstore.yml file was restoring data into charts_metrics.events collection and creating a column store index. But somehow the test control file was not applied.
The culprit is `AutoRun` specification. If we want to run the columnstore genny workload as part of autorun tasks, it should have had the following specification.
```
AutoRun:
...
ThenRun:
test_control: columnstore 
```
Because the columnstore workload task has the separate test control file. Without {{ThenRun}} specification, autorun tasks does not apply the separate test control file.
For now, I will …

PERF-3093 Remove `AutoRun` configuration

---

src/phases/execution/ClusteredCollection.yml

Genny ignores autorun in the phases directory. This definition has one, and it's surprising and confusing. This change removes it. 
The workload itself still runs. The workload is defined in the workloads directory and uses LoadConfig to load this whole file.

Remove spurious autorun

---

src/phases/execution/GetBsonDate.yml
src/workloads/docs/RunCommand-Simple.yml
src/workloads/execution/ColumnStoreIndex.yml
src/workloads/scale/LargeIndexedIns.yml

This PR is to work around the issue of `ISODate` in the yaml file by introducing a parameterized configuration `GetBsonDate`. Also added column store index bulk builder metric and request `explain` with `executionStats` instead of the plain `aggregate` command.
Companion PR:
- https://github.com/10gen/dsi/pull/1062
Evergreen patch build:
https://spruce.mongodb.com/version/62bd2e520ae606411b5eec73/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-3129 Work around the issue of `ISODate` type and fix other minor issues

---

src/driver/src/DefaultDriver.cpp
src/gennylib/include/gennylib/Node.hpp
src/gennylib/src/Node.cpp
src/gennylib/test/Node_test.cpp

Almost verbatim the main parts from @rtimmons 's PR (#424), with a more recent commit / some line noise removed. Spent a bit of time trying to get this to work with the STL containers but got a bit tangled up in templates, so agree with pushing this out for now and filing a separate bug ticket to catch it later, and maybe a separate ticket to make it barf explicitly.
Fwiw, I think the stl containers don't see a ton of use extracted from YAML like that in actor code.
Right now it's always on by default in dry runs and workload runs, with warning verbosity if there's anything caught by it. Hopefully people won't find that too annoying.
Patch: https://spruce.mongodb.com/version/62d1afc5c9ec4462ba43fdba/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Updated patch: …

TIG-2766 Genny warn on unused yaml

---

src/gennylib/include/gennylib/v1/PoolManager.hpp
src/gennylib/src/encryption.cpp
src/gennylib/test/encryption_test.cpp
src/workloads/docs/CrudActorEncrypted.yml

This patch builds on top of this patch: https://github.com/mongodb/genny/pull/726 to add QE support.

PERF-3187 - Extend Genny to add queryable encryption support

---

src/workloads/docs/RunCommand-Simple.yml
src/workloads/execution/ConstantFoldArithmetic.yml
src/workloads/execution/ExpressiveQueries.yml
src/workloads/execution/ExternalSort.yml
src/workloads/execution/GraphLookupWithOnlyUnshardedColls.yml
src/workloads/execution/LookupSBEPushdown.yml
src/workloads/execution/LookupSBEPushdownINLJMisc.yml
src/workloads/execution/LookupWithOnlyUnshardedColls.yml
src/workloads/execution/UnionWith.yml
src/workloads/scale/LargeIndexedIns.yml
src/workloads/scale/MixedWorkloadsGenny.yml

This proposed `genny` change goes together with the following 10gen/mongo and 10gen/dsi PRs:
- https://github.com/10gen/mongo/pull/7536
- https://github.com/10gen/dsi/pull/1095
I suggest reading the 10gen/mongo patch first, followed by the 10gen/dsi patch, followed by this patch.

PERF-3305 Update AutoRun config to account for SBE build variants

---

src/workloads/execution/TimeSeriesSort.yml

Hey, I didn't know of a way to check if the feature flag was enabled or if there was an existing meta x time index, so I believe dropping all indexes (aside from the _id index) will be a suitable solution. The indexes will be dropped right after creating the timeseries collection. 
I am not very familiar with modifying workloads but I put up a [patch on evergreen](https://spruce.mongodb.com/version/633258b03066155c6b42b277/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&variant=%5Elinux-3-node-replSet-disabled-feature-flags%24) and it looks good.

SERVER-68113 Drop all indexes after creating timeseries collection in TimeSeriesSort

---

src/cast_core/src/CrudActor.cpp
src/phases/execution/UpdateWithSecondaryIndexes.yml
src/workloads/execution/UpdateWithSecondaryIndexes.yml

Add UpdateWithSecondaryIndexes workload:
```
Updates a large range of documents in the collection.
Multiple secondary indexes are present.
Update performed with and without a hint.
```
Fixed a bug that prevented update option from actually affecting updateMany operations.

SERVER-58712: Add UpdateWithSecondaryIndexes workload

---

src/workloads/execution/BackgroundIndexConstruction.yml

This workload is to test the impact of background index builds on a populated dataset while writes are occurring simultaneously.

PERF-3420 Add workload for background index build impact

---

src/phases/execution/ClusteredCollection.yml

Added range queires on '_id' and 'a' to test if multi planner can efficiently choose between clustered index scan and secondary index scan

PERF-3470 Add range query on '_id' and 'a' to clustered collection workload

---

src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActorYamlTestRunner.cpp
src/cast_core/test/CrudActorYamlTests.yml
src/workloads/docs/CrudActorAggregate.yml

Proposed detailed commit message:
> Aggregate, like find, returns a cursor. We often want to measure the time taken to fully iterate the cursor, including the time to process the initial request as well as any subsequent getMore commands. Past workarounds obviated by this change include using manipulating the batchSize to ensure that the complete reply fits in a single batch, or using explain with "executionStats" verbosity.
This is depended on by [PERF-3476](https://jira.mongodb.org/browse/PERF-3476) (see https://github.com/mongodb/genny/pull/757).

PERF-3485 Extend 'CrudActor' to support the aggregate command

---

src/workloads/scale/CreateDropView.yml

@dalyd I was hoping to get your thoughts on this workload related to [PERF-2891](https://jira.mongodb.org/browse/PERF-2891). 
Do you think this provides enough value to be added? 
It takes less than a minute to run, and would monitor the duration of time for views to be created and deleted (averages are around 400,000 ns). 
I'm not particularly attached to it, and am fine just documenting having looked at this. 
I previous tested a different [view create / drop workload](https://github.com/mongodb/genny/compare/master...PERF-2891-create_view#diff-425cec6331df008a5d898ac29ac1757e5a3711f6c89710b182ad69fd0b19e8e8R112) (64 threads with 10,000 repeated create / drop views each) for an hour alongside mixed CRUD actors, and the server did seem to queue up the commands, create / drop view latency …

PERF-2891: Adding workload for measuring create / drop time for views.

---

src/phases/encrypted/ContinuousWritesWithExponentialCompactTemplate.yml
src/phases/encrypted/YCSBLikeActorTemplate.yml
src/phases/encrypted/YCSBLikeEncryptedTemplate.yml
src/workloads/encrypted/ExponentialCompact.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1Cf16.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1Cf16Sharded.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1Cf32.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1Cf32Sharded.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1Cfdefault.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt1CfdefaultSharded.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5Cf16.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5Cf16Sharded.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5Cf32.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5Cf32Sharded.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5Cfdefault.yml
src/workloads/encrypted/YCSBLikeQueryableEncrypt5CfdefaultSharded.yml

This adds a subset of the tests performed in the PM-2759 QE performance project, but with reduced number of iterations so that it does not take more than a few hours to run on DSI.
There are two types of workloads:
1. the YCSB-like workloads that try to emulate a YCSB workload, but with queries on encrypted fields, as opposed to simply the '_id' field. These workloads are meant to test the performance of encrypted finds and update, for various contention factor settings and various number of encrypted fields.
2. the exponential compact workload, which tests the latency of a compaction operation relative to the size of the ECOC collection.
evg: https://spruce.mongodb.com/version/637557d3d1fe072d1a4f7ab8/tasks

PERF-3364 Add Genny workloads to run QE performance tests

---

src/cast_core/src/CrudActor.cpp

All tests using this and the documentation use the `unit` key, but the implementation looks for `units` and otherwise defaults to seconds.
This PR aligns the implementation and tests/documentation to all use `unit` and further removes the default to avoid this issue from flying under the surface again.

PERF-2738 fixed unit <-> units bug that caused incorrect phase transition timings

---

src/workloads/execution/BackgroundIndexConstruction.yml

This PR removes standalone variant and 6.0 testing since the meaningful results are only present in master right now

PERF-3660 Remove standalone build variant and 6.0 testing

---

src/gennylib/test/encryption_test.cpp

This rewrites a couple of test cases in encryption_test.cpp that had too strict assertions on the layout of the generated encrypted field schema documents, which resulted in test failure when ran on M1 Macs.

PERF-3659 Loosen assertions on encrypted field schemas in Genny's encryption_test.cpp

---

src/cast_core/src/RunCommand.cpp
src/workloads/docs/ParallelInsert.yml
src/workloads/execution/UserAcquisition.yml
src/workloads/networking/SecondaryAllowed.yml
src/workloads/networking/ServiceArchitectureWorkloads.yml
src/workloads/networking/TransportLayerConnectTiming.yml
src/workloads/query/PipelineUpdate.yml
src/workloads/scale/CreateDropView.yml
src/workloads/sharding/MongosMerging.yml

This PR makes isQuiet=true the default for the RunCommand actor as printing every command can generate quite log files (e.g., PipelineUpdate, ServiceArchitectureWorkloads, ParallelInsert) and in extreme cases even bottleneck the test on the client side (PipelineUpdate).
With isQuiet=true being the new default, this PR also removes all existing occurrences of isQuiet:true in existing tests.
This PR does not update any documentation as this was split of into [EVG-18383](https://jira.mongodb.org/browse/EVG-18383).

EVG-18233 Set isQuiet=true as default for RunCommand actor

---

src/workloads/docs/Generators.yml

This is the data generator I added for testing time-series geo indexes: https://github.com/mongodb/genny/commit/72e9cd37dce55d839c3640cfed3c74caecf660dc
I'm adding an example and some description of the behavior.  Let me know if this is helpful!

PERF-3697 Document TwoDWalkGenerator

---

src/lamplib/requirements.txt

This avoids needing to build a binary wheel for Linux arm64, so instead we can just download it.

EVG-18665: Upgrade patch version of numexpr.

---

src/workloads/query/locf.yml

This was caught in [BF-27122](https://jira.mongodb.org/browse/BF-27122) which has more details on how I diagnosed the bug. I wrote a descirption for PERF-3744 which has more context as well.
Among the fixes I considered, I think adding a limit is the simplest way to do it while keeping the workload logically the same. The queries could run considerably more slowly if we instead starting using the `CrudActor` to exhaust the cursor. And I didn't want to go the more complex route of teaching genny how to partially read from a cursor and then kill it.

PERF-3744 fix cursor leak in locf.yml

---

.gitignore
src/value_generators/include/value_generators/FrequencyMap.hpp
src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/value_generators/test/FrequencyMap_test.cpp
src/workloads/docs/Generators.yml

QE tests require a precise distribution of data. The data distributions are generated offline and then fed into the workload.yml files. See https://github.com/markbenvenuto/genny/blob/frequency_map/src/phases/encrypted2/maps_pbl.yml for an example of a real example of how this is used.
A new generator `TakeRandomStringFromFrequencyMap` is added to read from these list of data distributions.
```
foo:
^TakeRandomStringFromFrequencyMap:
from:
v1: 1
v2: 2
v3: 2
```
This generator will generate "v1" once, "v2" twice and "v3" thrice in a random order. If you ask for 7 values, it will throw an error.
To enable us to use this across multiple actors threads, there is a version called `^TakeRandomStringFromFrequencyMapSingleton` which creates a singleton of each map to ensure distribution is …

PERF-3654 Enhance Genny to support FrequencyLists

---

src/workloads/execution/BackgroundIndexConstruction.yml

This PR rewrites the BackgroundIndexConstruction workload to reflect a more realistic scenario.
It lowers the dataset size so that we can repeat index creation to reduce noise and overall runs with better timings.
It is a clean cut from the previous workload, only the Setup actor has been kept with the same name.

PERF-3746 Rewrite BackgroundIndexConstruction workload

---

src/workloads/scale/ContentionTTLDeletions.yml

In some instances the workload can fail due to a socket timeout. This happens if the server is overloaded. As this workload purposefully overloads the server, we should increase the timeout.

PERF-3778 Increase socket timeout of ContentionTTLDeletions

---

src/workloads/query/GroupSpillToDisk.yml

This must be merged _after_ https://github.com/10gen/mongo/pull/9906. I kicked off a sys-perf patch build incorporating the changes from both repositories here: https://spruce.mongodb.com/version/63cee21da4cf4751fbe848a0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC.
I also ran the workload locally through Genny. Below I've included excerpts of the result summaries generated by running `python src/workloads/contrib/analysis/test_result_summary.py -d <workload output directory>`. First, the results when run against a server started with `./mongod --setParameter internalQueryFrameworkControl="forceClassicEngine"`:
```
GroupAddToSetAccumulatorWithLargeSets.aggregate summary:
timers.dur (measured in nanoseconds, displayed in milliseconds):
count     : 1
average   : 5580.5 …
```

PERF-3480 Enable GroupSpillToDisk.yml on variants where the queries use SBE

---

src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml

We should check for an actual "!!str" value tag. Based on testing I don't think the value of the tag is ever "!".

EVG-18844: Properly handle "!!str" in DocumentGenerator.

---

src/cast_core/src/Loader.cpp
src/workloads/docs/CollectionScanner.yml

This allows us to use 1eN notation instead of 10...00 which is difficult to read of the number of zeros is high

Use IntergerSpec for DocumentCount across Loader actor

---

src/workloads/docs/CollectionScanner.yml
src/workloads/query/ExpressiveQueries.yml

There is a TODO to use multithreading to load documents faster in ExpressiveQueries workload. This now can be fixed using MultipleThreadsPerCollection option.

PERF-3788 Use multi-threading to speed up Loader in ExpressiveQueries workload

---

src/workloads/query/ConstantFoldArithmetic.yml

[sys-perf patch](https://spruce.mongodb.com/version/63f58b7a3627e030e2b040c9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[sys-perf patch 2](https://spruce.mongodb.com/version/63f6fc07d1fe076217d90bf1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[sys-perf patch 3](https://spruce.mongodb.com/version/63f81f6232f417430796575f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
No OOM after 3 runs.

PERF-3517 re-enable ConstantFoldArithmetic

---

src/workloads/docs/ParallelInsert.yml

Decided to `Nop` those w:1 phases instead of removing them due to [EVG-19039](https://jira.mongodb.org/browse/EVG-19039).
[Evergreen build](https://spruce.mongodb.com/task/sys_perf_linux_3_node_replSet_intel.2022_11_parallel_insert_replica_patch_205649df343783082c38ad1790b6b46e3edb7a07_63f7903032f41743079429ea_23_02_23_16_12_21/tests?execution=1&sortBy=STATUS&sortDir=ASC)

PERF-3824: Remove w1 tests from ParallelInsert test

---

src/lamplib/src/genny/tasks/dry_run.py
src/workloads/execution/SinusoidalReadWrites.yml

The patch runs successfully on evergreen, but I'm still working on manually obtaining the intra-run data so we can see the distribution.
In the meantime, I wanted to put this patch up for review to see if we agree on the format.

PERF-3657 Add sinusoidal read/write workload for execution control

---

src/gennylib/include/gennylib/Orchestrator.hpp
src/gennylib/include/gennylib/context.hpp
src/gennylib/src/Orchestrator.cpp
src/gennylib/src/context.cpp

**What:**
The genny portion of the phase event handling. When run with './run-genny' directly, the named pipes are not created so genny does not emit any events. When run under DSI, the named pipes are available so genny writes phase to the out named pipe and waits for an ack from dsi before continuing.
The code addes start and end phase events. These could be trimmed to just a single event type.
The phase number was added as a parameter to the callback because there is already a write lock taken out, so it is not possible to read the phase number through the accessor. Adding the number to the start and stop seems reasonable to me.
**Patches:** 
[updated sys perf patch](https://spruce.mongodb.com/version/64049adb5623436fe78fec71/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
~~[sys …

PERF-3726 external phase coordinator.

---

src/workloads/execution/PingCommand.yml

JIRA Ticket: [PERF-3543](https://jira.mongodb.org/browse/PERF-3543)
Whats changed:
Adding in a new workload that will call the ping command between nodes. The workload runs the command using a rate limit across actors using 2, 4, 8, 16, 32 and 64 threads. Workload is set to auto run for all replica and sharded setups.
Patch Test:
This [patch](https://spruce.mongodb.com/version/63ffa8280305b93ff77552c7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) shows the workload running and reporting the metrics across the various actors. [This](https://spruce.mongodb.com/version/64137ea461837d2961450a33/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) patch shows the workload being picked up by the Genny autorun.

PERF-3543 - Add in PingCommand workload to replace ping canary

---

src/cast_core/src/CommitLatency.cpp

JIRA Ticket: [PERF-3945](https://jira.mongodb.org/browse/PERF-3945)
**Whats changed:**
The ```doc["total"].get_int64()``` raises  ```std::exception``` for some cases which in reality are errors that we wish to track. This change checks for a total field and then extracts the total by bson type.
**Patch Test:**
Legacy 4.4 no flow control [patch](https://spruce.mongodb.com/version/641b1ff032f4172716860d97/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC). This variant has been decommissioned but I'd still like to see if the issue is gone.
Sys Perf [patch](https://spruce.mongodb.com/version/641b275fd6d80adffa250714/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-3945 safely extract data from the aggregation cursor

---

src/workloads/scale/MixedWorkloadsGennyStress.yml

As seen on PERF-3979, this workload is expected to cause slow queries. But on some systems, like M60-like the resulting log file could be up to 35GB in size, making evergreen to fail because of disk space issues or memory exhaustion. This change is to reduce the query logging on this particular workload.

PERF-3988: Reduce slow query logging on mixed_workloads_genny_stress

---

src/workloads/execution/CreateBigIndex.yml
src/workloads/execution/CreateIndex.yml
src/workloads/issues/ConnectionsBuildupNoSharding.yml
src/workloads/networking/ServiceArchitectureWorkloads.yml
src/workloads/query/ExpressiveQueries.yml
src/workloads/query/PipelineUpdate.yml
src/workloads/query/UnionWith.yml
src/workloads/scale/BigUpdate.yml
src/workloads/scale/InsertBigDocs.yml
src/workloads/scale/InsertRemove.yml
src/workloads/scale/LargeScaleLongLived.yml
src/workloads/scale/LoadTest.yml
src/workloads/scale/ManyUpdate.yml
src/workloads/scale/MixedWorkloadsGenny.yml
src/workloads/scale/MixedWorkloadsGennyStress.yml
src/workloads/transactions/LLTMixed.yml
src/workloads/transactions/LLTMixedSmall.yml
src/workloads/transactions/templates/LLTInsertLowLtc.tmpl
src/workloads/transactions/templates/LLTMixedLowLtc.tmpl
src/workloads/transactions/templates/LLTQueryLowLtc.tmpl
src/workloads/transactions/templates/LLTRemoveLowLtc.tmpl
src/workloads/transactions/templates/LLTUpdateLowLtc.tmpl

Change AutoRun so the same tests that run on "atlas" also run on "atlas-like-replica.2022-10". Also changed those scheduled on the old "atlas-like-replica" that is not scheduled anymore so they now run on "atlas-like-replica.2022-10"

PERF-3967: Ensure tests that run against Atlas, also run against Atlas-like

---

src/cast_core/src/CrudActor.cpp
src/workloads/issues/ConnectionPoolStress.yml
src/workloads/scale/Mixed10KThreads.yml

**Jira Ticket:** PERF-4000 (BF-25451 / BF-25038)
_kSwallowAndRecord_ mode was not actually counting errors. Updated the code to addErrors(1) to record the errors so that they can be surfaced in **ErrorsTotal** and **ErrorRate** metrics.
Transient networking error are not necessarily fatal, they can be recoverable. Counting these errors and reporting them rather than raising Exceptions will allow us to monitor and improve stressful networking workloads.
So far,  _ConnectionPoolStress.yml_ and _./src/workloads/scale/Mixed10KThreads.yml_ derived workloads can be changed  (these are highly stressful tests) to count errors rather than cause System Failures (BF-25451 / BF-25038).
[New Behaviour](https://spruce.mongodb.com/version/64302e279ccd4eb0 …

PERF-4000 record swallowed errors

---

src/cast_core/src/Loader.cpp

Since connections on clients in libmongoc are opened lazily, currently the connection time is being counted when we measure time to load initial data. This caused BF-27679 when we updated our infrastructure to have a valid certificate chain, likely due to OpenSSL doing more work to process opening a TLS connection. The recommended fix was to make sure our connections are warm and open before we measure database operation, since that steady state is what we care most about for user operations.
This change pings the database at the beginning of each phase to make sure that we already have an active connection before we time anything. This should bring timings down and reduce noise.

EVG-19133: Pre-warm connection for Loader.cpp.

---

src/gennylib/include/gennylib/conventions.hpp

This Phase range syntax (..) is introduced in [TIG-1202](https://jira.mongodb.org/browse/TIG-1202). The Jira ticket description has a clearer explanation of what this syntax does than in the comment, so I based my revision on that description.

EVG-19298 Clarify what the Phase range syntax (..) does

---

src/workloads/scale/MixedWorkloadsGennyStress.yml

Moved the RunCommand actor to phase0 in order to eliminate the 50th latency regression.

PERF-4060: move runCommand to phase0

---

src/workloads/sharding/WouldChangeOwningShardBatchWrite.yml

:evergreen_tree: https://spruce.mongodb.com/version/64400f713627e0a930a96126/
Manually triggered a `moveRange` (atomic split+move) to distribute chunks in the way the test was originally expecting them.

PERF-3092 Adapt WouldChangeOwningShardBatchWrite workload to data size aware balancing

---

src/phases/tpch/denormalized/Q1.yml
src/phases/tpch/denormalized/Q10.yml
src/phases/tpch/denormalized/Q12.yml
src/phases/tpch/denormalized/Q14.yml
src/phases/tpch/denormalized/Q15.yml
src/phases/tpch/denormalized/Q20.yml
src/phases/tpch/denormalized/Q3.yml
src/phases/tpch/denormalized/Q4.yml
src/phases/tpch/denormalized/Q5.yml
src/phases/tpch/denormalized/Q6.yml
src/phases/tpch/denormalized/Q7.yml
src/phases/tpch/denormalized/Q8.yml
src/phases/tpch/normalized/Q1.yml
src/phases/tpch/normalized/Q10.yml
src/phases/tpch/normalized/Q12.yml
src/phases/tpch/normalized/Q14.yml
src/phases/tpch/normalized/Q15.yml
src/phases/tpch/normalized/Q20.yml
src/phases/tpch/normalized/Q3.yml
src/phases/tpch/normalized/Q4.yml
src/phases/tpch/normalized/Q5.yml
src/phases/tpch/normalized/Q6.yml
src/phases/tpch/normalized/Q7.yml
src/phases/tpch/normalized/Q8.yml

Jira Ticket: PERF-3141
Whats Changed:
Modified TPC-H queries to use the new ^Date syntax to make the queries a bit simpler
Patch testing results:
https://spruce.mongodb.com/version/644225aa2a60ed5c48651f65/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Workload Submission form:
Related PRs:

PERF-3141 Change TPC-H queries to leverage new ^Date syntax

---

src/workloads/docs/ParallelInsert.yml

**Jira Ticket:** [PERF-4044](https://jira.mongodb.org/browse/PERF-4044)
Noop unused dropCollection phases from ParallelInsert
6.0: https://spruce.mongodb.com/version/643e0bcc1e2d17c174086ebd/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=parallel
master: https://spruce.mongodb.com/version/643e0cf37742aed559c852f4/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=parallel

PERF-4044: Noop unused dropCollection phases from ParallelInsert

---

src/workloads/docs/RunCommand-Simple.yml
src/workloads/execution/MultiPlanning.yml
src/workloads/query/AggregateExpressions.yml
src/workloads/query/ArrayTraversal.yml
src/workloads/query/ExpressiveQueries.yml
src/workloads/query/ExternalSort.yml
src/workloads/query/FilterWithComplexLogicalExpression.yml
src/workloads/query/GroupSpillToDisk.yml
src/workloads/query/LookupNLJ.yml
src/workloads/query/LookupSBEPushdown.yml
src/workloads/query/LookupSBEPushdownINLJMisc.yml
src/workloads/query/MatchFilters.yml
src/workloads/query/RepeatedPathTraversal.yml
src/workloads/query/UnionWith.yml
src/workloads/query/VariadicAggregateExpressions.yml
src/workloads/scale/BigUpdate.yml
src/workloads/scale/LargeScaleLongLived.yml

**Jira Ticket:** PERF-4075
More genny tests running on telemetry build variants. For a start, I just looked for all the `standalone-sbe` and ran those. I think this will be good enough until we get to tackling the broader https://jira.mongodb.org/browse/SERVER-74399.
https://spruce.mongodb.com/version/6442c733c9ec44d5e0c18373/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
N/A no new workloads
None for now. Related to https://jira.mongodb.org/browse/SERVER-76083.

PERF-4075 Enable more genny workloads on telemetry variants

---

src/phases/execution/ValidateCmd.yml
src/workloads/execution/ValidateCmdFull.yml

**Jira Ticket:** [PERF-3905](https://jira.mongodb.org/browse/PERF-3905)
Adds a variant of the ValidateCmd.yml workload using full validation.
https://spruce.mongodb.com/version/643fc9b661837d294ec25a45/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-3905 Add validate cmd workload with full option

---

src/lamplib/src/genny/toolchain.py

When I was looking at this file to test my changes to [10gen/vcpkg/evergreen.yml](https://github.com/10gen/vcpkg/blob/master/evergreen.yml), I got confused for a while about how to get the toolchain build ID from the genny-toolchain Evergreen task because 
1) I'm using the new UI while the current example URL is for the old UI and 
2) My change is a patch so the build ID has "patch_" in front of it.
This change is to address these confusions.

Make the example URLs for toolchain build ID more newbie-friendly

---

src/lamplib/src/genny/cli.py

This is to avoid confusion with the "evaluate" CLI command's `evaluate()` function. The new name is chosen to avoid collision with `genny.curator`'s `export()` function.

Rename function for the "export" CLI command

---

src/workloads/query/MatchFilters.yml

Currently, `match_filters` only runs in standalones. We care about these tests and it should run in more variants that actually reflect a release configuration.

PERF-4123 run match_filters in atlas and repl variants

---

src/workloads/sharding/WouldChangeOwningShardBatchWrite.yml

:evergreen_tree: https://spruce.mongodb.com/version/645512fa9ccd4e6dd265581b (ongoing)

PERF-4118 Use split+move rather than moveRange in WouldChangeOwningShardBatchWrite

---

src/phases/query/RunLargeArithmeticOp.yml
src/workloads/query/ConstantFoldArithmetic.yml
src/workloads/query/CumulativeWindows.yml
src/workloads/query/DensifyFillCombo.yml
src/workloads/query/DensifyHours.yml
src/workloads/query/DensifyMilliseconds.yml
src/workloads/query/DensifyMonths.yml
src/workloads/query/DensifyNumeric.yml
src/workloads/query/DensifyTimeseriesCollection.yml
src/workloads/query/FillTimeseriesCollection.yml
src/workloads/query/LookupWithOnlyUnshardedColls.yml
src/workloads/query/MetricSecondaryIndexTimeseriesCollection.yml
src/workloads/query/SlidingWindows.yml
src/workloads/query/TimeSeries2dsphere.yml
src/workloads/query/TimeSeriesSortCompound.yml
src/workloads/query/linearFill.yml
src/workloads/query/locf.yml

**Jira Ticket:** https://jira.mongodb.org/browse/PERF-3784
Use CrudActor instead of RunCommand in query workloads wherever possible
https://spruce.mongodb.com/version/644a348dd6d80a3d5fe390ab/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
na
na

PERF-3784: Replace RunCommand by CrudActor in query workloads

---

src/workloads/query/TelemetryQueryShapes.yml

I think it's good to keep the all feature flags coverage also, but the rest of our comparisons are to the normal "no feature flags" baselines, so this will standardize things more.
https://spruce.mongodb.com/version/645cfb2dc9ec441ab522454b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
https://github.com/10gen/PerformanceReports/pull/91

PERF-4137 Run telemetry workload on standalone also

---

src/cast_core/include/cast_core/actors/CrudActor.hpp
src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActorYamlTests.yml
src/workloads/docs/CrudActorTransaction.yml

**Jira Ticket:** EVG-19821
Added support for Database and Collection fields per Operation in CrudActor, including inside WithTransaction operation.
There are no workloads that use this (yet), but I've added tests to CrudActorYamlTests:
https://spruce.mongodb.com/version/645d00982a60ed3b68c8ef40/tasks
Also added a sys-perf run: https://spruce.mongodb.com/version/645d015ac9ec441ab5225599

EVG-19821 Add ability to override Database and Collection for single operations in CrudActor

---

src/workloads/query/TimeSeriesSortCompound.yml

This was supposed to use a bounded sort, not a blocking sort. See ticket description for more info
In the [design doc](https://docs.google.com/document/d/1d1artozDJUU1WmwHfcViV2BPIaDjns-xcylvPDuHiiI/edit#bookmark=id.edo8gitvzpap) you can see the third row of the example queries shows this query needs a hint to trigger a bounded sort.
[patch](https://spruce.mongodb.com/version/645d317f0ae606ff137a0cc2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-4132 Change TimeSeriesSortCompound.yml to use bounded sort via hint

---

src/lamplib/src/genny/tasks/run_tests.py
src/lamplib/src/genny/toolchain.py

****Jira Ticket:**** EVG-19838
****Whats Changed:****
Currently, for Linux distros, genny sets `triplet_arch` to `arm64` for `amazon2_arm64` only. The code change is: if the distro name ends with `_arm64` (for instance: `ubuntu2204_arm64`) sets `triplet_arch` to `arm64`; otherwise, leave it as `x64`.
In addition to the above, I also added the download link for `ubuntu2204_arm64` into `CANNED_ARTIFACTS`.
****Patch testing results:****
With the following temporary changes
```diff
$ git df
diff --git a/src/lamplib/src/genny/toolchain.py b/src/lamplib/src/genny/toolchain.py
index 16a2b276..a25d00e6 100644
--- a/src/lamplib/src/genny/toolchain.py
+++ b/src/lamplib/src/genny/toolchain.py
@@ -239,7 +239,7 @@ class ToolchainDownloader(Downloader):
else:
prefix = "macos_1100"
else:
- …
```

EVG-19838 Set cpu arch based on linux_distro name

---

src/lamplib/src/genny/tasks/run_tests.py
src/lamplib/src/genny/toolchain.py

****Jira Ticket:**** EVG-19833
****Whats Changed:****
Update TOOLCHAIN\_BUILD\_ID to one that builds the toolchain for ubuntu2204 amd64 and arm64.
****Patch testing results:****
The following genny cmake-test and resmoke-test succeeded on ubuntu2204 x86\_64:
```text
sudo mkdir -p /data/db
sudo chown ${whoami}:${whoami} /data/db
./run-genny clean
./run-genny create-new-actor HelloWorldActor
sed -i '/program_executable/s!:.*$!: ../../build/src/cast_core/cast_core_test!' ./src/resmokeconfig/genny_single_node_replset.yml
sed -i '/REQUIRE(count == 101)/s/101/100/' ./src/cast_core/test/HelloWorldActor_test.cpp
./run-genny install -d ubuntu2204
./run-genny cmake-test
./run-genny resmoke-test --suites ../../src/resmokeconfig/genny_single_node_replset.yml
```

EVG-19833 Update TOOLCHAIN_BUILD_ID to avail ubuntu2204 toolchains and add mongod ubuntu2204 download link

---

docs/developing.md
src/lamplib/src/genny/tasks/create-new-actor.sh
src/lamplib/src/genny/tasks/run_tests.py

Currently, the code to implement resmoke-test assumes that it will be run by Evergreen. Therefore, to run resmoke-test locally, some modifications must be made. This PR is to add the commands to make these modifications.
I've thought about creating a script to automatically run these commands, but the root cause of why we have to use these commands is fundamentally a bug in Genny ([EVG-18189](https://jira.mongodb.org/browse/EVG-18189)), so that script would just be papering over this bug.

EVG-18380 - Add instructions for running resmoke-test locally

---

src/workloads/serverless/IndexStress.yml

**Jira Ticket:** 
[CLOUDP-177869](https://jira.mongodb.org/browse/CLOUDP-177869)
**Changes:**  
- Adds a 20-minute waiting phase after the workload runs to allow all scaling events to complete before the end of the test. See the comments on [CLOUDP-168645](https://jira.mongodb.org/browse/CLOUDP-168645) for an explanation of why this is necessary.  
Successful patch test run: https://spruce.mongodb.com/task/sys_perf_mms_atlas_serverless_serverless_index_stress_genny_workload_ten_instances_patch_e676d70f3c84f496cb5f5734e7693a59344a727f_6467daa061837d86a6fb02e9_23_05_19_20_23_36/tests?execution=0&sortBy=STATUS&sortDir=ASC

CLOUDP-177869: Add a sleeping period after the workload runs in the serverless_index_stress_genny_workload_ten_instances task

---

evergreen.yml

Now that Genny supports Ubuntu 22.04, and that Ubuntu 22.04 is the recommended distro for Evergreen workstations, we should add the Evergreen build for this distro as well. Given how we don't run Genny patches that often, this should not bump infra cost much.

Add Evergreen build for Ubuntu 22.04

---

src/workloads/scale/ManyUpdate.yml

**Jira Ticket:** PERF-4131
Changed "Options" to "OperationOptions" when setting write concern
[If applicable, link a patch test showing code changes running successfully
](https://spruce.mongodb.com/task/sys_perf_linux_3_node_replSet.2022_11_many_update_patch_2c11ff69a7c7c475d2c356fc184a2ccffccdfc15_6467bd0c9ccd4eb3dff7c058_23_05_19_18_27_14/tests?execution=0&sortBy=STATUS&sortDir=ASC)
But there is a catch:  I still get the YAML Usage warning message.  Which is also there for /Filter at the same level.  I am not sure if this is a problem with the Usage warning or the workload is still broken.  It looks right based on …

PERF-4131 Use the correct options name for write concern

---

src/workloads/contrib/analysis/test_result_summary.py
src/workloads/query/QueryStats.yml

**Jira Ticket:** PERF-4191 
I ran a profiled patch build and found this strange result:
We are spending almost all our time doing the queries! Then I noticed that our index spec didn't evolve to match our queries as we changed the way we generate our queries.
Launched one here: https://spruce.mongodb.com/version/646cd0ec9ccd4e2267dbc7d2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-4191 Fix Data/Index to match query shapes

---

src/workloads/docs/RunCommand-Simple.yml
src/workloads/execution/MultiPlanning.yml
src/workloads/query/AggregateExpressions.yml
src/workloads/query/ArrayTraversal.yml
src/workloads/query/ConstantFoldArithmetic.yml
src/workloads/query/ExpressiveQueries.yml
src/workloads/query/ExternalSort.yml
src/workloads/query/FilterWithComplexLogicalExpression.yml
src/workloads/query/GraphLookupWithOnlyUnshardedColls.yml
src/workloads/query/GroupSpillToDisk.yml
src/workloads/query/LookupNLJ.yml
src/workloads/query/LookupSBEPushdown.yml
src/workloads/query/LookupSBEPushdownINLJMisc.yml
src/workloads/query/LookupWithOnlyUnshardedColls.yml
src/workloads/query/MatchFilters.yml
src/workloads/query/PercentilesAgg.yml
src/workloads/query/PercentilesExpr.yml
src/workloads/query/PercentilesWindow.yml
src/workloads/query/PercentilesWindowSpillToDisk.yml
src/workloads/query/RepeatedPathTraversal.yml
src/workloads/query/UnionWith.yml
src/workloads/query/VariadicAggregateExpressions.yml
src/workloads/scale/BigUpdate.yml
src/workloads/scale/LargeIndexedIns.yml
src/workloads/scale/LargeScaleLongLived.yml
src/workloads/scale/MajorityReads10KThreads.yml
src/workloads/scale/MixedWorkloadsGenny.yml
src/workloads/scale/MixedWorkloadsGennyRateLimited.yml
src/workloads/scale/ScanWithLongLived.yml
src/workloads/transactions/LLTMixed.yml

**Jira Ticket:** PERF-4050
Allow Genny workload to run with Bonsai Heuristic variant
https://spruce.mongodb.com/version/646e04fbe3c331718d4d831a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
DSI: https://github.com/10gen/dsi/pull/1289

PERF-4050 Allow heuristic Bonsai variants to run auto Genny workloads

---

src/gennylib/src/PoolFactory.cpp
src/gennylib/test/PoolFactory_test.cpp

**Jira Ticket:** EVG-19731
**Whats Changed:** Redact password in MongoDB URI logging.
Patch Run:
https://spruce.mongodb.com/task/sys_perf_atlas_M60_atlas_repl_big_update_patch_cd1cfc52029ccfba3214f22b8dcb5b09848df5f3_646f29c49ccd4e17993b29c9_23_05_25_09_29_05/logs?execution=1&sortBy=STATUS&sortDir=ASC
Redacted log line outputted by Genny:
https://parsley.mongodb.com/evergreen/sys_perf_atlas_M60_atlas_repl_big_update_patch_cd1cfc52029ccfba3214f22b8dcb5b09848df5f3_646f29c49ccd4e17993b29c9_23_05_25_09_29_05/1/task?bookmarks=0,2488,4678&shareLine=2488
**Related PRs:** https://github.com/10gen/dsi/pull/1286

EVG-19731 - Redact password in MongoDB URI logging

---

src/workloads/execution/CreateIndexSharded.yml
src/workloads/scale/InsertRemove.yml
src/workloads/scale/LargeScaleLongLived.yml
src/workloads/sharding/MultiShardTransactions.yml
src/workloads/sharding/ReshardCollectionMixed.yml
src/workloads/sharding/ReshardCollectionReadHeavy.yml
src/workloads/sharding/WouldChangeOwningShardBatchWrite.yml

**Jira Ticket:** PERF-4181
Added a AutoRun hook that runs workloads with Linux-3-Shard heuristic Bonsai build variant.
https://spruce.mongodb.com/version/6470c5da9ccd4eb12fc1ecf8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
https://github.com/10gen/mongo/pull/13216
https://github.com/10gen/dsi/pull/1293

PERF-4181 Enable relevant Genny workloads on the heuristic Bonsai 3-Shard variant

---

docs/using.md
src/cast_python/src/mongosync_actor.py
src/lamplib/src/genny/cli.py
src/lamplib/src/genny/curator.py
src/lamplib/src/genny/tasks/compile.py
src/lamplib/src/genny/tasks/preprocess.py

**Whats Changed:** 
This is to batch some miscellaneous fixes into one PR:
- Reformatting by linter after running `./run-genny lint-python --fix`. The modified files are `src/cast_python/src/mongosync_actor.py` and `src/lamplib/src/genny/tasks/compile.py`.
- Fix type error where `parent` is not a member of `str` (it's a member of `Path`) & add type annotations in `src/lamplib/src/genny/tasks/preprocess.py`
- Fix [incomplete refactoring in PR #515](https://github.com/mongodb/genny/pull/515/files#diff-c9ee5569fee04a5bd776c8b46b7c03abe31617d0116cd4ed7cd4983f2c4ef72aL316-L319) in `src/lamplib/src/genny/tasks/preprocess.py`

Miscellaneous fixes in Genny

---

src/workloads/scale/CreateDropView.yml

**Jira Ticket:** BF-28934
added the logging actor into the create_drop_view workload that prevents tasks from failing if they are silent for too long
[If applicable, link a patch test showing code changes running successfully](https://spruce.mongodb.com/version/648080603e8e8694bce2a40a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

Fix for BF-28934

---

src/workloads/scale/BigUpdate.yml
src/workloads/scale/LargeScaleLongLived.yml
src/workloads/scale/LoadTest.yml

**Jira Ticket:** [PERF-4143](https://jira.mongodb.org/browse/PERF-4143)
**What's Changed:**  
Not running certain workloads on small atlas variants
[Patch test](https://spruce.mongodb.com/version/64820a2a0305b94151f6b4c3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC). 
Separate fix for mixed_genny_workloads
Mixed genny failure fixed [here](https://github.com/10gen/dsi/pull/1313).

PERF-4143: Not running some workloads on small atlas variants

---

evergreen.yml
src/gennylib/test/PhaseLoop_test.cpp
src/lamplib/src/genny/cli.py
src/lamplib/src/genny/tasks/run_tests.py

**Jira Ticket:** [EVG-19909](https://jira.mongodb.org/browse/EVG-19909)  
-   Split the test case "Actual Actor Example" to "Actual Actor Example" and  
"Actual Actor Example Timing"
-   Modify 'run-genny cmake-test' to accept the option '&#x2013;regex-exclude'
-   Modify 'evergreen.yml' run cmake-test on macOS with '&#x2013;regex-exclude'
At the moment, the `f_cmake_test_ignore_flaky` function runs cmake-test with  
`--regex-exclude` to skip timing/random number related tests which are known to  
fail on macOS. In the future, should more such tests are discovered, please skip  
them similarly.  
<https://spruce.mongodb.com/version/6492ab750ae6065cd41edb29/tasks>  
<https://spruce.mongodb.com/version/649a474457e85a45efc31d70/tasks> …

EVG-19909 Run cmake-test on macOS but skip flaky tests

---

src/workloads/execution/CreateBigIndex.yml
src/workloads/execution/CreateIndex.yml
src/workloads/networking/ServiceArchitectureWorkloads.yml
src/workloads/query/ExpressiveQueries.yml
src/workloads/query/MatchFilters.yml
src/workloads/query/PipelineUpdate.yml
src/workloads/query/UnionWith.yml
src/workloads/scale/BigUpdate.yml
src/workloads/scale/InsertBigDocs.yml
src/workloads/scale/InsertRemove.yml
src/workloads/scale/LargeScaleLongLived.yml
src/workloads/scale/ManyUpdate.yml
src/workloads/scale/MixedWorkloadsGenny.yml
src/workloads/scale/MixedWorkloadsGennyStress.yml
src/workloads/scale/MixedWorkloadsGennyStressWithScans.yml

On SERVER-69824 we are going to enable M30 on sys perf, but we need to disable the genny workloads so it only runs industry_benchmarks, tpcc, and linkbench2. This ticket is to disable those workloads.

PERF-4338: Disable genny tasks on M30 Atlas

---

src/workloads/networking/CommitLatency.yml

**Jira Ticket:** [PERF-2932](https://jira.mongodb.org/browse/PERF-2932)
We have added in 4 new phases to the commit latency workload to cover testing of the "available" ReadConcern option. We are testing this with W:1, W:0, journaling and readMode as primary and secondary.
A successful patch can be found here:
https://spruce.mongodb.com/version/649b294ad1fe07b787b40405/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

[PERF-2932] - Commit latency updates to include ReadConcern "Available"

---

evergreen.yml
src/gennylib/test/PhaseLoop_test.cpp

**Jira Ticket:** EVG-19909
Rename "Acutual Actor Example Timing" to "Actual Actor Example IgnoredOnMacOS"
**Patch testing results:** 
<https://spruce.mongodb.com/version/649ba6b70ae606acbdb6af22/tasks>

EVG-19909 Rename "Acutual Actor Example Timing" to "Actual Actor Example IgnoredOnMacOS"

---

src/lamplib/requirements.txt

**Jira Ticket:** [EVG-19923](https://jira.mongodb.org/browse/EVG-19923)
Update Genny dependencies flagged by Dependabot [here](https://github.com/mongodb/genny/security/dependabot).
- [sys-perf](https://spruce.mongodb.com/version/649942a70ae606c012941377/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
https://github.com/10gen/dsi/pull/1318

EVG-19923: Update Genny dependencies flagged by Dependabot

---

src/lamplib/requirements.txt
src/lamplib/src/genny/tasks/run_tests.py

**Jira Ticket:** [EVG-20471](https://jira.mongodb.org/browse/EVG-20471)
This PR fixes an issue with Genny where the explicitly defined version of PyYAML is incompatible with the implicitly installed Cython 3.0 dependency. They are [not](https://github.com/yaml/pyyaml/issues/601) compatible. PyYAML is being downgraded to 5.3.1 instead of being upgraded to 6.0.1 because I ran into some transitive dependency issues still requiring PyYAML ~5.
Because Genny, during its own testing, pulls in an additional `requirements.txt` from Mongo, defined [here](https://github.com/mongodb/mongo/blob/master/etc/pip/components/core.req#L4) I have additionally added a pre-install step, hopefully causing `pip`'s resolver to not try and upgrade PyYAML or Cython.
The [sys-perf …

EVG-20471 - Downgrade PyYAML to fixed version compatible with Cython 3.0

---

src/workloads/query/QueryStats.yml

Through https://jira.mongodb.org/browse/BF-29351 we realized that when calling $queryStats here https://github.com/mongodb/genny/blob/master/src/workloads/query/QueryStats.yml#L48 we are not getting all the entries, so there seemed to be a performance improvement since one partition is now smaller so quicker to read out. This fixes the workload to iterate through all the query stats entries.
https://spruce.mongodb.com/version/64b99103d6d80a0f834be0e0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Compared this new version to the patch from the BF and now results are more similar to before: 
https://performance-analyzer.server-tig.prod.corp.mongodb.com/perf-analyzer-viz/?comparison_id=286b4dc3-8814-448a-aac3-97abfab4b13e&percent_filter=0%7C%7C100&z_filter=0%7C%7C10

PERF-4436: Update $queryStats to Exhaust Cursor in QueryStats.yml Genny Workload

---

src/cast_core/src/CrudActor.cpp
src/cast_core/test/CrudActorYamlTests.yml

**Jira Ticket:** EVG-20421
Add the "Options" keyword to CrudActor's "insertMany" operation. This would enable "insertMany" to support setting [insert options](https://www.mongodb.com/docs/manual/reference/command/insert/#syntax) via MongoDB C++ Driver's [`mongocxx::options::insert`](http://mongocxx.org/api/mongocxx-v3/classmongocxx_1_1options_1_1insert.html). These options include "WriteConcern", "Ordered", and "BypassDocumentValidation".
- sys-perf's [background_ttl_deletions](https://spruce.mongodb.com/task/sys_perf_linux_standalone_all_feature_flags.2022_11_background_ttl_deletions_patch_ccf65577c26aaa1ba825a587aaf5834c37eaf9bd_64b7817d1e2d17b64ec17388_23_07_19_06_24_48/logs?execution=0) (which uses insertMany). There is [no performance …

EVG-20421: Add "Options" to insertMany in CrudActor

---

src/workloads/execution/ClusteredCollection.yml
src/workloads/execution/ClusteredCollectionLargeRecordIds.yml
src/workloads/query/OneMDocCollection_LargeDocIntId.yml
src/workloads/query/TenMDocCollection_IntId.yml
src/workloads/query/TenMDocCollection_ObjectId.yml
src/workloads/query/TenMDocCollection_SubDocId.yml

We recently added variants for `shard-limited-query-stats`, `shard-lite-query-stats`, and `shard-lite-limited-query-stats`. This patch includes those variants to be run on workloads relevant to query stats.
[Evergreen link](https://spruce.mongodb.com/version/64c2901a32f4179811ce7a32/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-4463: Include more sharded variants on query stats workloads

---

src/phases/replication/startup/StartupPhasesTemplate.yml
src/workloads/replication/startup/1_0_5GB.yml
src/workloads/replication/startup/1_1_5GB_crud.yml
src/workloads/replication/startup/1_2_5GB_ddl.yml
src/workloads/replication/startup/1_3_5GB_index.yml
src/workloads/replication/startup/2_0_50GB.yml
src/workloads/replication/startup/2_1_50GB_crud.yml
src/workloads/replication/startup/2_2_50GB_ddl.yml
src/workloads/replication/startup/2_3_50GB_index.yml
src/workloads/replication/startup/3_0_Reads.yml
src/workloads/replication/startup/README.md

Jira Ticket: < [PERF-4076](https://jira.mongodb.org/browse/PERF-4076) >
Whats Changed:
Create performance benchmark for server startup and shutdown
Patch testing results:
[Patch1](https://spruce.mongodb.com/version/64c11835d1fe0740ac80cf02/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[Patch2](https://spruce.mongodb.com/version/64c1184161837db62cfb9a93/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[Patch3](https://spruce.mongodb.com/version/64c1185b2fbabe72a9517f34/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
Related PRs:
[Mongo](https://github.com/10gen/mongo/pull/14458)
[DSI](https://github.com/10gen/dsi/pull/1357)

PERF-4076 Create performance benchmark for server startup and shutdown

---

src/value_generators/include/value_generators/DocumentGenerator.hpp
src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocGenYamlTestCaseRunner.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml

**Jira Ticket:** PERF-4478
Add the `DistinctArray` generator, which is essentially a set, but as an array with no duplicate values. Unlike `Array`, `DistinctArray` operates solely on homogeneous array values.
Also implements a refactor for the parsers maps to deduplicate maps and hedge against the risk of accidentally leaving a parser off of `allParsers`.
If applicable, link a patch test showing code changes running successfully (TBD)

PERF-4478 Generator for an array of distinct values

---

src/lamplib/src/genny/tasks/preprocess.py
src/lamplib/src/tests/test_preprocess.py

**Jira Ticket:** PERF-4517
Implement the `^FlattenArray` key, which reduces the dimensionality of an array by 1. For example:
- `[1, 2, 3, 4, 5, 6, 7, 8, 9]` -> `[1, 2, 3, 4, 5, 6, 7, 8, 9]`
- `[[1, 2, 3], 4, 5, 6, [7, [8, 9]]]` -> `[1, 2, 3, 4, 5, 6, 7, [8, 9]]`
- `"123456789"` -> `[1, 2, 3, 4, 5, 6, 7, 8, 9]`

PERF-4517 Implement Genny preprocessor key FlattenArray

---

evergreen.yml

**Jira Ticket:** PERF-4520
Update name of Evergreen build variant from "Bug Sur arm64" to "Big Sur arm64"

PERF-4520 Correct spelling of Evergreen variant for Big Sur arm64

---

src/workloads/query/OneMDocCollection_LargeDocIntId.yml
src/workloads/query/TenMDocCollection_IntId.yml
src/workloads/query/TenMDocCollection_ObjectId.yml
src/workloads/query/TenMDocCollection_SubDocId.yml

When investigating PERF results from the IDHACK workloads, it often takes many days of repeated runs for the results to stabilize and remove significant noise. By having the workloads run for 5 minutes instead of 30 seconds, we'll be able to narrow down if noise is coming from the find commands, or the hardware, or something else. This hopefully will also help the results stabilize sooner.
[Evergreen patch](https://spruce.mongodb.com/version/64d26292562343c2b650cc05/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-4523: Have IDHACK workloads run for 5 minutes instead of 30 seconds

---

src/workloads/query/FilterWithComplexLogicalExpression.yml

**Jira Ticket:** <PERF-4500 >
Added a rooted $or query workload
https://spruce.mongodb.com/version/64d396482a60edf3c60b212e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-4500 Create a rooted $or workload that can be affected by the change of the default enumeration strategy

---

docs/using.md

**Jira Ticket:** PERF-4538
Fix typo of `test_result_summary.py` in the genny docs.

PERF-4538 Fix name of python result summary script in docs

---

docs/using.md
src/lamplib/src/genny/tasks/preprocess.py
src/lamplib/src/tests/test_preprocess.py
src/workloads/docs/HelloWorld.yml

**Jira Ticket:** PERF-4516
Add `^FormatString` as a preprocessor key. It mimics the `^FormatString` value generator. If `^FormatString` fails at the preprocess step, it'll ignore the failure and let the value generator version of `^FormatString` handle it.

PERF-4516 Implement Genny preprocessor key FormatString

---

src/workloads/sharding/ReshardCollectionWithIndexes.yml

**Jira Ticket:** [PERF-4225](https://jira.mongodb.org/browse/PERF-4225)
Add a workload for resharding with 10 indexes
[Patch](https://spruce.mongodb.com/version/64cbcb7ca4cf47bf54dbdcc6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC). The patch hasn't run successfully due to lack of available instance and long sys-perf queue.
[Form](https://docs.google.com/forms/d/e/1FAIpQLSf1oh23Ddo1khjLZMqZ9DHbRdObnpeH20PSXTBuXVg-7mxxTA/viewform?edit2=2_ABaOnueG5Z-djqaIYwlIPrAzY5kbAC7mtqj-G6FpcajAukgf6ir-0hH56oObruNBoF3PxXI)
[dsi](https://github.com/10gen/dsi/pull/1369) …

PERF-4225 add a workload to test resharding performance with indexes

---

src/phases/query/IDHack.yml
src/workloads/query/TenMDocCollection_ObjectId.yml
src/workloads/query/TenMDocCollection_ObjectId_Sharded.yml

Added an IDHack workload on a sharded collection. Since much of the logic is shared with the existing `TenMDocCollection_ObjectId` workload, I factored some of the shared templates into `src/phases/query/IDHack.yml`.
[Evergreen patch](https://spruce.mongodb.com/version/64db88347742ae0c65d8a85e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-4546: Add sharded IDHACK to Genny workloads

---

src/cast_core/src/MoveRandomChunkToRandomShard.cpp
src/cast_core/src/RollingCollections.cpp
src/cast_core/test/CrudActorYamlTestRunner.cpp
src/cast_core/test/MoveRandomChunkToRandomShard_test.cpp
src/cast_core/test/MultiCollectionQuery_test.cpp
src/gennylib/src/quiesce.cpp
src/gennylib/src/topology.cpp
src/gennylib/test/encryption_test.cpp
src/testlib/include/testlib/helpers.hpp
src/value_generators/src/DocumentGenerator.cpp

**Jira Ticket:** EVG-20548
Replace bsoncxx's `get_utf8()` with its `get_string()` as the former has been deprecated generates lots of noises during compilation.
****Patch testing results:****
The following patches were run and the `get_utf8()` related deprecation errors disappeared.
-   [a full genny patch test](https://spruce.mongodb.com/version/64d1e7e8d1fe07a79f5fcdea/tasks)
-   [a sys-perf patch task](https://spruce.mongodb.com/task/sys_perf_linux_1_node_replSet.2022_11_insert_remove_patch_b15e8edd21f3249f71cd28f570a4d9c3a9bd734e_64d57235d6d80a0b4adcc766_23_08_11_00_01_35/tests?execution=0&sortBy=STATUS&sortDir=ASC)

EVG-20548 replace 'get_utf8()' to avoid deprecation warnings

---

src/phases/query/IDHack.yml
src/workloads/query/OneMDocCollection_LargeDocIntId.yml
src/workloads/query/TenMDocCollection_IntId.yml
src/workloads/query/TenMDocCollection_SubDocId.yml

[lil evg patch](https://spruce.mongodb.com/version/64e761ca9ccd4ed58281782c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-4589: Have IDHack workloads run for 100 seconds

---

src/cast_core/src/CrudActor.cpp
src/workloads/scale/BulkLoading.yml

This workload tests the performance of the bulkWrite API and compares it to normal writes.
It is modeled as a collection of sensor data. It would be common for this use case to do batching using, e.g., AWS SQS.
It tests the following scenarios:
- BulkWrite API, ~30GB data in the db, single connection, no index
- BulkWrite API, ~30GB data in the db, single connection, with index
- BulkWrite API, ~30GB data in the db, many connections, no index
- BulkWrite API, ~30GB data in the db, many connections, with index
- normal writes, ~30GB data in the db, many connections, no index
- normal writes, ~30GB data in the db, many connections, with index
- BulkWrite Upserts, ~30GB data in the db, many connections, with index
Note: This workload requires the fix from PERF-4583, but wanted to get some …

PERF-4368 Create a 'bulk-loading' workload

---

src/cast_core/src/CrudActor.cpp

The bulk write operation allows setting some properties, such as WriteConcern at the top level instead of for each child-operation within the bulk write:
http://mongocxx.org/api/current/classmongocxx_1_1options_1_1bulk__write.html
Some properties can only be set on the child level, such as upsert:
http://mongocxx.org/api/current/classmongocxx_1_1model_1_1update__one.html 
However, Genny currently ignores the properties of child operations when constructing the model, which makes it impossible to, e.g., set upsert for bulk operations.
This PR uses all OperationOptions that are set for a child-operation when creating the operation model, which is used to construct the bulk operation. 
Aside from making it possible to set these values for bulk operations in the first place, this PR also …

PERF-4583 - Enable setting child-operation properties for BulkWrites

---

src/workloads/query/ExpressiveQueries.yml
src/workloads/scale/LargeIndexedIns.yml
src/workloads/scale/LoadTest.yml
src/workloads/scale/MajorityReads10KThreads.yml
src/workloads/scale/MixedWorkloadsGennyRateLimited.yml

Added the high value workloads to auto run on query stats replica variant
[Evergreen patch](https://spruce.mongodb.com/version/64ed06992a60ed5dc07cb9e9/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

SERVER-80476: Add High Value Workloads to Perf Dashboard

---

src/canaries/src/Loops.cpp

**Jira Ticket:** EVG-20067
The root cause of this ticket is that genny-canaries was missing timing code for arm64 and variants other than Mac & x86-64. This PR is to add timing code for arm64 and variants other than Mac & x86-64.
It is expected that this PR will trigger change points because it would fix the genny-canaries time series for ARM variants.
The new arm64 timing code, like the existing Mac & x86-64 timing code, adapted [Apache-2.0 licensed code](https://github.com/google/benchmark/blob/main/LICENSE) from [google/benchmark](https://github.com/google/benchmark/blob/8f7b8dd9a3211e6043e742a383ccb35eb810829f/src/cycleclock.h#L142-L149), which utilizes assembly code or platform-specific code. Specifically, google/benchmark's [arm64 timing …

EVG-20067: Add genny-canaries timing code for arm64 and variants other than Mac & x86-64

---

src/workloads/query/LookupColocatedData.yml

This patch fixes a typo in the let + pipeline `$lookup` queries. The definition of the let is an expressions, so it must be dollar-prefixed, not a simple string.
Here's the [patch test ](https://spruce.mongodb.com/version/64f221ce850e6109ef514751/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)and corresponding [perf analysis](https://performance-analyzer.server-tig.prod.corp.mongodb.com/perf-analyzer-viz/?comparison_id=2bd51a4a-eaab-43a9-bffa-83e424dd20de&task_filter=lookup_colocated_data&measurement_filter=Latency50thPercentile&determination_filter=Improved&determination_filter=Regressed&percent_filter=0%7C%7C100&z_filter=0%7C%7C10). 
As I would expect, most `*LetPipeline*` queries get slower because they are matching documents, whereas before they were not matching any. There is one …

PERF-4656: Add dollar prefix to colocated $lookup let field

---

src/workloads/query/FilterWithComplexLogicalExpression.yml
src/workloads/query/MatchWithLargeExpression.yml

**Jira Ticket:** PERF-4637
A new workload was added to test the performance of expression search for parameter re-use during parameterization.
https://spruce.mongodb.com/version/64f07cbb1e2d170ed4b21ff3/tasks
Submitted
[SERVER-79092](https://github.com/10gen/mongo/pull/15219)

PERF-4637 Create a workload that can be affected by the optimization to expression search for parameter reuse

---

src/workloads/query/TimeseriesCount.yml
src/workloads/query/TimeseriesFixedBucketing.yml

**Jira Ticket:** PERF-4312
2 new workloads were added. One is to exercise the $count optimization that was added in the fixed bucketing project. One is to measure the performance improvements of the fixed bucketing $dateTrunc optimization that was added. 
[Patch link](https://spruce.mongodb.com/version/64efb3df2fbabe81fc81b11f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[Patch with new variants added](https://spruce.mongodb.com/version/64f739453627e06217b48cd2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
If applicable, only required if there is a new workload being added. Form can …

PERF-4312 Add genny workloads for fixed bucketing and count optimizations for timeseries

---

src/lamplib/requirements.txt
src/lamplib/src/genny/cli.py
src/lamplib/src/genny/tasks/auto_tasks.py
src/lamplib/src/genny/tasks/auto_tasks_all.py
src/lamplib/src/tests/test_auto_tasks.py
src/lamplib/src/tests/test_auto_tasks_all.py

**Jira Ticket:** [EVG-17874](https://jira.mongodb.org/browse/EVG-17874)
This is a draft PR for switching to having a single task generation task for all the variants in Genny. The advantage of this is that generated tasks will be scheduled only when other variant tasks are scheduled, but will also always be available to run on any waterfall build, allowing individual tasks to be run. 
This change also makes it possible to generate tasks in a patch build without running all of them, in case there is a specific generated task that needs to be run.
See https://github.com/mongodb/mongo/blob/EVG-17874-taskgen-test/etc/system_perf_taskgen_test.yml#L455 …

EVG-17874: Generate all tasks

---

src/workloads/streams/CurrencyConversion.yml
src/workloads/streams/HighestBid.yml
src/workloads/streams/Selection.yml
src/workloads/streams/UrlAggregation.yml
src/workloads/streams/YahooBenchmark.yml

**Jira Ticket:** BF-30108
Fixing existing streaming workloads after a breaking change with the in-memory source operator went out.
https://spruce.mongodb.com/version/650dbe26306615d63c508d35/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

BF-30108: [streams] fix workloads

---

src/cast_core/include/cast_core/actors/StreamStatsReporter.hpp
src/cast_core/src/StreamStatsReporter.cpp
src/cast_core/test/StreamStatsReporter_test.cpp
src/workloads/contrib/analysis/test_result_summary.py
src/workloads/docs/StreamStatsReporter.yml
src/workloads/streams/HighestBid.yml
src/workloads/streams/InsertBidsTemplate.yml
src/workloads/streams/Selection.yml
src/workloads/streams/UrlAggregation.yml
src/workloads/streams/YahooBenchmark.yml

**Jira Ticket:** [SERVER-81260](https://jira.mongodb.org/browse/SERVER-81260)
Introducing a new actor that periodically polls metrics from a mongo streams instance and records the throughput metrics returned in the genny operation metrics. The actor doesn't exit until the conditional expected document count is met. We need this because stream processing is asynchronous, so the best way to measure throughput here is pulling output throughput metrics from the stream process itself.

SERVER-81260: custom throughput reporter for streams

---

evergreen.yml
src/lamplib/src/genny/cli.py
src/lamplib/src/genny/tasks/compile.py

If a distro is not specified, we should be able to autodetect it given the finite number of actual configurations we support.
**Jira Ticket:** EVG-17757
Autodetects the value to use for distro if it is not specified
[This patch](https://spruce.mongodb.com/version/65147562d1fe074855e94159/tasks) shows all the compile tasks running successfully without the distro set

EVG-17757: Add function to autodetect distro.

---

src/lamplib/src/genny/tasks/auto_tasks.py
src/lamplib/src/tests/test_auto_tasks.py

**Jira Ticket:** EVG-20906
Use the correct variable when warning about task generation

EVG-20906: Don't reference undefined variable.

---

src/lamplib/src/genny/tasks/preprocess.py
src/lamplib/src/tests/test_preprocess.py

**Jira Ticket:** [SERVER-81260](https://jira.mongodb.org/browse/SERVER-81260?filter=-1)
Support `^ClientURI` replacement which will replace any instances of `^ClientURI` with the corresponding registered client's URI. The plan is to use this for streams in DSI and have a streams instance create a source operator that consumes a change stream from a mongo VM within the same DSI VPC. But in order for that to work, I need the client URI to be exposed.
Unfortunately the `URI` for each client will be populated during preprocess time in genny `preprocess.py` so the `URI` is not known pre-compile time so we can't anchor/reference the `URI`.
e.g.
``` …
```

SERVER-81260: support ^ClientURI in preprocessing

---

src/cast_core/src/QuiesceActor.cpp

**Jira Ticket:** EVG-20698
QuiesceActor uses Topology, which needs to access cluster members directly. Currently, the URIs for the members are constructed using "protocol://member_fqdn:port", where protocol is either "mongodb" or "mongodb+srv". When "mongodb+srv" is used (for Atlas related tests), the resulted URIs are invalid because mongodb+srv shall not include port numbers.
This change is to report the error during QuiesceAcor initialization (in the constructor) so that:
- The users understand what the issue is.
- Tests with wrong mongo URIs (i.e. the srv ones)  fail at the beginning *not* when QuiesceActor actually start to work.
None

EVG-20698 QuiesceActor reports error if srv mongodb uri is in use.

---

docs/setup.md

**Jira Ticket:** EVG-19799
Temporary measure while waiting for snappy to be added to Genny toolchain.

[doc] snappy must be installed manually on Mac

---

src/gennylib/include/gennylib/Node.hpp

**Jira Ticket:** EVG-20582
If an `actor::PhaseConfig` tries to `getPlural` from a Sequence, report an error message which is different from the default `InvalidKeyException` message. Hopefully this helps users to understand the error better.
I've run local tests using the configuration with the configuration files mentioned in the ticket EVG-20582.
Originally, the error message is this:
```text
Invalid key 'getPlural('Operation', 'Operations')': Either 'Operation' or 'Operations' required. On node with path
'/Users/lungang.fang/source/genny/build/WorkloadOutput/workload/test.yml/Actors/0/Phases/0': - Repeat: 1
Database: test
Operations:
OperationName: RunCommand
OperationCommand:
create: Collection0
timeseries:
timeField: t
metaField: sensorId …
```

EVG-20582: Error message for running getPlural for a Sequence node

---

src/workloads/sharding/MultiShardTransactionsWithManyNamespaces.yml

**Jira Ticket:** 
https://jira.mongodb.org/browse/PERF-4788
Disabling MultiShardTransactionsWithManyNamespaces workload for shard-heuristic-bonsai setup
* Evergreen patch with task running: https://spruce.mongodb.com/version/65325a810ae606cf1b971138/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
* Evergreen with task not running: https://spruce.mongodb.com/version/65325d01d6d80a0fa49da972/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-4788 Disable MultiShardTransactions for shard-heuristic-bonsai setup

---

src/workloads/streams/LargeTumblingWindow.yml

**Jira Ticket:** SERVER-82372
Lower the input document count for LargeTumblingWindow.yml to reduce change of OOM. This is hugging pretty close to the max RSS so occasionally leads to an OOM.

SERVER-82372: [streams] lower LargeTumblingWindow workload doc count

---

src/workloads/query/ArrayTraversal.yml
src/workloads/query/FilterWithComplexLogicalExpression.yml

**Jira Ticket:** [PERF-4685](https://jira.mongodb.org/browse/PERF-4695)
- The Genny workloads filter_with_complex_logical_expression and array_traversal will now run on the 3-Node ReplSet variants.
- There was some discussion between query and performance regarding whether the high-value CQF workloads should be added to the 3-Node ReplSet variants and if corresponding 3-Node Bonsai variants should also be created. We've decided to add the workloads to the 3-Node ReplSet variants to build up a history and have opened a follow-up ticket ([PERF-4866](https://jira.mongodb.org/browse/PERF-4866)) to analyse the resulting noise and revisit moving the _high-value_ CQF workloads away from standalone variants to the 3-Nodes.
**Patch Testing Results:**  
- [Evergreen …

PERF-4695 Add filter_with_complex_logical_expression and array_traversal to 3-Node ReplSet variants

---

src/lamplib/src/genny/tasks/auto_tasks.py
src/lamplib/src/tests/test_auto_tasks.py

We shouldn't generate a global task for any workload that doesn't have an AutoRun block. These tasks aren't usable and pollute the namespace.
**Jira Ticket:** DEVPROD-2654
Don't generate a global task definition for Genny Workloads that don't have an AutoRun block. There is no reason to do this and it pollutes the global task namespace.
https://spruce.mongodb.com/version/655432d83066159f7eed78fa/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
The above patch is the fix for a naming conflict that was happening as part of PM-3362, since the "search" task name that was generated by Genny conflicted with an existing task. …

DEVPROD-2654: Don't generate tasks if no AutoRun block.

---

src/phases/query/BooleanSimplifier.yml
src/workloads/query/BooleanSimplifier.yml
src/workloads/query/BooleanSimplifierSmallDataset.yml

**Jira Ticket:** SERVER-77343
Add benchmarks that measure performance of boolean expressions which can be simplified by the Boolean Simplifier. 
**Patch testing results:**  [link](https://spruce.mongodb.com/version/6555d34861837d4298a2e825/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

SERVER-77343 Add Boolean simplification benchmarks

---

src/gennylib/src/topology.cpp
src/workloads/query/TimeseriesTsbsOptimizations.yml

Jira Ticket: [PERF-4868](https://jira.mongodb.org/browse/PERF-4868)
Whats Changed:
In this patch, I've changed it so that we avoid trying to call the configsvr topology visitor if a separate configsvr doesn't exist (because we're now running variants with a config shard). I've also added a LoggingActor to the timeseries query optimizations workload, which was otherwise quitting because there was no output to std::out on the new variants.
Patch testing results:
[patch 1 (a few failures)](https://spruce.mongodb.com/version/6553f27e562343b0a9b5a2b6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[patch 2 - with fix for canaries](https://spruce.mongodb.com/version/655512b8306615ba9bb0b357/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[patch 3 - with fix for …

PERF-4868 Run high value workloads on default sharding perf variants

---

src/phases/query/LookupCommands.yml
src/workloads/query/LookupUnwind.yml

**Jira Ticket:** PERF-4904
Adding genny performance benchmark that contains a pipeline with $lookup followed immediately by $unwind that unwinds the array result of the lookup.

PERF-4904 Add genny performance benchmark for $LU pushdown

---

src/workloads/query/TimeseriesBlockProcessing.yml

**Jira Ticket:** [PERF-4881](https://jira.mongodb.org/browse/PERF-4881)
Created a workload that runs against uniformly random timeseries data to target SBE block processing.
[Evergreen patch](https://spruce.mongodb.com/version/654d26803e8e86df96dc9eec/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
Form submitted!
**Related PRs:**

PERF-4881 Add genny workload targeting block processing

---

src/phases/execution/ClusteredCollection.yml
src/workloads/query/GraphLookup.yml
src/workloads/query/Lookup.yml
src/workloads/query/LookupColocatedData.yml
src/workloads/query/TenMDocCollection_ObjectId_Sharded.yml
src/workloads/sharding/ReshardCollection.yml
src/workloads/sharding/ReshardCollectionMixed.yml
src/workloads/sharding/ReshardCollectionReadHeavy.yml

**Jira Ticket:** [PERF-4889](https://jira.mongodb.org/browse/PERF-4889)
The numInitialChunks parameter was deprecated in [SERVER-74747](https://jira.mongodb.org/browse/SERVER-74747), and now 1 chunk per shard is created by default. 
Adjust workloads accordingly. 
Example patch run: https://spruce.mongodb.com/version/655f8149e3c3312d2f4f6616/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-4889 Remove the 'numInitialChunks' parameter used with 'ShardCollection' command

---

src/workloads/execution/CreateBigIndex.yml
src/workloads/execution/CreateIndex.yml
src/workloads/query/ExternalSort.yml

**Jira Ticket:** PERF-4942
Enable CreateIndex, CreateBigIndex and ExternalSort workloads for standalone-all-feature-flag variant
https://spruce.mongodb.com/version/656719e8e3c33182d9590cff/tasks

PERF-4942 Enable CreateIndex, CreateBigIndex and ExternalSort workloads for standalone-all-feature-flag variant

---

src/workloads/query/QueryStats.yml

**Jira Ticket:** PERF-4796
Runs query stats workloads on variants that use the shard-single mongodb_setup file
[🌲 ](https://spruce.mongodb.com/version/65650b51d6d80aacc1471789/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&statuses=success&variant=%5Elinux-shard-single.2022-11%24)
(only look at shard single variant)
This will run every Tuesday and Thursday.

PERF-4796: Run query stats workload on shard-single variants

---

src/phases/query/CollScanSimplifiablePredicate.yml
src/workloads/query/CollScanSimplifiablePredicateLarge.yml
src/workloads/query/CollScanSimplifiablePredicateMedium.yml
src/workloads/query/CollScanSimplifiablePredicateSmall.yml

**Jira Ticket:** SERVER-83896
Added benchmarks with complex expressions that can (at least in theory) be simplified by the optimizer. These benchmarks are run against collections of different sizes (100, 10K and 1M documents).
Running [here](https://spruce.mongodb.com/version/6576ef0d306615e62bf91bf4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC).
Done.
- https://github.com/mongodb/genny/pull/1081
- https://github.com/mongodb/genny/pull/1079

SERVER-83896 Add collscan benchmarks with complex expressions that can be simplified

---

src/workloads/query/TimeseriesBlockProcessing.yml

Apart for adding a new test where we have an explicit $and of $or using different comparisons (because the other $or inside an $and in the test MatchOnMultipleNestedFields is being converted into a $in given that is an equality of two constants), I also moved the active phases to avoid running two tests in the same phase

PERF-4969 Add TS task with compound $and and $or

---

src/workloads/query/TimeSeriesTelemetry.yml

The plan for this report requires supporting OR, filters on dotted paths, supporting dateTrunc, removing a few makeObj to avoid working on result document, allowing an unwind on non-block data, supporting grouping on compound key
Edit: PR link: https://spruce.mongodb.com/task/sys_perf_linux_3_node_replSet_all_feature_flags.2022_11_time_series_telemetry_patch_457b601676c17188abea53cf8c5b2c055e086581_657abde161837d04a2184d31_23_12_14_08_34_27/tests?execution=0&sortBy=STATUS&sortDir=ASC

PERF-4973 Add TS benchmark for a complex reporting task

---

src/phases/replication/startup/StartupPhasesTemplate.yml

Fix data distribution to only make one field (`int3`) have many docs with the same value to for the [sameKey dbcheck](https://github.com/mongodb/genny/blob/5e0f1bcab55d5fcbe105f2f689189a67a9959450/src/workloads/replication/dbcheck/dbcheck_40GB.yml#L222) test.

PERF-4986 Fix value distribution for dbcheck workload

---

src/phases/query/CollScanSimplifiablePredicate.yml
src/workloads/query/CollScanSimplifiablePredicateLarge.yml

[patch](https://spruce.mongodb.com/version/65819146306615863c7ce58a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
I've ran `coll_scan_simplifiable_predicate_large` on the failing variant (`Linux Standalone 2022-11`) 8 times now to ensure it doesn't randomly fail anymore. I'll restart it a few more times before merging.

PERF-4991 Reduce size of the largest predicates in CollScanSimplifiablePredicate

---

src/phases/query/RunLargeArithmeticOp.yml
src/workloads/query/ConstantFoldArithmetic.yml
src/workloads/query/DensifyFillCombo.yml
src/workloads/query/DensifyHours.yml
src/workloads/query/DensifyMilliseconds.yml
src/workloads/query/DensifyMonths.yml
src/workloads/query/DensifyNumeric.yml
src/workloads/query/DensifyTimeseriesCollection.yml
src/workloads/query/FillTimeseriesCollection.yml
src/workloads/query/LookupWithOnlyUnshardedColls.yml
src/workloads/query/MetricSecondaryIndexTimeseriesCollection.yml
src/workloads/query/TimeSeries2dsphere.yml
src/workloads/query/TimeSeriesSortCompound.yml
src/workloads/query/linearFill.yml
src/workloads/query/locf.yml

Jira Ticket:
[PERF-3784](https://jira.mongodb.org/browse/PERF-3784)
Whats Changed:
Replace RunCommand by CrudActor in query workloads
Patch testing results:
[evergreen build](https://spruce.mongodb.com/version/65858d17e3c3317c1525c371)
Workload Submission form:
NA
Related PRs:
NA

PERF-3784 Replace RunCommand by CrudActor in query workloads

---

src/cast_core/src/Loader.cpp
src/workloads/scale/LoadTest.yml

**Jira Ticket:** PERF-2540
log the average docs inserted per second
Run locally
15:03:06Z>  [2023-12-07 15:03:06.986267] [0x0000ffff7d320fc0] [info]    Phase still progressing (170s)
15:03:16Z>  [2023-12-07 15:03:16.987667] [0x0000ffff7d320fc0] [info]    Phase still progressing (180s)
15:03:25Z>  [2023-12-07 15:03:25.739824] [0x0000fffbed4b1fc0] [info]    Done with load phase. All 10000000 documents loaded into Collection0 duration(seconds) 187.857 53.23k docs/s
Not applicable

PERF-2540: log the average docs inserted per second

---

src/lamplib/src/genny/cli.py
src/lamplib/src/genny/tasks/auto_tasks_all.py

Since now variants are split across multiple files we need to allow scanning them all.
**Jira Ticket:** [DEVPROD-2159](https://jira.mongodb.org/browse/DEVPROD-2159)
Now that performance tasks are split across multiple files, auto_tasks_all needs to handle parsing tasks/variants from across multiple yaml files.

DEVPROD-2159: Allow multiple files containing variants.

---

src/workloads/query/GroupLikeDistinct.yml

**Jira Ticket:** [PERF-4956](https://jira.mongodb.org/browse/PERF-4956)
Added a wrokload which tests various $group with distinct like semantics, as well as with $top and $bottom accumulators which will be updated to also use DISTINCT_SCAN.
**Sys-Perf Patch** 
https://spruce.mongodb.com/version/658d0dfb850e617aeccc2832/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
I also added the results of one run onto this spreadsheet: 
https://docs.google.com/spreadsheets/d/1Y53LpA64G0egL5JRa5QH19Hr9QVGmntSg3KUOoez_PQ/edit#gid=0
We can see that the commands that don't use distinct scan are slower than those that do. Once I finish …

PERF-4956: Create genny workload for $group with distinct semantics

---

evergreen.yml
src/lamplib/src/genny/curator.py
src/lamplib/src/genny/tasks/compile.py
src/lamplib/src/genny/tasks/run_tests.py
src/lamplib/src/genny/toolchain.py

**Jira Ticket:** DEVPROD-1625
Compile genny on Amazon Linux 2023 (al2023.0).
Things worth noting:
-   `TOOLCHAIN_BUILD_ID` will be updated once [corresponding genny toolchain PR](https://github.com/10gen/vcpkg/pull/31) is merged and a new waterfall build of genny toolchain is done.
-   Why al2023.0 not al2023.2?
Currently, the mongodb toolchain version used by evergreen does not work with al2023.2. The error is the following (on al2023.2, the available SO verison is libffi.so.8):
```text
ImportError: libffi.so.6: cannot open shared object file: No such file or
directory
```
The latest mongodb toolchain has alrady been rebuilt on al2023.2 to fix this issue. Hence, when evergreen adopts the latest toolchain (an indication could be being unable to find libffi.so.8), update …

DEVPROD-1625: Compile genny on Amazon Linux 2023 (al2023.0)

---

src/workloads/query/GroupLikeDistinct.yml

Jira Ticket: [PERF-5019](https://jira.mongodb.org/browse/PERF-5019)
Whats Changed:
prevent workload from running on older versions before $top was added

PERF-5019: Prevent group_like_distinct from running on older versions

---

src/workloads/query/TimeseriesBlockProcessing.yml

**Jira Ticket:** [PERF-5026](https://jira.mongodb.org/browse/PERF-5026)
Enabling TimeseriesBlockProcessing workload in 7.0. This is required for timeseries perf dashboard to work.
[Evergreen patch](https://spruce.mongodb.com/version/659fb60e562343ebe57cfebc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-5026: Enable TimeseriesBlockProcessing.yml workload on sys-perf-7.0

---

src/lamplib/src/genny/tasks/dry_run.py
src/workloads/query/AggregationsOutput.yml

**Jira Ticket:** PERF-4830
We're adding a workload to test $out and $merge performance of aggregation output.
Evergreen run: https://spruce.mongodb.com/version/657b3b7e2a60ed0495276c2d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
**Workload Submission form:**
I've filled the form and submitted it as it is a new workload.

PERF-4830 Add workloads to test $out and $merge performance

---

evergreen.yml
src/lamplib/src/genny/cli.py
src/lamplib/src/genny/curator.py
src/lamplib/src/genny/tasks/auto_tasks.py
src/lamplib/src/genny/tasks/auto_tasks_all.py
src/lamplib/src/tests/test_auto_tasks_all.py

This adds an activate_generated_tasks parameter, which allows for specifying variant/task pairs as part of the version parameters. auto_task_all will generate all of those variant/task pairs with activate:true s that they are automatically run.
**Jira Ticket:** DEVPROD-3617
This adds an activate_generated_tasks parameter, which allows
for specifying variant/task pairs as part of the version
parameters. auto_task_all will generate all of those variant/task
pairs with activate:true so that they are automatically run. …

DEVPROD-3617: Allow users to specify a task to run on task generation.

---

src/lamplib/src/genny/tasks/auto_tasks_all.py
src/lamplib/src/tests/test_auto_tasks_all.py

Python string.split on an empty string doesn't return an empty list, so this was crashing task generation. Add some tests, a little bit of error handling, and handle the empty case.
**Jira Ticket:** [DEVPROD-3840](https://jira.mongodb.org/browse/DEVPROD-3840)
Fix the parsing for the activate_generated_tasks parameter
Blank activate_generated_tasls: https://spruce.mongodb.com/version/65a8036dc9ec44646ff8b242/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
Single Task Specified: https://spruce.mongodb.com/version/65a80399d6d80a7ced3a340a/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

DEVPROD-3840: Fix auto_tasks_all to handle empty parameter.

---

src/workloads/query/GroupLikeDistinct.yml

**Jira Ticket:** [PERF-5022](https://jira.mongodb.org/browse/PERF-5022)
Added an additional index to match the sorter in the actors for $top and $bottom, so that once https://jira.mongodb.org/browse/SERVER-84347 is complete, these will run with a distinct scan

PERF-5022: Fix sorter for $top and $bottom actors to match index in group_like_distinct

---

src/phases/query/RepeatedPathTraversal.yml
src/workloads/query/RepeatedPathTraversalMedium.yml
src/workloads/query/RepeatedPathTraversalSmall.yml

**Jira Ticket:** SERVER-84674
Extend the RepeatedPathTraversal workload by:
- Adding queries with longer common path prefixes
- Running it against collections of 100 and 10K documents (it was already running on 1M docs).
~[Patch](https://spruce.mongodb.com/version/65aa739f57e85a363231dc2c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)~
[Patch #2](https://spruce.mongodb.com/version/65ae4e0e850e61cdd0aefbe8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

SERVER-84674 Add queries with longer common path prefixes

---

src/phases/query/LookupCommands.yml
src/workloads/query/LookupOnly.yml

Improve Genny workload LookupUnwind.yml to:
1. Use 20,000 docs in the local collection instead of just one
2. Use join keys in 0-9 instead of always 1
Add a sister Genny workload LookupOnly.yml that does the same tests as LookupUnwind.yml except without the $unwind stage of the pipeline to make the performance difference with and without $unwind visible. ($lookup-$unwind, aka $LU, is a macro stage that does a $lookup followed immediately by an $unwind that unwinds the lookup's "as" result array, but implemented so as never to materialize that array at all.)
Currently both of these benchmarks use LookupStrategy::kHashJoin for all cases.
Change 1 is needed so the cost of building the hash table has a positive return on investment. (I also opened SERVER-85964 in QO to improve the join …

PERF-5078 Improve Genny LookupUnwind.yml and add LookupOnly.yml

---

src/lamplib/src/genny/tasks/auto_tasks.py
src/lamplib/src/tests/test_auto_tasks.py
src/lamplib/src/tests/test_auto_tasks_all.py

Auto-generated tasks are currently generated with a 7200 (2h) idle timeout, which can not be overridden by users.
Since this timeout [duplicates DSI's no_output_ms ](https://github.com/10gen/dsi/blob/62d5572cebf887e260fe25231e4decc95db9d9f5/configurations/test_control/defaults.original.yml#L8), my suggestion would be to make timeout_secs equal to exec_timeout_secs, which defacto disables the evergreen idle timeout for these tasks. This way, we only have the DSI idle timeout that can be more easily configured by users.

DEVPROD-4562 Update timeout_secs

---

src/workloads/query/QueryStats.yml

The only analysis we'll do for the 7.0 QueryStats backport that involves this workload is in th M60-like variant, so running it elsewhere is not needed.

Remove AutoRun from unnecessary variants in QueryStats.yml

---

src/workloads/query/TimeSeriesSort.yml

**Jira Ticket:** [PERF-5196](https://jira.mongodb.org/browse/PERF-5196)
As we discovered in [SERVER-87104](https://jira.mongodb.org/browse/SERVER-87104), MetaPointPredicateTimeSortBoundedSort query runs with explain which is likely to have different performance profile from running without explain and has hidden the performance metrics for runs without explain.
It should run without explain just like other queries in the same workload.
We will maintain both tests with and without explain until we can have enough data points to establish the baseline of test without explain and then will remove the test with explain.
**Updated Phases:**
0 - `CreateTimeSeriesCollection`
1 - `DropAllIndexesUponCreation`, `InsertData`
2 - `Quiesce`
3 - `SortQueryBoundedSort`
4 - …

PERF-5196 Add MetaPointPredicateTimeSortBoundedSortWithoutExplain to time_series_sort workload

---

src/workloads/query/InWithVariedArraySize.yml

**Jira Ticket:** PERF-5124
Added a workload for $in with different array lengths and in the presence and absence of indexes.
(Latest, 2/27, commit 4): https://spruce.mongodb.com/version/65de34ccd6d80aaff3c3d0f3/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
(2/26, Commit 3) https://spruce.mongodb.com/version/65dcf4e29ccd4e6d913d41f0/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-5124: Add workload for $in with different array lengths

---

src/lamplib/src/genny/curator.py

**Jira Ticket:** DEVPROD-2165
Redirect the output of Poplar into a log file. When the process finishes, review the log file to:
-   Print any "fatal error" to stderr
-   If the error OOM (or alike), print a message to suggest that the user uses a larger workload instance.
Previously the outputs of Poplar are log at the INFO level. Normally this is not an issue because Poplar prints almost nothing. But, when Poplar hits the OOM issue, it may print a huge stack trace, making it hard to spot the issue. See [this log](https://parsley.mongodb.com/evergreen/sys_perf_perf_1_node_replSet_longRunning.arm.aws.2023_11_llt_mixed_patch_798243406d1f483e46669d7d20f29f4d8f50ba01_65ddb0c20ae6063ec624c105_24_02_27_10_09_37/0/task?bookmarks=0,11604) for an example.
**Patch testing …

Devprod-2165 redirect and review Poplar outputs

---

src/workloads/docs/RunCommand-Simple.yml

**Ticket:** [SERVER-87415](https://jira.mongodb.org/browse/SERVER-87415)
**Patch:**
[Evergreen patch](https://spruce.mongodb.com/version/65e61ffa3e8e86404efa7789/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) showing that dsi_integ_test_run_command_simple no longer comes up on PERF Standalone ARM AWS 2023-11 and run_command__simple is not auto run on the relevant variants
**Related PRs:**
- [sys-perf changes](https://github.com/10gen/mongo/pull/19555)
- [DSI changes](https://github.com/10gen/dsi/pull/1584)

SERVER-87415 Remove run_command__simple workload from sys-perf

---

src/lamplib/src/genny/tasks/dry_run.py
src/workloads/scale/UpdateSingleLargeDocumentWith10kThreads.yml

**Jira Ticket:** [PERF-5144](https://jira.mongodb.org/browse/PERF-5144)
Adds a workload with 10k threads attempting to update the same 16MiB document. The large amount of write conflict retries, and the memory which is held while retrying, eventually causes an OOM kill.

PERF-5144 Add workload generating write conflicts on large document

---

src/workloads/query/multiplanner/NoResults.yml

**Jira Ticket:** PERF-5246
Add multiplanner workload where query predicates match no documents
https://spruce.mongodb.com/version/65f876e0aaa0f80007c5f141/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-5246 Add multiplanner workload where query predicates match no documents

---

src/value_generators/src/DocumentGenerator.cpp
src/value_generators/test/DocumentGeneratorTestCases.yml
src/workloads/docs/Generators.yml
src/workloads/streams/Passthrough_ChangeStreamSource.yml

Jira Ticket: SERVER-85660
Whats Changed:
The change stream source should only be consumed after all documents have been written and durably persisted in the mongo collection, so the stream processor should be started after all the documents have been added to the source collection. In order to this we need to use startAtOperationTime in the $source.config to tell the stream processor to consume the documents in the change stream source from the beginning. It doesn't seem like there is a great way to generate a BSON timestamp object that mongo IDL likes through genny YAML or through the existing generators, so added {^NowTimestamp: {}} generator for BSON timestamps, similar to BSON date generators. (NOTE: None of the BSON date generators work here because the mongo IDL explicitly wants a …

SERVER-85660: fix streams passthrough change stream source workload

---

src/lamplib/src/genny/tasks/dry_run.py
src/workloads/scale/CursorStormMongos.yml

Jira Ticket: [PERF-5184](https://jira.mongodb.org/browse/PERF-5184)
Whats Changed:
Add a new workload reproducing an OOM on mongos caused by a cursor storm.
Workload Submission form:
If applicable, only required if is a new workload being added. Form can be found [here](https://docs.google.com/forms/d/1r0kOHvFUa7rJxVmX_wp9prxYU5K155yKyZ1y3d5yhZg/edit)

PERF-5184 Add workload reproducing an OOM on mongos caused by a cursor storm

---

src/workloads/query/AggregationsOutput.yml

- Get rid of `MonotonicSingleLoader` usages. Use `Loader`s instead.
- Based on PM-3229 performance analysis work observations (WRITING-17072), I redefined some of the workloads:
-- Test single thread
-- Test single document size
-- Test different data set sizes (limiting using $limit). This helps show constant overheads vs O(dataSetSize) components.
:evergreen_tree: [EVG](https://spruce.mongodb.com/version/65f075ae0305b939a52d7047/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-5198 Rework AggregationsOutput workload to properly load initial documents

---

src/workloads/query/TimeseriesBlockProcessing.yml

[master](https://spruce.mongodb.com/version/65f9dbfa66f4c30007e27611/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[7.0](https://spruce.mongodb.com/version/65f9dd88f2db6a00071cfc25/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
Added tests | Op Throughput (master) | Op Throughput (7.0) | percent_diff
-- | -- | -- | --
AndMatchOnArrayField.TsBPAndMatchOnArrayFields | 0.268232986 | 0.115541292 | 132.1533552
AndOfOrFiltersOnArrayFields.TsBPAndOrMatchOnArrayFields | 0.102148626 | 0.058780248 | 73.78052913
AndOfSelectiveFiltersOnArrayFields.TsBPAndMatchOnArrayFields | 0.111988848 | 0.106482375 | 5.171252989
BasicMatchOnArrayField.TsBPBasicMatchOnArrayField | 0.269961855 | 0.151375481 | 78.33922192
MatchOnArrayFieldAndTime.TsBPMatchOnArrayFieldAndTime | 2.629579684 …

PERF-5274 Add queries in TimeseriesBlockProcessing workload that operates on array fields

---

src/workloads/query/multiplanner/ClusteredCollection.yml
src/workloads/query/multiplanner/UseClusteredIndex.yml

**Jira Ticket:** PERF-5120
ClusteredCollection workload that has huge _id.
UseClusteredIndex workload that has predicate on _id as selective as predicate on x1, making clustered index tied with x1 index.
https://spruce.mongodb.com/version/65fc278f3a0f5b000781f94d/tasks
Note: it depends on the monotonic loader PR #1155

PERF-5120 Add two multiplanner focused clustered collection workloads

---

src/workloads/sharding/BatchedUpdateOneWithoutShardKeyWithId.yml
src/workloads/sharding/BulkWriteBatchedUpdateOneWithoutShardKeyWithId.yml

**Jira Ticket:** SERVER-88082
Added two new workloads to measure performance under PM-3190
(https://spruce.mongodb.com/version/65f4b6c4c50c4400078120c8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[Pre-filled form](https://docs.google.com/forms/d/e/1FAIpQLSf1oh23Ddo1khjLZMqZ9DHbRdObnpeH20PSXTBuXVg-7mxxTA/viewform?usp=pp_url&entry.1544049958=PM-3190.+This+workload+tests+the+performance+of+batched+writes+without+shard+key+with+_id.&entry.621283182=Master+Only&entry.132161754=sys-perf&entry.1936323232=Linux+Shard+Lite+Cluster+2022-11(2+shards,+2+node+replica+sets,+once+per+day)&entry.1936323232=Linux+3-Shard+Cluster+2022-11+(once+per+week)&entry.1936323232=Linux+Shard+Lite+All+Feature+Flags+2022-11&entry.14828 …

SERVER-88082 Add workloads for WriteType::WriteWithoutShardKeyWithId

---

docs/using.md

For more context, see the description of [DEVPROD-4601](https://jira.mongodb.org/browse/DEVPROD-4601) as well as this internal stackoverflow post: https://mongodb.stackenterprise.co/questions/1151. In short, it wasn't clear to me at first that `test_result_summary.py` had its own Python requirements, so I wanted to make this more obvious in the genny documentation!

DEVPROD-4601 Make documentation of Python dependencies in contrib/analysis/ more discoverable

---

src/workloads/scale/MixedWorkloadsGennyStress.yml

**Jira Ticket:** [PERF-5282](https://jira.mongodb.org/browse/PERF-5282)
reduce runtime to prevent OOM on client mixed_workloads_genny_stress. The test currently fails because the workload client memory grows beyond the capacity of the system and crashes. Instead of increasing the instance size we are shortening the test to it finishes before it reaches this breaking point. I tested 30 min, 25 min, 20 min, and 15 min. 20 min was the longest time that didn't OOM die. It also had slightly lower noise than 15 min.
test | measurement | 20 min CV | 15 min CV
-- | -- | -- | --
Find_1024.Crud | Latency50thPercentile | 6.5% | 3.5%
Find_1024.Crud | Latency95thPercentile | 1.1% | 1.4%
Find_1024.Crud | OperationThroughput | 1.5% | 1.4%
Find_1024.findOne | Latency50thPercentile | …

PERF-5282 reduce runtime to prevent OOM on client mixed_workloads_genny_stress

---

src/workloads/query/multiplanner/MultiPlanningReadsALotOfData.yml

**Jira Ticket:** PERF-5304
Added QueryWithMultiplanningAndTieBreakingHeuristics that runs a query for which tie breaking heuristics will guess the correct index. Expected result would be that SBE multi planner will perform better for this kind of queries.
https://spruce.mongodb.com/version/6602ecc5f7a3490007adbe2a/tasks

PERF-5304 Add best-case scenario for SBE multi-planner, compared to Classic

---

src/workloads/scale/MixedWorkloadsGennyStress.yml
src/workloads/scale/MixedWorkloadsGennyStressWithScans.yml
src/workloads/sharding/WouldChangeOwningShardBatchWrite.yml

**Jira Ticket:** PERF-5308
shorten genny stressy workloads to 15 min to prevent OOM on all major releases of mongo
https://spruce.mongodb.com/version/66033c11ca19fe0007f985c7/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=mixed_workloads_genny_stress
N/A
https://github.com/mongodb/genny/pull/1163

PERF-5308: shorten genny stressy workloads to 15 min to prevent OOM on all major releases of mongo

---

src/workloads/issues/ConnectionPoolStress.yml

**Jira Ticket:** [PERF-5310](https://jira.mongodb.org/browse/PERF-5310)
shorten test from 10 min to 5 min to prevent OOM kill in 5.0. Does change performance numbers
test | measurement | 5 min | 10 min | percent_diff | z_score
-- | -- | -- | -- | -- | --
ConnectionPoolStress.Crud | Latency50thPercentile | 1031834 | 3313119.909 | -68.86% | -0.172901736
ConnectionPoolStress.Crud | Latency95thPercentile | 134613776 | 10857745.81 | 1139.79% | 53.65504642
ConnectionPoolStress.Crud | OperationThroughput | 99114.6887 | 48844.0739 | 102.92% | 4.665846322
ConnectionPoolStress.find | Latency50thPercentile | 997415 | 3175574.727 | -68.59% | -0.171927816
ConnectionPoolStress.find | Latency95thPercentile | 133955072 | 9849012.331 | 1260.09% | 53.40898504
ConnectionPoolStress.find …

PERF-5310 shorten connection_pool_stress to prevent OOM kill

---

src/workloads/streams/AddFields.yml
src/workloads/streams/LargeHoppingWindow.yml
src/workloads/streams/LargeTumblingWindow.yml
src/workloads/streams/LargeWindowMixed.yml
src/workloads/streams/LargeWindowUniqueAndExistingKeys.yml
src/workloads/streams/Passthrough.yml
src/workloads/streams/Passthrough_ChangeStreamSource.yml
src/workloads/streams/Passthrough_MongoSink.yml
src/workloads/streams/Search.yml
src/workloads/streams/StreamsLookup.yml
src/workloads/streams/TopKPerWindow.yml

Jira Ticket: SERVER-88846
Whats Changed:  
The start_StreamProcessor command has an options field which is not an optional field anymore. That is causing the workloads to fail. This change is to fix the broken stream workloads. Adding an empty options field in the phase which starts a stream processor.
https://spruce.mongodb.com/version/660b8c6b1f4649000769fdd7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

SERVER-88846 Fix Streams perf harness system failures due to missing 'options' field

---

.github/pull_request_template.md
docs/developing.md

Updates any references to the Evergreen Commit Queue to refer to the Github Merge Queue instead.
**Jira Ticket:** [DEVPROD-988](https://jira.mongodb.org/browse/DEVPROD-988)
Updates any references to the Evergreen Commit Queue to refer to the Github Merge Queue instead.
I will merge this after approval and after the Merge Queue changes are enabled.

DEVPROD-988: Docs changes for Genny switch to Merge Queue.

---

docs/generated/workloads.md
src/workloads/scale/Mixed10KThreads.yml

The read queries match on an increasing set of documents over time because we insert more data that matches the query predicate over time. Read throughput is directly influenced by write throughput. To reduce that influence, the find query will only return 10 documents per query.

SERVER-88684: Mixed10KThreads find operations limited to 10

---

src/workloads/query/multiplanner/MultikeyIndexes.yml

I noticed that all of the queries were using COLLSCAN plans. I think this helps to explain the current results for this workload presented here: https://github.com/10gen/product-perf-experimentations/blob/master/investigations/PERF-5121-compare-multiplanners/full-results.ipynb. Hopefully the results tell us something more meaningful about the three multi-planning code paths after this fix!
I'm verifying that the workload runs correctly locally, but haven't done any other testing of this change.
I will alert the perf build barons that change points (probably improvements) are expected for this workload as a consequence of this change!

DEVPROD-6453 Fix MultikeyIndexes.yml indexes so that multi-planning is exercised as intended

---

src/lamplib/src/genny/toolchain.py

**Jira Ticket:** PERF-5094
Updates the dependency for libmongocrypt to a recent version for Range V2 support. This is necessary for running the performance tests described in the linked ticket. When the next version of libmongocrypt releases, we plan to do another update to the toolchain version so that we don't have a git-hash version in the toolchain; see https://jira.mongodb.org/browse/PERF-5064
PR for toolchain change: https://github.com/10gen/vcpkg/pull/41

PERF-5094 Update toolchain version for libmongocrypt Range V2 support

---

src/workloads/query/CollScanComplexPredicateLarge.yml
src/workloads/query/CollScanComplexPredicateMedium.yml
src/workloads/query/CollScanComplexPredicateSmall.yml
src/workloads/query/CollScanSimplifiablePredicateLarge.yml
src/workloads/query/CollScanSimplifiablePredicateMedium.yml
src/workloads/query/CollScanSimplifiablePredicateSmall.yml
src/workloads/query/MetricSecondaryIndexTimeseriesCollection.yml
src/workloads/query/ProjectParse.yml
src/workloads/query/QueryStats.yml

Updating the auto-run branches on tasks that we added query stats auto-run configs for in PERF-5152 to include 6.0. Also, adding a query stats variant to the MetricSecondaryIndexTimeseriesCollection.yml auto-run because we'd like to get data from it on both backport branches. 
SERVER-87943 is adding the query stats variants that these will be run under to v6.0.
https://spruce.mongodb.com/version/6617fa2e8ce8480007b1695c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-5241 Update AutoRun in workloads relevant to the QueryStats 6.0 backport

---

docs/TPCH.md
docs/streams.md

JIRA Ticket: https://jira.mongodb.org/browse/DEVPROD-6718
Whats Changed:
We have added new documentation pages for the TPCH and Streams workloads. These workloads are run through test control files in DSI and call several Genny workloads within them. We will use these pages to link via the test control files.

DEVPROD-6718 - Create documentation page for TPCH and Streams workload

---

docs/generated/workloads.md
src/workloads/scale/MixedWorkloadsGennyStress.yml

**Jira Ticket:**
[BF-32921](https://jira.mongodb.org/browse/BF-32921)
shortened the workload from 15 min to 10 min to keep azure from OOM dying
[tested twice here](https://spruce.mongodb.com/task/sys_perf_perf_atlas_M60_real.intel.azure.2023_11_mixed_workloads_genny_stress_patch_fb988940d1ce9d0ff567a7d4385352237335b4cf_66268158e774ee00077b7176_24_04_22_15_28_21?execution=1&sortBy=STATUS&sortDir=ASC)

BF-32921: shortened from 15 min to 10 min to keep azure from OOM dying

---

src/lamplib/src/genny/curator.py
src/metrics/include/metrics/v2/event.hpp

This fixes a potential bug with the Genny hook via Curator into Poplar. [Poplar](https://github.com/mongodb/curator/blob/a1293258b30e04ea503e6b91b6b1628789e90093/operations/poplar.go#L21C34-L21C49) accepts the `POPLAR_RPC_HOST` and the `POPLAR_RPC_PORT` environment variables and defaults to `localhost` and `2288` if those environment variables are not set.
This change properly handles the `POPLAR_RPC_PORT` environment variable when setting up Genny to connect to Poplar. Prior to this change, Genny would attempt to connect to port `2288`, regardless of where the Poplar service was actually listening.

PERF-5302: Properly process port number environment variables captured by Poplar

---

src/workloads/query/TimeSeriesSortCompound.yml

**Jira Ticket:** [DEVPROD-6937](https://jira.mongodb.org/browse/DEVPROD-6937)
Passed in the hint correctly to the pipeline options, so we change from using a blocking sort to BoundedSorter. This should improve performance and remove a regression. See https://jira.mongodb.org/browse/BF-32682 for more details.
From local testing the throughput without the hint is below:
ops       : 50.0    
seconds   : 1378.591
ops per second: 0.0363 
The throughput with my change is:
throughput:
ops       : 50.0    
seconds   : 425.903 
ops per second: 0.1174 
There is a huge improvement locally. I'm running a sys-perf patch now to see the improvement on evergreen.
[patch link](https://spruce.mongodb.com/version/663105334e149a0007f16090/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
Results from the …

DEVPROD-6937 Pass hint correctly to TimeSeriesSortCompound aggregation

---

src/workloads/query/multiplanner/MultiplannerWithGroup.yml

**Jira Ticket:** [PERF-5359](https://jira.mongodb.org/browse/PERF-5359)
This corrects an error with the original implementation of the workload. Before the change, the $match stage had no selective predicates. As a result, all of the documents in the collection matched, which in turn caused the workload to be dominated by query execution time. Since this is a multi-planning benchmark, we instead want the time required to select a plan to be significant relative to the overall query runtime.
This change also has the nice side effect of making the workload run much more quickly overall.
The workload seems to work as expected when I run it locally. I have this patch build created, but I'm figuring out how to take advantage of [DEVPROD-2159](https://jira.mongodb.org/browse/DEVPROD-2159) in …

PERF-5359 use one selective predicate in MultiplannerWithGroup.yml workload

---

src/workloads/query/TimeSeriesSortCompound.yml

**Jira Ticket:** [DEVPROD-7139](https://jira.mongodb.org/browse/DEVPROD-7139)
We fixed how the hint was passed into this workload to solve a regression BF. However, this workload runs on 6.0, and the index used in the hint is created by default in 7.0.0. So the aggregation now fails, since the index hint can't be applied to the query plan.

DEVPROD-7139 Create the default time-series index for timeseries sort compound

---

src/workloads/contrib/qe_range_testing/templates/rc.yml.j2
src/workloads/encrypted/qe-range-age-100-0.yml
src/workloads/encrypted/qe-range-age-50-50.yml
src/workloads/encrypted/qe-range-balance-100-0.yml
src/workloads/encrypted/qe-range-balance-50-50.yml
src/workloads/encrypted/qe-range-timestamp-100-0.yml
src/workloads/encrypted/qe-range-timestamp-50-50.yml

**Jira Ticket:** [SERVER-90382](https://jira.mongodb.org/browse/SERVER-90382)
Followup to PERF-5094, fixing a bug I accidentally introduced in the workloads.
sys-perf: https://spruce.mongodb.com/version/663d20c77d13b100070fb410/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

SERVER-90382 Fix issues with phase + metadata in QE Range workloads

---

src/workloads/query/GroupStagesOnComputedFields.yml

**Jira Ticket:** [BF-33222](https://jira.mongodb.org/browse/BF-33222)
Set a "binSize" value to null. Originally it lacked a value. During YAML linting and formatting, we set its value to an empty string. Now, change it to `null` as the corresponding test failed with the value being an empty string.
[patch](https://spruce.mongodb.com/version/664154a8cd210900071d3a14/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
**Related PRs:**

BF-33222 set `binSize` to null instead of "" (empty string)

---

docs/generated/workloads.md
src/workloads/query/plan_cache/EmptyGroup.yml
src/workloads/query/plan_cache/MatchEqVaryingArray.yml

**Jira Ticket:** [PERF-5459](https://jira.mongodb.org/browse/PERF-5459)
I've added two new Genny benchmarks:
* $group on an empty collection, intended to show a case where the time taken by stage-builders matters.
* $eq with a varying array, intended to show a case where the Classic plan cache has a much better hit rate than the SBE plan cache.
I've spot checked it locally to make sure it does what we want.  I checked the number of plan cache entries in each scenario:
* empty $group
* master: 5 cache entries (one per query shape -- there are no parameters varying here)
* draft PR: 0 cache entries (because there are no indexes)
* $eq array
* master: 1000 cache entries (one per parameter value)
* draft PR: 1 cache entry (showing Classic's auto-parameterization working well)
I also looked at …

Perf 5459  compare disable sbe plan cache

---

src/phases/query/TimeSeriesLastpoint.yml
src/workloads/query/TimeSeriesLastpoint.yml

**Jira Ticket:** [PERF-5440](https://jira.mongodb.org/browse/PERF-5440)
- Fix wrong index creation for ascending time sort key queries
- Repeat optimized last point queries100 times instead of 10 to be able to collect on-cpu profiling
- Use `CrudActor` instead of `RunCommand` to execute the aggregates
- Use `OnlyActiveInPhases`
https://spruce.mongodb.com/version/663feee5e0ec0400072fd1cb/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-5440 Fix created indices for ascending sort key queries in TimeSeriesLastpoint.yml workload

---

src/workloads/query/TimeSeriesLastpoint.yml

**Jira Ticket:** [PERF-5522](https://jira.mongodb.org/browse/PERF-5522)
Fix `TimeSeriesLastpoint.yml` drop collection actor so that it does not return an error for non-existing collection on v6.0. This is a fix for BF-33490
sys-perf patch
https://spruce.mongodb.com/version/6659555749889e0007008b72/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
sys-perf-6.0 patch
https://spruce.mongodb.com/version/665956cfb800a30007b5ad40/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-5522 Fix time_series_lastpoint drop collection actor

---

src/lamplib/src/genny/tasks/compile.py
src/lamplib/src/genny/toolchain.py

**Jira Ticket:** [DEVPROD-7330](https://jira.mongodb.org/browse/DEVPROD-7330)
**This PR reduces the download and decompress stage of the genny install from 1.25 minutes to 5 seconds**. This reduces the total genny setup time from 6.8 minutes to 5.5 minutes, and reduces the genny compile time from 4.5 minutes to ~3.1 minutes.
The [PR in vcpkg](https://github.com/10gen/vcpkg/pull/42) must be approved and merged in first, to get a real build ID to use in this PR.
In a standard Genny setup on an average configuration (`infrastructure_provisioning = replica`) (metrics [here](https://ui.honeycomb.io/mongodb-4b/environments/production/datasets/dsi/result/Cx6TVokULBr)) takes 6.8 minutes. The steps are:
- 2.3 minutes on `workload_setup.genny.1.on_workload_client`, (bash script …

DEVPROD-7330 Don't use toolchain with intermediate build and debug artifacts

---

docs/generated/workloads.md
src/workloads/query/multiplanner/NoSuchField.yml

**Jira Ticket:** [PERF-5373](https://jira.mongodb.org/browse/PERF-5373)
I confirmed that as originally implemented, the multi-planning trial period would end after the plan using index `{x1: 1}` hit EOF. By changing this predicate from `{x: {$lt: *selectivity}}` to `{x1: { $lte: 1}}`, I've made it so that all of the indexed plans need to perform a large index scan. After this change, I've confirmed that none of the plans will hit EOF, and the trial period will instead terminate by hitting the "max works" condition.
In addition, I noticed that we were unnecessarily repeating the `collMod` command to hide indexes 1000 times, so I fixed this to just hide indexes once.
I've confirmed that this lints locally by running `./run-genny -v lint-yaml --format`.
Kicked off a patch build: …

PERF-5373 Fix NoSuchField.yml so that it hits 'max works' as intended

---

src/lamplib/src/genny/tasks/auto_tasks_all.py
src/lamplib/src/tests/test_auto_tasks_all.py

Variants that don't have a schedule_variant_auto_tasks task should not have tasks generated for them, since several of them don't work with task generation and none of them have been tested to work with task generation.
**Jira Ticket:** [DEVPROD-5102](https://jira.mongodb.org/browse/DEVPROD-5102)
This modifies auto_tasks_all so that it avoids generating tasks for variants that don't already have a schedule_variant_auto_tasks task. This fixes BF-31453
https://spruce.mongodb.com/version/665fa75cc5864900075c7a8d/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC
This should show that generate_all_variant_auto_tasks works.

DEVPROD-5102: Generating all auto_tasks should skip some variants.

---

evergreen.yml
src/lamplib/src/genny/curator.py

**Jira Ticket:** [DEVPROD-7874](https://jira.mongodb.org/browse/DEVPROD-7874)
Removed the special casing for Curator versions. Now, Genny always just grabs the version of Curator pinned below. Also, removed the testing for Ubuntu 1804 - it's EOL and as far as I can tell, we don't run any tests on that os anymore. Please correct me if I'm wrong on that though.
[Genny](https://spruce.mongodb.com/version/6661cdaf7f45dc0007653b7e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[Sys-perf
](https://spruce.mongodb.com/version/6661dc545f5be30007113ef2/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

DEVPROD-7874: Update Genny to use the latest version of Curator

---

src/lamplib/src/genny/cli.py
src/lamplib/src/genny/curator.py
src/lamplib/src/genny/tasks/dry_run.py
src/lamplib/src/genny/tasks/genny_runner.py

**Jira Ticket:** [DEVPROD-8018](https://jira.mongodb.org/browse/DEVPROD-8018)
This adds a new flag to Genny that allows for generating JSON rollups from the FTDC files output from workloads. It does so by iterating over the output data folder and calling out to Curator using a CLI. 
I gave it a default of "Off" to preserve the current default behavior. When testing locally, I did not see a significant amount of time added to the runtime of Genny when doing these rollups. 
[Sys-perf](https://spruce.mongodb.com/version/666a071466c328000796b15c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[Sys-perf with flag](https://spruce.mongodb.com/version/666a071466c328000796b15c/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=mixed)

DEVPROD-8018: Give Genny the ability to output JSON rollups

---

src/lamplib/src/genny/curator.py

**Jira Ticket:** [DEVPROD-8142](https://jira.mongodb.org/browse/DEVPROD-8142)
Updated the calculate-rollups command to also rollup canary FTDC files. This is needed because the canaries also are currently using the attachment system in Cedar.

DEVPROD-8142: Update Genny to also calculate rollups from canaries

---

src/workloads/scale/MassDeleteRegression.yml

**Jira Ticket:** PERF-5523
add a quiesce after deletes to remove tombstones for more stable results. CV goes down from 157% to 2%.
[multi-patch](https://performance-analyzer.server-tig.prod.corp.mongodb.com/perf-analyzer-viz/?comparison_id=26ef34f9-a29f-4c3e-92ce-6324d78caea2&selected_tab=data-table&percent_filter=0%7C%7C100&z_filter=0%7C%7C10)

PERF-5523 quiesce to remove tombstones for more stability

---

src/workloads/query/TimeseriesEnum.yml

**Jira Ticket:** [PERF-5628](https://jira.mongodb.org/browse/PERF-5628)
Changing the test to run on a smaller data set. This will help avoid timeouts (some of the queries currently take 6+ minutes). At the same time, this will not make the queries run so quickly that we don't get a good signal on the query's performance.
Patch build running here:
https://spruce.mongodb.com/version/667c46abea070d00079381c4/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

PERF-5628 Reduce runtime of TimeseriesEnum test

---

src/workloads/query/QueryStats.yml

**Jira Ticket:** PERF-5539
Enabling the `QueryStats` workload to auto-run on v6.0 now that the query stats feature flag is enabled there.
[Evergreen](https://spruce.mongodb.com/version/66845e3a5faa1b0007ef9a5c/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-5539 Enable QueryStats workload auto-run on v6.0

---

src/workloads/sharding/WouldChangeOwningShardBatchWrite.yml

**Jira Ticket:** [SERVER-87143](https://jira.mongodb.org/browse/SERVER-87143)
Skip  WouldChangeOwningShardBatchWrite workload on versions < 6.0.
[🌲 EVG](https://spruce.mongodb.com/version/66961fda4521620007b5f050/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

SERVER-87143 Skip WouldChangeOwningShardBatchWrite workload on versions < 6.0

---

src/workloads/query/AggregateExpressions.yml

**Jira Ticket:** [PERF-5507](https://jira.mongodb.org/browse/PERF-5507)
Fixed generation of array data to populate arrays of size 10, previously was only making arrays of size 1. 
Additionally fixed a query using an undefined field.

PERF-5507 Fix AggregateExpressions.yml query definition and data generation

---

src/workloads/scale/MajorityReads10KThreads.yml
src/workloads/scale/Mixed10KThreads.yml

**Jira Ticket:** [DEVPROD-9336](https://jira.mongodb.org/browse/DEVPROD-9336)
This disables the MajorityReads10KThreads workload from AutoRun
https://spruce.mongodb.com/version/66a7a595603f76000738232f/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

DEVPROD-9336 Disable MajorityReads10KThreads from AutoRun

---

src/workloads/query/ProjectParse.yml

**Jira Ticket:** [PERF-5738](https://jira.mongodb.org/browse/PERF-5738)
A pair of `Nop` phases didn't make it into the previous patch (my mistake). Adding them in for certain now.
[Patch](https://spruce.mongodb.com/version/66abab00e751700007781f74).

PERF-5738: Add missing Nop phases to ProjectParse

---

src/workloads/scale/MixedWorkloadsGenny.yml

**Jira Ticket:** PERF-5711
Replace quiesce with noop which appears to not impact the results in this test thankfully. This lets us then use this genny test to test rolling restarts. Instead of making genny quiesce handle a rolling restart we should keep this in mind for Locust
[patch](https://spruce.mongodb.com/version/66a9417b7f65a40007ac9e15/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-5711 remove quiesce so we can rolling restart

---

src/workloads/query/multiplanner/BlockingSort.yml
src/workloads/query/multiplanner/ClusteredCollection.yml
src/workloads/query/multiplanner/CompoundIndexes.yml
src/workloads/query/multiplanner/ManyIndexSeeks.yml
src/workloads/query/multiplanner/MultiPlanningReadsALotOfData.yml
src/workloads/query/multiplanner/MultikeyIndexes.yml
src/workloads/query/multiplanner/MultiplannerWithGroup.yml
src/workloads/query/multiplanner/NoResults.yml
src/workloads/query/multiplanner/NoSuchField.yml
src/workloads/query/multiplanner/NonBlockingVsBlocking.yml
src/workloads/query/multiplanner/Simple.yml
src/workloads/query/multiplanner/Subplanning.yml
src/workloads/query/multiplanner/UseClusteredIndex.yml
src/workloads/query/multiplanner/VariedSelectivity.yml

**Jira Ticket:** [DEVPROD-7308](https://jira.mongodb.org/browse/DEVPROD-7308)
Add single replica all feature flags variants to multiplanner Genny workloads.
[Patch](https://spruce.mongodb.com/version/66a2b4eab87fd00007bc4d87).

DEVPROD-7308: Run multiplanning Genny workloads on single-node all-feature-flags variants

---

src/lamplib/src/genny/toolchain.py

**Jira Ticket:** [PERF-5064](https://jira.mongodb.org/browse/PERF-5064)
Related vcpkg (toolchain) ticket: https://github.com/10gen/vcpkg/pull/43
Update toolchain version to latest.
sys-perf: https://spruce.mongodb.com/version/66be672a839af200074950d1/
Note: Currently, the toolchain points to a patch version. My plan is to first merge the vcpkg PR, then point the toolchain at the actual version, and rerun testing.

PERF-5064 Update toolchain version in order to use libmongocrypt 1.11.0

---

docs/generated/workloads.md
src/workloads/query/NonSearchHybridScoring.yml

**Jira Ticket:** [PERF-5546](https://jira.mongodb.org/browse/PERF-5546)
Adds a workload for a hybrid scoring like use-case, but without using any atlas search
features, since (at the time of this writing) they are complex to set up in our test
infrastructure.
[sys-perf patch](https://spruce.mongodb.com/version/66c62982e20f07000782b397/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[sys-perf-8.0 patch](https://spruce.mongodb.com/version/66c63550e206f50007f220d8/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
An earlier patch's performance analysis with only 2 out of 3 of the queries can be found here: https://performance-analyzer.server-tig.prod.corp.mongodb.com/perf-analyzer-viz/?comparison_id=db03934f-6299-43ec-bccf-62c7f160dfc3&selected_tab=data-table&test_filter=RankFusion.%2ACrud&percen …

PERF-5546 Add new workload for hybrid scoring (no search-y stages)

---

src/workloads/query/TenMDocCollection_IntId.yml

**Jira Ticket:** [PERF-5868](https://jira.mongodb.org/browse/PERF-5868)
Needed to change a comment, and maybe a test name, now that we use IDHACK for a query of the shape `{_id: {$eq: <value>}}`. And maybe we should add another query that doesn't use IDHACK to replace the one we lost here.

PERF-5868 Edit comment in TenMDocCollection_IntId about {_id: {$eq: <val>}}

---

.yamllint
docs/using.md
evergreen.yml
evergreen/system_perf/5.0/genny_tasks.yml
evergreen/system_perf/6.0/genny_tasks.yml
evergreen/system_perf/7.0/genny_tasks.yml
evergreen/system_perf/7.3/genny_tasks.yml
evergreen/system_perf/8.0/genny_tasks.yml
evergreen/system_perf/README.md
evergreen/system_perf/master/genny_tasks.yml
src/lamplib/requirements.txt
src/lamplib/src/genny/cli.py
src/lamplib/src/genny/tasks/auto_tasks.py
src/lamplib/src/genny/tasks/auto_tasks_all.py
src/lamplib/src/genny/tasks/auto_tasks_local.py
src/lamplib/src/tests/test_auto_tasks.py

**Jira Ticket:** [DEVPROD-10486](https://jira.mongodb.org/browse/DEVPROD-10486)
This PR replaces the task generation in evergreen with a locally pre-generated definition and a CI task that validates that the auto-generated task definitions are up to date.
The main driver here is that a lot of the analysis tooling gets more complicated with auto-generated tests. Additionally, this means that users can schedule Genny tasks directly through the evergreen UI like normal tasks. 
The downside is that users need to re-run the generation script if they are adding a new workload or if they are adding a new variant on which genny tasks are supposed to run (both of these should get rarer in the future since we are slowly moving away from Genny).
Companion PRs:
https://github.com/10gen/dsi/pull/1984 …

DEVPROD-10486 Move to local task generation

---

evergreen.yml
evergreen/system_perf/5.0/genny_tasks.yml
evergreen/system_perf/6.0/genny_tasks.yml
evergreen/system_perf/7.0/genny_tasks.yml
evergreen/system_perf/8.0/genny_tasks.yml
evergreen/system_perf/master/genny_tasks.yml
src/workloads/contrib/qe_range_testing/templates/rc-perfconfig.yml.j2

[PERF-5402](https://jira.mongodb.org/browse/PERF-5402): Convert shard-lite FLE variant to 3-Node
Converting FLE shard lite to shard.
Manually editing docs to get passed failed self test in [related DSI PR](https://github.com/10gen/dsi/pull/2046)
[7.0 Patch](https://spruce.mongodb.com/version/670553c9f049bf00071eb7e5/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[8.0 Patch](https://spruce.mongodb.com/version/6705364e77c87f0007a32030/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[Master Patch](https://spruce.mongodb.com/version/670534dccb2efd0007ed57b7/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

PERF-5402: Convert shard-lite FLE variant to 3-Node

---

docs/generated/workloads.md
src/workloads/scale/InsertRemove.yml

Reinstating "src/workloads/scale/InsertRemove.yml" as the task `mongo_perf_standalone_genny_InsertRemove` in the DSI merge queue requires this file.
- [DSI patch](https://spruce.mongodb.com/version/67077a8b83beda0007c6898b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) with this PR.

DEVPROD-11966: Reinstate InsertRemove.yml for DSI commit queue

---

evergreen.yml
src/lamplib/src/genny/cli.py
src/lamplib/src/genny/tasks/auto_tasks_local.py

**Jira Ticket:** [DEVPROD-11908](https://jira.mongodb.org/browse/DEVPROD-11908)
This PR allows users to configure a custom dsi/private_workloads repo when generating the genny tasks. This allows users to prepare fast-follow PRs for DSI changes that affect genny task scheduling.

DEVPROD-11908 Allow custom DSI repo in auto-tasks-local

---

src/phases/replication/startup/StartupPhasesTemplate.yml

**Jira Ticket:** [BF-35535](https://jira.mongodb.org/browse/BF-35535)
There seems to be a weird interaction with the code to suppress metrics from the RunCommand actor, and this test that [runs multiple genny tests in a single test_control file](https://github.com/10gen/dsi/blob/afedce8e11e4d23abecb699ba1d4c09aeca13095/configurations/test_control/test_control.startup.yml#L14-L75). Since we are going to deprecate Genny soon, this PR disables the metric suppression for this test rather than digging into the root cause.
[Baseline](https://spruce.mongodb.com/version/6722391725ee1400074813dc/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)
[Without ReportMetrics](https://spruce.mongodb.com/task/sys_perf_perf_1_node_replSet_test_commands.arm.aws.2023_11_startup_patch_7ffadf503022cac4b40f141ca52459 …

 BF-35535 Remove ReportMetrics for the startup test

---

src/workloads/sharding/ReshardCollection.yml

**Jira Ticket:** [SERVER-96485](https://jira.mongodb.org/browse/SERVER-96485)
The value of numInitialChunks in reshardCollection changed as a result of [SERVER-92762](https://jira.mongodb.org/browse/SERVER-92762). This PR fixes an issue where there isn't enough cardinality to create required number of chunks by increasing shard key space to allow more values in sampling.
Patch: https://spruce.mongodb.com/version/67291fe9d282fc00076f9c70/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

SERVER-96485 Increase shard key space

---

src/lamplib/src/genny/tasks/genny_runner.py

As part of #1277 - upgrading the requests package drops support for Python 3.7. Lets check that Genny doesn't use 3.7 before accepting the upgrade. This should output a easy to discover log we can collate to see what versions of Python are being used by Genny.
Also removed some unused imports

DEVPROD-13594 Adding an SLOG statement to the genny_runner to collect Python version info

---

docs/generated/workloads.md
src/phases/query/TimeSeriesLastpoint.yml
src/workloads/query/TimeSeriesLastpoint.yml

[PERF-6695](https://jira.mongodb.org/browse/PERF-6695)
The previous query used $regex which meant that the queries couldn't use DISTINCT_SCAN. Changing to $in/$nin allows the queries to use DISTINCT_SCAN, testing the optimizations we want.

PERF-6695 Fix timeseries lastpoint to use DISTINCT_SCAN

---

docs/generated/phases.md
docs/generated/workloads.md
src/workloads/query/UpdateLargeDocuments.yml

**Jira Ticket:** [PERF-5143](https://jira.mongodb.org/browse/PERF-5143)
Removed `Threads: 50` annotation as it is not applied anyway.

PERF-5143 Remove unused threads configuration
